const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const read=p=>fs.readFileSync(path.join(__dirname,p),'utf8');
const C=require('./race-core.js'),three=require('./vendor/three.min.js');
const trackContext={THREE:three,RaceCore:C};vm.createContext(trackContext);vm.runInContext(read('track.js'),trackContext);const track=trackContext.RaceTrack;
const gas={throttle:true,brake:false,steer:0,drift:false},dt=1/120;
function solo(){const s=C.createRace(track);for(const r of s.racers.slice(1)){r.x=10000+r.id*20;r.z=10000;r.finishTime=0;r.contact=10000;}s.pickups=[];return s;}
function place(s,r,d,speed=30,lane=0){const p=s.track.sample(d,lane);Object.assign(r,{x:p.x,y:p.y,z:p.z,yaw:Math.atan2(p.tx,p.tz),vx:p.tx*speed,vz:p.tz*speed,speed,d,lane,nearD:p.d,surface:p,lastSafeD:d,grounded:true,phase:'driving',phaseTime:0,yawRate:0,steering:0,vy:0,jumpOrigin:null});}
function run(s,input,seconds){for(let i=0;i<seconds/dt;i++)C.step(s,typeof input==='function'?input(s):input,dt);}
assert(track.length>1800,'Longer course exceeds 1.8 km');
const elevations=track.segments.map(s=>s.a.y);assert(Math.max(...elevations)-Math.min(...elevations)>55,'Real elevation change exceeds 55 m');assert.equal(track.gaps.length,2);
for(const gap of track.gaps){assert(!track.sample((gap.start+gap.end)/2).ground);assert(track.sample(gap.start-1).slope>.15,'Raised approach ramp');assert(track.sample(gap.end+1).ground);}
// On a bend, releasing the wheel must preserve the world heading and straight trajectory.
const straight=solo(),p=straight.racers[0];place(straight,p,440,26);const before={x:p.x,z:p.z,yaw:p.yaw};run(straight,gas,.65);assert.equal(p.phase,'driving');assert(Math.abs(C.angle(p.yaw-before.yaw))<1e-10,'No automatic steering on curves');assert(Math.abs((p.x-before.x)*Math.cos(before.yaw)-(p.z-before.z)*Math.sin(before.yaw))<1e-8,'No rail-following motion');
const right=solo(),left=solo();place(right,right.racers[0],20,32);place(left,left.racers[0],20,32);const yaw=right.racers[0].yaw;run(right,{...gas,steer:1},.4);run(left,{...gas,steer:-1},.4);assert(C.angle(right.racers[0].yaw-yaw)<-.3,'Right steering turns decisively');assert(C.angle(left.racers[0].yaw-yaw)>.3,'Left steering turns decisively');assert(right.racers[0].lane>1&&left.racers[0].lane< -1);
const sliding=solo(),gripping=solo();place(sliding,sliding.racers[0],15,32);place(gripping,gripping.racers[0],15,32);run(sliding,{...gas,steer:.65,drift:true},.7);run(gripping,{...gas,steer:.65},.7);assert(Math.abs(sliding.racers[0].slip)>Math.abs(gripping.racers[0].slip)*2,'Drift preserves lateral momentum');assert(Math.abs(sliding.racers[0].slip)>.25,'Body and travel direction differ during drift');
const charged=solo();charged.track={...track,width:1000};place(charged,charged.racers[0],300,35);run(charged,{...gas,steer:.55,drift:true},1.4);assert(charged.racers[0].drift>.55,'Real slip charges boost');C.step(charged,gas,dt);assert(charged.racers[0].boost>0,'Drift release grants turbo');
const fakeDrift=solo();place(fakeDrift,fakeDrift.racers[0],20,30);run(fakeDrift,{...gas,drift:true},.5);assert.equal(fakeDrift.racers[0].drift,0,'Holding drift on a straight grants nothing');
const off=solo(),op=off.racers[0],exitD=420;place(off,op,exitD,22,11.15);op.yaw-=Math.PI/2;op.vx=Math.sin(op.yaw)*22;op.vz=Math.cos(op.yaw)*22;C.step(off,gas,dt);assert.equal(op.phase,'falling','Kart leaves the edge without an invisible wall');const anchor=op.respawnD;while(op.phase==='falling')C.step(off,gas,dt);assert.equal(op.phase,'respawning');assert(Math.abs(op.lane)<1e-8);assert.equal(op.d,anchor);assert.equal(op.speed,2);while(op.phase==='respawning')C.step(off,gas,dt);assert.equal(op.phase,'driving');assert(op.grounded&&op.shield>0,'Respawn includes recovery animation and temporary protection');
let completedJumps=0;
for(const gap of track.gaps){const jump=solo(),jp=jump.racers[0];place(jump,jp,gap.start-.4,46);let airborne=false,landed=false,maxY=jp.y;for(let i=0;i<350;i++){C.step(jump,gas,dt);maxY=Math.max(maxY,jp.y);if(!jp.grounded)airborne=true;if(airborne&&jp.grounded){landed=true;break;}}assert(airborne&&landed,'Each drawbridge can be cleared with speed');assert.equal(jp.falls,0);assert(maxY>track.sample(gap.start).y+1,'A jump has vertical flight');completedJumps++;}
const short=solo(),sp=short.racers[0];place(short,sp,track.gaps[0].start-.3,10);let failed=false;for(let i=0;i<250;i++){C.step(short,{...gas,throttle:false},dt);if(sp.phase==='falling'){failed=true;break;}}assert(failed,'Insufficient speed falls into the gap');assert(sp.respawnD<track.gaps[0].start-40,'Failed jump returns to a usable run-up');
const thrown=solo(),tp=thrown.racers[0],victim=thrown.racers[1];place(thrown,tp,10,30);victim.x=tp.x+Math.sin(tp.yaw)*23;victim.z=tp.z+Math.cos(tp.yaw)*23;victim.y=tp.y;victim.vx=20;victim.speed=20;tp.item='coconut';assert(C.useItem(thrown));assert.equal(tp.item,null);assert(!C.useItem(thrown));const bulletX=thrown.projectiles[0].x;run(thrown,gas,.05);assert.notEqual(thrown.projectiles[0].x,bulletX,'Thrown item travels through world space');run(thrown,gas,.5);assert(victim.stun>1,'Coconut collision slows an opponent');
const blast=solo(),bp=blast.racers[1],shielded=blast.racers[2];place(blast,bp,20,20);place(blast,shielded,20,20,3);bp.finishTime=shielded.finishTime=0;shielded.shield=7;blast.projectiles.push({id:1,owner:0,type:'bomb',x:bp.x,y:bp.y+.3,z:bp.z,vx:0,vz:0,vy:-1,age:.5,life:4,nearD:20});C.step(blast,gas,dt);assert(bp.stun>2,'Bomb explosion slows nearby racer');assert.equal(shielded.stun,0,'Shield blocks an explosion');assert(blast.effects.length>0,'Hits produce visible effects');
const pickup=C.createRace(track);place(pickup,pickup.racers[0],pickup.pickups[0].d-.2,20);C.step(pickup,gas,dt);assert(pickup.racers[0].item,'Actual pickup grants a carriable item');
const finish=C.createRace(track);let jumps=0;for(let i=0;i<35000&&!finish.finished;i++){C.step(finish,C.botInput(finish,finish.racers[0]),dt);if(finish.events.includes('ЧИСТОЕ ПРИЗЕМЛЕНИЕ!'))jumps++;finish.events=[];}assert(finish.finished,'Physical course is completable for three laps');assert.equal(finish.lapTimes.length,3);assert(jumps>=6,'Three laps include both jumps');assert(finish.rank>=1&&finish.rank<=6);const time=finish.time;C.step(finish,gas,dt);assert.equal(finish.time,time);
assert.equal(C.formatTime(61.259),'01:01.25');
console.log(`OK: world-space steering, no assistance, lateral drift, turbo, ${completedJumps} gaps, failed jump, recovery, projectiles, shields, pickups, full 3-lap course (${finish.time.toFixed(1)} s with a test driver).`);

// Progress belongs to each hero. Upgrades change actual acceleration/braking, not just labels.
const profile=C.newProfile();assert.equal(profile.heroes.length,5);assert.equal(C.skillPoints(profile.heroes[0]),3);assert(C.upgrade(profile,0,'speed'));assert.equal(profile.heroes[1].upgrades.speed,0);assert(C.upgrade(profile,0,'aero'));assert(C.upgrade(profile,0,'braking'));assert(!C.upgrade(profile,0,'handling'),'Cannot overspend');assert(!C.upgrade(profile,0,'__proto__'));assert.deepEqual(C.parseProfile(JSON.stringify(profile)),profile);assert.throws(()=>C.parseProfile('{broken'));assert.throws(()=>C.parseProfile(JSON.stringify({version:99,heroes:[]})));const bad=C.newProfile();bad.heroes[0].upgrades.speed=5;assert.throws(()=>C.parseProfile(JSON.stringify(bad)),'Reject overspent save');
const baseStats=C.stats(0),maxStats=C.stats(0,Object.fromEntries(C.STAT_KEYS.map(k=>[k,5])));for(const k of C.STAT_KEYS)assert(maxStats[k]>baseStats[k],k+' grows');assert(C.stats(0,{aero:5}).handling>baseStats.handling&&C.stats(0,{aero:5}).acceleration>baseStats.acceleration,'Aerodynamics affects control and acceleration');
function physicsTrial(levels,input,speed){const s=solo();s.racers[0].cfg=C.stats(0,levels);place(s,s.racers[0],15,speed);run(s,input,.4);return s.racers[0];}
assert(physicsTrial({acceleration:5},gas,0).speed>physicsTrial({},gas,0).speed,'Upgrade reaches drive physics');assert(physicsTrial({braking:5},{...gas,throttle:false,brake:true},30).speed<physicsTrial({},{...gas,throttle:false,brake:true},30).speed,'Better brakes reduce speed sooner');
const rewardProfile=C.newProfile();finish.rewardClaimed=false;const reward=C.awardRace(rewardProfile,finish);assert(reward.xp>0&&rewardProfile.heroes[0].xp===reward.xp);assert(C.skillPoints(rewardProfile.heroes[0])>3);assert.equal(C.awardRace(rewardProfile,finish),null,'No duplicate finish rewards');const ravenReward=C.awardRace(C.newProfile(),{...finish,driver:3,rewardClaimed:false});assert(ravenReward.xp>reward.xp,'Raven earns extra experience');assert(C.stats(1).armor===.65&&C.stats(0).driftGain===1.3&&C.stats(2).landingBoost===1.2&&C.stats(4).boost===1.3,'Each hero has a distinct implemented passive');
// The aim rule selects only live opponents in front. One random roll is made per throw.
const aimed=C.createRace(track),ap=aimed.racers[0];place(aimed,ap,10,0);for(const e of aimed.racers.slice(1)){e.x=9000+e.id*5;e.z=9000;}const target=aimed.racers[1];target.x=ap.x+Math.sin(ap.yaw)*30;target.z=ap.z+Math.cos(ap.yaw)*30;target.y=ap.y;ap.item='coconut';assert.equal(C.aimTarget(aimed).id,1);target.x=ap.x-Math.sin(ap.yaw)*30;target.z=ap.z-Math.cos(ap.yaw)*30;assert.equal(C.aimTarget(aimed),null,'No lock behind the car');target.x=ap.x+Math.sin(ap.yaw)*30;target.z=ap.z+Math.cos(ap.yaw)*30;
let guided=0;for(let i=0;i<10000;i++){ap.item=i%2?'bomb':'coconut';aimed.projectiles=[];C.useItem(aimed);if(aimed.projectiles[0].targetId===1)guided++;else assert.equal(aimed.projectiles[0].missTargetId,1);}assert(Math.abs(guided/10000-.7)<.015,'Guidance probability is 70%');
function outcome(seed){const s=C.createRace(track);place(s,s.racers[0],15,0);for(const e of s.racers.slice(1)){e.x=9000+e.id*5;e.z=9000;e.finishTime=0;}const r=s.racers[1];place(s,r,45,0);r.finishTime=null;r.stun=10;s.racers[0].item='coconut';s.rng=seed;C.useItem(s);const guided=s.projectiles[0].targetId===1;run(s,{...gas,throttle:false},.9);return {guided,hit:s.metrics.hits>0};}
assert.deepEqual(outcome(1),{guided:true,hit:true},'Guided projectile physically reaches target');assert.deepEqual(outcome(1500),{guided:false,hit:false},'Miss roll does not hit locked target');
for(const course of trackContext.RaceTracks.slice(1)){const s=C.createRace(course,4);for(let i=0;i<42000&&!s.finished;i++){C.step(s,C.botInput(s,s.racers[0]),dt);s.events=[];}assert(s.finished,course.name+' is completable');assert(s.metrics.jumps>=6);assert.notEqual(course.segments[500].a.x,track.segments[500].a.x,'Distinct course geometry');}
console.log(`OK: five heroes, individual RPG saves/points/caps, upgrade physics, rewards, passives, three complete courses, front-only lock, guided hit/miss; ${guided}/10000 guided throws.`);

// Execute real scene/UI with GPU and DOM replaced; this is not a visual/FPS check.
const html=read('index.html'),nodes=new Map(),events={};
function element(id='',classes=''){const set=new Set(classes.split(' '));return {id,style:{},dataset:{},textContent:'',innerHTML:'',listeners:{},classList:{add:x=>set.add(x),remove:x=>set.delete(x),contains:x=>set.has(x),toggle(x,on){const yes=on===undefined?!set.has(x):on;yes?set.add(x):set.delete(x);return yes;}},addEventListener(type,fn){this.listeners[type]=fn;},setAttribute(){},focus(){context.document.activeElement=this;},blur(){},querySelector(){return element();},getContext(){return new Proxy({},{get:(_,k)=>k==='createRadialGradient'?()=>({addColorStop(){}}):()=>{}});}};}
for(const tag of html.matchAll(/<[^>]*\bid="([^"]+)"[^>]*>/g))nodes.set(tag[1],element(tag[1],tag[0].match(/class="([^"]+)"/)?.[1]||''));
const drivers=Array.from({length:5},(_,i)=>Object.assign(element(),{dataset:{driver:String(i)}})),buttons=['KeyA','KeyD','Space','KeyS','KeyW'].map(key=>Object.assign(element(),{dataset:{key}}));
const courseButtons=Array.from({length:3},(_,i)=>Object.assign(element(),{dataset:{track:String(i)}})),upgradeButtons=C.STAT_KEYS.map(k=>Object.assign(element(),{dataset:{upgrade:k}})),saved=new Map();
let frames=0,lastScene;
class Renderer{constructor(){this.shadowMap={};}setPixelRatio(){}setSize(){}render(scene,camera){frames++;scene.updateMatrixWorld();camera.updateMatrixWorld();lastScene=scene;}}
const context={console,THREE:{...three,WebGLRenderer:Renderer},innerWidth:1440,innerHeight:900,performance:{now:()=>0},matchMedia:()=>({matches:false}),requestAnimationFrame:fn=>{context.frame=fn;},localStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)},document:{getElementById(id){assert(nodes.has(id),`Element ${id} exists`);return nodes.get(id);},querySelector:()=>element(),querySelectorAll:q=>q==='[data-driver]'?drivers:q==='[data-key]'?buttons:q==='[data-track]'?courseButtons:q==='[data-upgrade]'?upgradeButtons:[],createElement:()=>element(),body:element(),documentElement:element(),addEventListener(type,fn){events['document:'+type]=fn;}}};context.window=context;context.addEventListener=(type,fn)=>{events[type]=fn;};vm.createContext(context);vm.runInContext(read('race-core.js'),context);vm.runInContext(read('track.js'),context);
const gameSource=read('game.js'),end=gameSource.lastIndexOf('})();');vm.runInContext(gameSource.slice(0,end)+'globalThis.probe={get mode(){return mode;},get state(){return state;},set state(s){state=s;},get selected(){return selected;},get models(){return models;},get profile(){return profile;},get track(){return track;},get smoke(){return smoke;},get skidCount(){return skidCount;},sample,camera,projectileViews,placeKarts,updateAtmosphere,updateHUD};\n'+gameSource.slice(end),context);
let now=0;function frame(n=1){for(let i=0;i<n;i++){now+=1000/60;context.frame(now);}}function click(id){nodes.get(id).listeners.click();}function key(code,down=true){events[down?'keydown':'keyup']({code,preventDefault(){},repeat:false});}
frame();assert(frames>0);lastScene.traverse(child=>{assert(child.position.toArray().every(Number.isFinite));if(child.geometry?.attributes.position)assert(Array.from(child.geometry.attributes.position.array).every(Number.isFinite));});
const roadMeshes=[];lastScene.traverse(m=>{if(m.name==='track-strip')roadMeshes.push(m);});
for(const gap of track.gaps){const middle=track.sample((gap.start+gap.end)/2),ray=new three.Raycaster(new three.Vector3(middle.x,middle.y+80,middle.z),new three.Vector3(0,-1,0));assert.equal(ray.intersectObjects(roadMeshes).length,0,'Visible bridge opening has no road geometry');}
drivers[2].listeners.click();assert.equal(context.probe.selected,2);click('openForge');nodes.get('forge').listeners.keydown({code:'Tab',shiftKey:true,preventDefault(){}});assert.equal(context.document.activeElement,nodes.get('forgeDone'));nodes.get('forge').listeners.keydown({code:'Tab',shiftKey:false,preventDefault(){}});assert.equal(context.document.activeElement,nodes.get('closeForge'));upgradeButtons[0].listeners.click();assert.equal(context.probe.profile.heroes[2].upgrades.speed,1);assert.equal(context.probe.profile.heroes[0].upgrades.speed,0);assert.equal(C.parseProfile(saved.get('wild-drift-ashen-profile-v1')).heroes[2].upgrades.speed,1);click('forgeDone');courseButtons[1].listeners.click();click('start');assert.equal(context.probe.track.id,'thorn');assert(context.probe.state.racers[0].cfg.speed>C.DRIVERS[2].speed);assert.equal(context.probe.mode,'countdown');frame(220);assert.equal(context.probe.mode,'race');key('KeyW');frame(90);assert(Number(nodes.get('speed').textContent)>0);const player=context.probe.state.racers[0];player.item='coconut';frame();assert(context.probe.models[0].items.coconut.visible,'Picked-up item appears in the character hand');assert(!context.probe.models[0].items.bomb.visible);key('ShiftLeft');frame();assert(!context.probe.models[0].items.coconut.visible,'Throw removes the item from the hand');assert(context.probe.projectileViews.some(v=>v.g.visible),'Thrown item renders in the world');
const pausedTime=context.probe.state.time;key('Escape');frame(60);assert.equal(context.probe.state.time,pausedTime);key('Escape');key('KeyW');frame(10);assert(context.probe.state.time>pausedTime);events.blur();assert.equal(context.probe.mode,'paused');click('resume');key('KeyR');frame();assert.equal(context.probe.state.racers[0].phase,'falling');frame(51);assert.equal(context.probe.state.racers[0].phase,'respawning');assert(context.probe.models[0].respawnRing.visible,'Respawn effect is displayed');
finish.rewardClaimed=false;context.probe.state=finish;frame();assert.equal(context.probe.mode,'finish');assert(!nodes.get('finish').classList.contains('hidden'));assert(nodes.get('finishTime').textContent.length>0);click('again');assert.equal(context.probe.state.time,0);click('pauseButton');click('back');assert.equal(context.probe.mode,'menu');
for(const m of html.matchAll(/(?:src|href)="([^"#]+)"/g)){assert(!/^https?:/.test(m[1]));assert(fs.existsSync(path.join(__dirname,m[1])));}
console.log('OK: scene geometry, real bridge openings, hand items, projectile rendering, HUD, pause, recovery animation, results, replay, offline assets. GPU output and FPS are not tested.');

assert(saved.has('wild-drift-ashen-profile-v1'));assert(nodes.get('reward').textContent.includes('опыта'));courseButtons[2].listeners.click();drivers[4].listeners.click();click('start');assert.equal(context.probe.track.id,'frost');assert.equal(context.probe.models[0].g.name,'hero-4');assert.equal(lastScene.children.filter(c=>c.name==='course').length,1,'World switching removes old geometry');console.log('OK: forge buttons save individual upgrades, course selection swaps the world, all five hero models build, finish grants XP.');

// Rendered effects follow live race state; no GPU/image-quality assertion is made here.
const renderState=context.probe.state,rp=renderState.racers[0];place(renderState,rp,15,32);rp.drifting=true;rp.slip=.4;context.probe.placeKarts(1);rp.x+=Math.sin(rp.yaw)*.5;rp.z+=Math.cos(rp.yaw)*.5;context.probe.placeKarts(1);context.probe.updateAtmosphere(.1);assert(context.probe.skidCount>0,'Drift lays real road geometry');assert(context.probe.smoke.some(p=>p.life>0&&p.sprite.visible&&p.sprite.material.opacity>0),'Drift emits visible smoke');
for(const e of renderState.racers.slice(1)){e.x=9000+e.id*5;e.z=9000;}const lock=renderState.racers[1];lock.x=rp.x+Math.sin(rp.yaw)*25;lock.z=rp.z+Math.cos(rp.yaw)*25;lock.y=rp.y;rp.item='bomb';context.probe.camera.position.set(rp.x-Math.sin(rp.yaw)*12,rp.y+6,rp.z-Math.cos(rp.yaw)*12);context.probe.camera.lookAt(lock.x,lock.y+2,lock.z);context.probe.updateHUD();assert(!nodes.get('reticle').classList.contains('hidden'),'Held throwable shows a reticle on a target ahead');rp.item=null;context.probe.updateHUD();assert(nodes.get('reticle').classList.contains('hidden'),'Reticle clears when no throwable is held');
const runeBoost=C.createRace(track,4);place(runeBoost,runeBoost.racers[0],track.pads[0],20);C.step(runeBoost,gas,dt);assert(Math.abs(runeBoost.racers[0].boost-1.6*1.3)<1e-8,'Wolf passive also extends rune pad boosts');
console.log('OK: keyboard focus stays in the forge, drift smoke and road trails render, held items drive the target reticle, rune pads apply the wolf passive.');

// Cover-inspired geometry and ambient animation must survive real scene transitions.
const visualHero=context.probe.models[0];let heroDraws=0;visualHero.g.traverse(o=>{if(o.isMesh)heroDraws++;});assert(heroDraws<95,'Ornamental details are batched instead of separate draw calls');
for(const type of [0,3,4]){const k=context.probe.models.find(m=>m.g.name==='hero-'+type);assert(k&&k.head&&k.cape&&k.arms.length===2,'Cover heroes have a sculpted head, cape and articulated arms');const bounds=new three.Box3().setFromObject(k.head);assert(bounds.getSize(new three.Vector3()).z>.7,'Animal muzzle has depth');}
const banner=lastScene.getObjectByName('wind-banner'),bird=lastScene.getObjectByName('raven'),weather=lastScene.getObjectByName('airborne-particles');assert(banner&&bird&&weather&&lastScene.getObjectByName('gothic-city'));
const capeBefore=Array.from(visualHero.cape.geometry.attributes.position.array),flagBefore=Array.from(banner.geometry.attributes.position.array),birdBefore=bird.position.clone(),weatherBefore=Array.from(weather.geometry.attributes.position.array);frame(50);
assert.notDeepEqual(Array.from(visualHero.cape.geometry.attributes.position.array),capeBefore,'Cape moves in wind');assert.notDeepEqual(Array.from(banner.geometry.attributes.position.array),flagBefore,'Banners ripple');assert(bird.position.distanceTo(birdBefore)>0,'Birds circle the cathedral');assert.notDeepEqual(Array.from(weather.geometry.attributes.position.array),weatherBefore,'Air particles move');
click('pauseButton');const still=Array.from(banner.geometry.attributes.position.array),birdStill=bird.position.clone();frame(90);assert.deepEqual(Array.from(banner.geometry.attributes.position.array),still,'Pause freezes cloth');assert.equal(bird.position.distanceTo(birdStill),0,'Pause freezes world motion');click('resume');frame(10);assert.notDeepEqual(Array.from(banner.geometry.attributes.position.array),still,'World resumes after pause');
const geometryCount=()=>{let n=0;lastScene.traverse(o=>{if(o.geometry)n++;});return n;},beforeCount=geometryCount();frame(50);assert.equal(geometryCount(),beforeCount,'Animation reuses geometry');lastScene.traverse(o=>{assert(o.position.toArray().every(Number.isFinite));if(o.geometry)for(const key of ['position','normal'])if(o.geometry.attributes[key])assert(Array.from(o.geometry.attributes[key].array).every(Number.isFinite),key+' stays finite');});
console.log('OK: cover heroes have animal muzzles, articulated armour and batched karts; capes, banners, birds and air particles animate, pause and resume without geometry growth.');
