const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const read=p=>fs.readFileSync(path.join(__dirname,p),'utf8');
const C=require('./race-core.js'),three=require('./vendor/three.min.js');
const trackContext={THREE:three,RaceCore:C};vm.createContext(trackContext);vm.runInContext(read('track.js'),trackContext);const track=trackContext.RaceTrack;
const gas={throttle:true,brake:false,steer:0,drift:false},dt=1/120;
function solo(){const s=C.createRace(track);for(const r of s.racers.slice(1)){r.x=10000+r.id*20;r.z=10000;r.finishTime=0;r.contact=10000;}s.pickups=[];return s;}
function place(s,r,d,speed=30,lane=0){const p=s.track.sample(d,lane);Object.assign(r,{x:p.x,y:p.y,z:p.z,yaw:Math.atan2(p.tx,p.tz),vx:p.tx*speed,vz:p.tz*speed,speed,d,lane,nearD:p.d,surface:p,lastSafeD:d,previousPose:null,grounded:true,phase:'driving',phaseTime:0,yawRate:0,steering:0,vy:0,jumpOrigin:null});}
function run(s,input,seconds){for(let i=0;i<seconds/dt;i++)C.step(s,typeof input==='function'?input(s):input,dt);}
assert(track.length>1800,'Longer course exceeds 1.8 km');
const elevations=track.segments.map(s=>s.a.y);assert(Math.max(...elevations)-Math.min(...elevations)>45,'Real elevation change exceeds 45 m');assert.equal(track.gaps.length,2);
for(const gap of track.gaps){assert(!track.sample((gap.start+gap.end)/2).ground);assert(track.sample(gap.start-1).slope>.15,'Raised approach ramp');assert(track.sample(gap.end+1).ground);}
// On a bend, releasing the wheel must preserve the world heading and straight trajectory.
const straight=solo(),p=straight.racers[0];place(straight,p,440,26);const before={x:p.x,z:p.z,yaw:p.yaw};run(straight,gas,.65);assert.equal(p.phase,'driving');assert(Math.abs(C.angle(p.yaw-before.yaw))<1e-10,'No automatic steering on curves');assert(Math.abs((p.x-before.x)*Math.cos(before.yaw)-(p.z-before.z)*Math.sin(before.yaw))<1e-8,'No rail-following motion');
const right=solo(),left=solo();place(right,right.racers[0],20,32);place(left,left.racers[0],20,32);const yaw=right.racers[0].yaw;run(right,{...gas,steer:1},.4);run(left,{...gas,steer:-1},.4);assert(C.angle(right.racers[0].yaw-yaw)<-.3,'Right steering turns decisively');assert(C.angle(left.racers[0].yaw-yaw)>.3,'Left steering turns decisively');assert(right.racers[0].lane>1&&left.racers[0].lane< -1);
const sliding=solo(),gripping=solo();place(sliding,sliding.racers[0],15,32);place(gripping,gripping.racers[0],15,32);run(sliding,{...gas,steer:.65,drift:true},.7);run(gripping,{...gas,steer:.65},.7);assert(Math.abs(sliding.racers[0].slip)>Math.abs(gripping.racers[0].slip)*2,'Drift preserves lateral momentum');assert(Math.abs(sliding.racers[0].slip)>.25,'Body and travel direction differ during drift');
const charged=solo();charged.track={...track,width:1000};place(charged,charged.racers[0],300,35);run(charged,{...gas,steer:.55,drift:true},1.4);assert(charged.racers[0].drift>.55,'Real slip charges boost');C.step(charged,gas,dt);assert(charged.racers[0].boost>0,'Drift release grants turbo');
const fakeDrift=solo();place(fakeDrift,fakeDrift.racers[0],20,30);run(fakeDrift,{...gas,drift:true},.5);assert.equal(fakeDrift.racers[0].drift,0,'Holding drift on a straight grants nothing');
const off=solo(),op=off.racers[0],exitD=420;place(off,op,exitD,22,11.15);op.yaw-=Math.PI/2;op.vx=Math.sin(op.yaw)*22;op.vz=Math.cos(op.yaw)*22;C.step(off,gas,dt);assert.equal(op.phase,'falling','Kart leaves the edge without an invisible wall');const anchor=op.respawnD;while(op.phase==='falling')C.step(off,gas,dt);assert.equal(op.phase,'respawning');assert(Math.abs(op.lane)<1e-8);assert.equal(op.d,anchor);assert.equal(op.speed,2);while(op.phase==='respawning')C.step(off,gas,dt);assert.equal(op.phase,'driving');assert(op.grounded&&op.shield>0,'Respawn includes recovery animation and temporary protection');
let completedJumps=0;
for(const gap of track.gaps){const jump=solo(),jp=jump.racers[0];place(jump,jp,gap.start-.4,46);let airborne=false,landed=false,maxY=jp.y;for(let i=0;i<350;i++){C.step(jump,gas,dt);maxY=Math.max(maxY,jp.y);if(!jp.grounded)airborne=true;if(airborne&&jp.grounded){landed=true;break;}}assert(airborne&&landed,'Each drawbridge can be cleared with speed');assert.equal(jp.falls,0);assert(maxY>track.sample(gap.start).y+1,'A jump has vertical flight');completedJumps++;}
const short=solo(),sp=short.racers[0];place(short,sp,track.gaps[0].start-.3,10);let failed=false;for(let i=0;i<250;i++){C.step(short,{...gas,throttle:false},dt);if(sp.phase==='falling'){failed=true;break;}}assert(failed,'Insufficient speed falls into the gap');assert(sp.respawnD<track.gaps[0].start-40,'Failed jump returns to a usable run-up');
const thrown=solo(),tp=thrown.racers[0],victim=thrown.racers[1];place(thrown,tp,10,30);victim.x=tp.x+Math.sin(tp.yaw)*23;victim.z=tp.z+Math.cos(tp.yaw)*23;victim.y=tp.y;victim.vx=20;victim.speed=20;tp.item='coconut';assert(C.useItem(thrown));assert.equal(tp.item,null);assert(!C.useItem(thrown));const bulletX=thrown.projectiles[0].x;run(thrown,gas,.05);assert.notEqual(thrown.projectiles[0].x,bulletX,'Thrown item travels through world space');run(thrown,gas,.5);assert(victim.stun>1,'Coconut collision slows an opponent');
const blast=solo(),bp=blast.racers[1],shielded=blast.racers[2];place(blast,bp,20,20);place(blast,shielded,20,20,3);bp.finishTime=shielded.finishTime=0;shielded.shield=7;blast.projectiles.push({id:1,owner:0,type:'bomb',x:bp.x,y:bp.y+.3,z:bp.z,vx:0,vz:0,vy:-1,age:.5,life:4,nearD:20});C.step(blast,gas,dt);assert(bp.stun>2,'Bomb explosion slows nearby racer');assert.equal(shielded.stun,0,'Shield blocks an explosion');assert(blast.effects.length>0,'Hits produce visible effects');
const pickup=C.createRace(track);place(pickup,pickup.racers[0],pickup.pickups[0].d-.2,20);C.step(pickup,gas,dt);assert(pickup.racers[0].item,'Actual pickup grants a carriable item');
const finish=C.createRace(track);let jumps=0;for(let i=0;i<35000&&!finish.finished;i++){C.step(finish,C.botInput(finish,finish.racers[0]),dt);if(finish.events.includes('ЧИСТОЕ ПРИЗЕМЛЕНИЕ!'))jumps++;finish.events=[];}assert(finish.finished,'Physical course is completable for three laps');assert.equal(finish.lapTimes.length,3);assert(jumps>=6,'Three laps include both jumps');assert(finish.rank>=1&&finish.rank<=6);const time=finish.time;C.step(finish,gas,dt);assert.equal(finish.time,time);
assert.equal(C.formatTime(61.259),'01:01.25');
console.log(`OK: world-space steering, no assistance, lateral drift, turbo, ${completedJumps} gaps, failed jump, recovery, projectiles, shields, pickups, full 3-lap course (${finish.time.toFixed(1)} s with a test driver).`);

// Progress belongs to each hero. Upgrades change actual acceleration/braking, not just labels.
const profile=C.newProfile();assert.equal(profile.heroes.length,8);assert.equal(C.skillPoints(profile.heroes[0]),3);assert(C.upgrade(profile,0,'speed'));assert.equal(profile.heroes[1].upgrades.speed,0);assert(C.upgrade(profile,0,'aero'));assert(C.upgrade(profile,0,'braking'));assert(!C.upgrade(profile,0,'handling'),'Cannot overspend');assert(!C.upgrade(profile,0,'__proto__'));assert.deepEqual(C.parseProfile(JSON.stringify(profile)),profile);assert.throws(()=>C.parseProfile('{broken'));assert.throws(()=>C.parseProfile(JSON.stringify({version:99,heroes:[]})));const bad=C.newProfile();bad.heroes[0].upgrades.speed=5;assert.throws(()=>C.parseProfile(JSON.stringify(bad)),'Reject overspent save');
const baseStats=C.stats(0),maxStats=C.stats(0,Object.fromEntries(C.STAT_KEYS.map(k=>[k,5])));for(const k of C.STAT_KEYS)assert(maxStats[k]>baseStats[k],k+' grows');assert(C.stats(0,{aero:5}).handling>baseStats.handling&&C.stats(0,{aero:5}).acceleration>baseStats.acceleration,'Aerodynamics affects control and acceleration');
function physicsTrial(levels,input,speed){const s=solo();s.racers[0].cfg=C.stats(0,levels);place(s,s.racers[0],15,speed);run(s,input,.4);return s.racers[0];}
assert(physicsTrial({acceleration:5},gas,0).speed>physicsTrial({},gas,0).speed,'Upgrade reaches drive physics');assert(physicsTrial({braking:5},{...gas,throttle:false,brake:true},30).speed<physicsTrial({},{...gas,throttle:false,brake:true},30).speed,'Better brakes reduce speed sooner');
const rewardProfile=C.newProfile();finish.rewardClaimed=false;const reward=C.awardRace(rewardProfile,finish);assert(reward.xp>0&&rewardProfile.heroes[0].xp===reward.xp);assert(C.skillPoints(rewardProfile.heroes[0])>3);assert.equal(C.awardRace(rewardProfile,finish),null,'No duplicate finish rewards');const ravenReward=C.awardRace(C.newProfile(),{...finish,driver:3,rewardClaimed:false});assert(ravenReward.xp>reward.xp,'Raven earns extra experience');assert(C.stats(1).armor===.65&&C.stats(0).driftGain===1.3&&C.stats(2).landingBoost===1.2&&C.stats(4).boost===1.3,'Each hero has a distinct implemented passive');
// The aim rule selects only live opponents in front. One random roll is made per throw.
const aimed=C.createRace(track),ap=aimed.racers[0];place(aimed,ap,10,0);for(const e of aimed.racers.slice(1)){e.x=9000+e.id*5;e.z=9000;}const target=aimed.racers[1];target.x=ap.x+Math.sin(ap.yaw)*30;target.z=ap.z+Math.cos(ap.yaw)*30;target.y=ap.y;ap.item='coconut';assert.equal(C.aimTarget(aimed).id,1);target.x=ap.x-Math.sin(ap.yaw)*30;target.z=ap.z-Math.cos(ap.yaw)*30;assert.equal(C.aimTarget(aimed),null,'No lock behind the car');target.x=ap.x+Math.sin(ap.yaw)*30;target.z=ap.z+Math.cos(ap.yaw)*30;
let guided=0;for(let i=0;i<10000;i++){ap.item=i%2?'bomb':'coconut';aimed.projectiles=[];C.useItem(aimed);if(aimed.projectiles[0].targetId===1)guided++;else assert.equal(aimed.projectiles[0].missTargetId,1);}assert(Math.abs(guided/10000-.7)<.015,'Guidance probability is 70%');
function outcome(seed){const s=C.createRace(track);place(s,s.racers[0],15,0);for(const e of s.racers.slice(1)){e.x=9000+e.id*5;e.z=9000;e.finishTime=0;}const r=s.racers[1];place(s,r,45,0);r.finishTime=null;r.stun=10;s.racers[0].item='coconut';s.rng=seed;C.useItem(s);const guided=s.projectiles[0].targetId===1;run(s,{...gas,throttle:false},.9);return {guided,hit:s.metrics.hits>0};}
assert.deepEqual(outcome(1),{guided:true,hit:true},'Guided projectile physically reaches target');assert.deepEqual(outcome(1500),{guided:false,hit:false},'Miss roll does not hit locked target');
for(const course of trackContext.RaceTracks.slice(1)){const s=C.createRace(course,4);for(let i=0;i<42000&&!s.finished;i++){C.step(s,C.botInput(s,s.racers[0]),dt);s.events=[];}assert(s.finished,course.name+' is completable');assert(s.metrics.jumps>=6);assert.notEqual(course.segments[500].a.x,track.segments[500].a.x,'Distinct course geometry');}
console.log(`OK: eight heroes, individual RPG saves/points/caps, upgrade physics, rewards, passives, five complete courses, front-only lock, guided hit/miss; ${guided}/10000 guided throws.`);

// Execute real scene/UI with GPU and DOM replaced; this is not a visual/FPS check.
const html=read('index.html'),nodes=new Map(),events={};
function element(id='',classes=''){const set=new Set(classes.split(' '));return {id,style:{},dataset:{},textContent:'',innerHTML:'',listeners:{},classList:{add:x=>set.add(x),remove:x=>set.delete(x),contains:x=>set.has(x),toggle(x,on){const yes=on===undefined?!set.has(x):on;yes?set.add(x):set.delete(x);return yes;}},addEventListener(type,fn){this.listeners[type]=fn;},setAttribute(){},focus(){context.document.activeElement=this;},blur(){},querySelector(){return element();},getContext(){return new Proxy({},{get:(_,k)=>k==='createRadialGradient'?()=>({addColorStop(){}}):()=>{}});}};}
for(const tag of html.matchAll(/<[^>]*\bid="([^"]+)"[^>]*>/g))nodes.set(tag[1],element(tag[1],tag[0].match(/class="([^"]+)"/)?.[1]||''));
const drivers=Array.from({length:8},(_,i)=>Object.assign(element(),{dataset:{driver:String(i)}})),buttons=['KeyA','KeyD','Space','KeyC','KeyS','KeyW'].map(key=>Object.assign(element(),{dataset:{key}}));
const courseButtons=Array.from({length:5},(_,i)=>Object.assign(element(),{dataset:{track:String(i)}})),upgradeButtons=C.STAT_KEYS.map(k=>Object.assign(element(),{dataset:{upgrade:k}})),skinButtons=C.SKINS.map((_,i)=>Object.assign(element(),{dataset:{skin:String(i)}})),saved=new Map();
let frames=0,lastScene;
class Renderer{constructor(){this.shadowMap={};}setPixelRatio(){}setSize(){}render(scene,camera){frames++;scene.updateMatrixWorld();camera.updateMatrixWorld();if(scene.name!=='garage')lastScene=scene;}}
const context={console,devicePixelRatio:1,THREE:{...three,WebGLRenderer:Renderer},innerWidth:1440,innerHeight:900,performance:{now:()=>0},matchMedia:()=>({matches:false}),requestAnimationFrame:fn=>{context.frame=fn;},localStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)},document:{getElementById(id){assert(nodes.has(id),`Element ${id} exists`);return nodes.get(id);},querySelector:()=>element(),querySelectorAll:q=>q==='[data-driver]'?drivers:q==='[data-key]'?buttons:q==='[data-track]'?courseButtons:q==='[data-upgrade]'?upgradeButtons:q==='[data-skin]'?skinButtons:[],createElement:()=>element(),body:element(),documentElement:element(),addEventListener(type,fn){events['document:'+type]=fn;}}};context.window=context;context.addEventListener=(type,fn)=>{events[type]=fn;};vm.createContext(context);vm.runInContext(read('race-core.js'),context);vm.runInContext(read('track.js'),context);
const gameSource=read('game.js'),end=gameSource.lastIndexOf('})();');vm.runInContext(gameSource.slice(0,end)+'globalThis.probe={get mode(){return mode;},get state(){return state;},set state(s){state=s;},get selected(){return selected;},get models(){return models;},get profile(){return profile;},get track(){return track;},get smoke(){return smoke;},get skidCount(){return skidCount;},sample,camera,projectileViews,placeKarts,updateAtmosphere,updateHUD,updateCamera,softBox,sculptedShell,kart,disposeGroup,clearOfRoad,waveCloth,renderPose,set renderAlpha(a){simulationDebt=a/120;},get garageModel(){return garageModel;},get garageScene(){return garageScene;},get cameraTarget(){return cameraTarget;}};\n'+gameSource.slice(end),context);
let now=0;function frame(n=1){for(let i=0;i<n;i++){now+=1000/60;context.frame(now);}}function click(id){nodes.get(id).listeners.click();}function key(code,down=true){events[down?'keydown':'keyup']({code,preventDefault(){},repeat:false});}
frame();assert(frames>0);lastScene.traverse(child=>{assert(child.position.toArray().every(Number.isFinite));if(child.geometry?.attributes.position)assert(Array.from(child.geometry.attributes.position.array).every(Number.isFinite));});
const roadMeshes=[];lastScene.traverse(m=>{if(m.name==='track-strip')roadMeshes.push(m);});
for(const gap of track.gaps){const middle=track.sample((gap.start+gap.end)/2),ray=new three.Raycaster(new three.Vector3(middle.x,middle.y+80,middle.z),new three.Vector3(0,-1,0));assert.equal(ray.intersectObjects(roadMeshes).length,0,'Visible bridge opening has no road geometry');}
drivers[2].listeners.click();assert.equal(context.probe.selected,2);click('openForge');nodes.get('forge').listeners.keydown({code:'Tab',shiftKey:true,preventDefault(){}});assert.equal(context.document.activeElement,nodes.get('forgeDone'));nodes.get('forge').listeners.keydown({code:'Tab',shiftKey:false,preventDefault(){}});assert.equal(context.document.activeElement,nodes.get('closeForge'));upgradeButtons[0].listeners.click();assert.equal(context.probe.profile.heroes[2].upgrades.speed,1);assert.equal(context.probe.profile.heroes[0].upgrades.speed,0);assert.equal(C.parseProfile(saved.get('wild-drift-ashen-profile-v1')).heroes[2].upgrades.speed,1);click('forgeDone');courseButtons[1].listeners.click();click('start');assert.equal(context.probe.track.id,'thorn');assert(context.probe.state.racers[0].cfg.speed>C.DRIVERS[2].speed);assert.equal(context.probe.mode,'countdown');frame(220);assert.equal(context.probe.mode,'race');key('KeyW');frame(90);assert(Number(nodes.get('speed').textContent)>0);const player=context.probe.state.racers[0];player.item='coconut';frame();assert(context.probe.models[0].items.coconut.visible,'Picked-up item appears in the character hand');assert(!context.probe.models[0].items.bomb.visible);key('ShiftLeft');frame();assert(!context.probe.models[0].items.coconut.visible,'Throw removes the item from the hand');assert(context.probe.projectileViews.some(v=>v.g.visible),'Thrown item renders in the world');
const pausedTime=context.probe.state.time;key('Escape');frame(60);assert.equal(context.probe.state.time,pausedTime);key('Escape');key('KeyW');frame(10);assert(context.probe.state.time>pausedTime);events.blur();assert.equal(context.probe.mode,'paused');click('resume');key('KeyR');frame();assert.equal(context.probe.state.racers[0].phase,'falling');frame(51);assert.equal(context.probe.state.racers[0].phase,'respawning');assert(context.probe.models[0].respawnRing.visible,'Respawn effect is displayed');
finish.rewardClaimed=false;context.probe.state=finish;frame();assert.equal(context.probe.mode,'finish');assert(!nodes.get('finish').classList.contains('hidden'));assert(nodes.get('finishTime').textContent.length>0);click('again');assert.equal(context.probe.state.time,0);click('pauseButton');click('back');assert.equal(context.probe.mode,'menu');
for(const m of html.matchAll(/(?:src|href)="([^"#]+)"/g)){assert(!/^https?:/.test(m[1]));assert(fs.existsSync(path.join(__dirname,m[1].split('?')[0])));}
console.log('OK: scene geometry, real bridge openings, hand items, projectile rendering, HUD, pause, recovery animation, results, replay, offline assets. GPU output and FPS are not tested.');

assert(saved.has('wild-drift-ashen-profile-v1'));assert(nodes.get('reward').textContent.includes('опыта'));courseButtons[2].listeners.click();drivers[4].listeners.click();click('start');assert.equal(context.probe.track.id,'frost');assert.equal(context.probe.models[0].g.name,'hero-4');assert.equal(lastScene.children.filter(c=>c.name==='course').length,1,'World switching removes old geometry');console.log('OK: forge buttons save individual upgrades, course selection swaps the world, all eight hero models build, finish grants XP.');

// Rendered effects follow live race state; no GPU/image-quality assertion is made here.
const renderState=context.probe.state,rp=renderState.racers[0];place(renderState,rp,15,32);rp.drifting=true;rp.slip=.4;context.probe.placeKarts(1);rp.x+=Math.sin(rp.yaw)*.5;rp.z+=Math.cos(rp.yaw)*.5;context.probe.placeKarts(1);context.probe.updateAtmosphere(.1);assert(context.probe.skidCount>0,'Drift lays real road geometry');assert(context.probe.smoke.some(p=>p.life>0&&p.sprite.visible&&p.sprite.material.opacity>0),'Drift emits visible smoke');
for(const e of renderState.racers.slice(1)){e.x=9000+e.id*5;e.z=9000;}const lock=renderState.racers[1];lock.x=rp.x+Math.sin(rp.yaw)*25;lock.z=rp.z+Math.cos(rp.yaw)*25;lock.y=rp.y;rp.item='bomb';context.probe.camera.position.set(rp.x-Math.sin(rp.yaw)*12,rp.y+6,rp.z-Math.cos(rp.yaw)*12);context.probe.camera.lookAt(lock.x,lock.y+2,lock.z);context.probe.updateHUD();assert(!nodes.get('reticle').classList.contains('hidden'),'Held throwable shows a reticle on a target ahead');rp.item=null;context.probe.updateHUD();assert(nodes.get('reticle').classList.contains('hidden'),'Reticle clears when no throwable is held');
const runeBoost=C.createRace(track,4);place(runeBoost,runeBoost.racers[0],track.pads[0],20);C.step(runeBoost,gas,dt);assert(Math.abs(runeBoost.racers[0].boost-1.6*1.3)<1e-8,'Wolf passive also extends rune pad boosts');
console.log('OK: keyboard focus stays in the forge, drift smoke and road trails render, held items drive the target reticle, rune pads apply the wolf passive.');

// Cover-inspired geometry and ambient animation must survive real scene transitions.
const visualHero=context.probe.models[0];let heroDraws=0;visualHero.g.traverse(o=>{if(o.isMesh)heroDraws++;});assert(heroDraws<95,'Ornamental details are batched instead of separate draw calls');
for(const type of [0,3,4]){const found=context.probe.models.find(m=>m.g.name==='hero-'+type),k=found||context.probe.kart(type);assert(k&&k.head&&k.cape&&k.arms.length===2,'Cover heroes have a sculpted head, cape and articulated arms');const bounds=new three.Box3().setFromObject(k.head);assert(bounds.getSize(new three.Vector3()).z>.7,'Animal muzzle has depth');if(!found)context.probe.disposeGroup(k.g);}
const banner=lastScene.getObjectByName('wind-banner'),bird=lastScene.getObjectByName('raven'),weather=lastScene.getObjectByName('airborne-particles');assert(banner&&bird&&weather&&lastScene.getObjectByName('gothic-city'));
const capeBefore=Array.from(visualHero.cape.geometry.attributes.position.array),flagBefore=Array.from(banner.geometry.attributes.position.array),birdBefore=bird.position.clone(),weatherBefore=Array.from(weather.geometry.attributes.position.array);frame(50);
assert.notDeepEqual(Array.from(visualHero.cape.geometry.attributes.position.array),capeBefore,'Cape moves in wind');assert.notDeepEqual(Array.from(banner.geometry.attributes.position.array),flagBefore,'Banners ripple');assert(bird.position.distanceTo(birdBefore)>0,'Birds circle the cathedral');assert.notDeepEqual(Array.from(weather.geometry.attributes.position.array),weatherBefore,'Air particles move');
click('pauseButton');const still=Array.from(banner.geometry.attributes.position.array),birdStill=bird.position.clone();frame(90);assert.deepEqual(Array.from(banner.geometry.attributes.position.array),still,'Pause freezes cloth');assert.equal(bird.position.distanceTo(birdStill),0,'Pause freezes world motion');click('resume');frame(10);assert.notDeepEqual(Array.from(banner.geometry.attributes.position.array),still,'World resumes after pause');
const geometryCount=()=>{let n=0;lastScene.traverse(o=>{if(o.geometry)n++;});return n;},beforeCount=geometryCount();frame(50);assert.equal(geometryCount(),beforeCount,'Animation reuses geometry');lastScene.traverse(o=>{assert(o.position.toArray().every(Number.isFinite));if(o.geometry)for(const key of ['position','normal'])if(o.geometry.attributes[key])assert(Array.from(o.geometry.attributes[key].array).every(Number.isFinite),key+' stays finite');});
console.log('OK: cover heroes have animal muzzles, articulated armour and batched karts; capes, banners, birds and air particles animate, pause and resume without geometry growth.');

// Real barriers slow collisions without steering; unfenced exits and jumps retain their rules.
for(const course of trackContext.RaceTracks){assert(course.fences.length>=5);for(const f of course.fences){assert(!course.bridgeAt(f.start)&&!course.bridgeAt(f.end));assert(course.fenceAt((f.start+f.end)/2,f.side));}
 for(const side of [-1,1]){const fence=course.fences.find(f=>f.side===side),s=C.createRace(course),r=s.racers[0];for(const e of s.racers.slice(1)){e.x=e.z=9000;e.finishTime=0;}place(s,r,(fence.start+fence.end)/2,60,side*8.9);const n={x:-r.surface.tz*side,z:r.surface.tx*side};r.yaw=Math.atan2(n.x,n.z);r.vx=n.x*60;r.vz=n.z*60;const yaw=r.yaw;C.step(s,{...gas,throttle:false},.05);assert.equal(r.phase,'driving','Barrier prevents an exit');assert(Math.abs(r.lane)<=course.fenceLane-1.3+.01);assert(r.speed<30,'Impact cuts speed');assert(r.vx*n.x+r.vz*n.z<=0,'Impact removes outward velocity');assert(Math.abs(C.angle(r.yaw-yaw))<1e-10,'Barrier never auto-steers');assert(s.events.some(e=>e.includes('ОГРАЖДЕНИЕ')));}
}
// Check actual world placement through the chase-camera projection, not just existence.
for(let i=0;i<5;i++){click('pauseButton');click('back');courseButtons[i].listeners.click();click('start');frame(4);const t=context.probe.track,camera=context.probe.camera;camera.updateMatrixWorld();const projected=o=>o.clone().project(camera),inFrame=p=>p.z>0&&p.z<1&&Math.abs(p.x)<.94&&Math.abs(p.y)<.94;
 const fog=[],fires=[],fences=[];lastScene.traverse(o=>{if(o.name==='road-mist')fog.push(o);if(o.name==='torch-flame')fires.push(o);if(o.name==='track-fence')fences.push(o);});assert.equal(fences.length,t.fences.length,'Rendered barriers use the physics sections');assert(fog.some(o=>{const pos=o.getWorldPosition(new three.Vector3()),road=t.nearest(pos.x,pos.z);return inFrame(projected(pos))&&pos.y>=road.y&&pos.distanceTo(camera.position)<65&&o.material.opacity>.3;}),'Fog is above the road and inside the chase view');assert(fires.some(o=>{const flame=o.children[0],pos=flame.getWorldPosition(new three.Vector3());return inFrame(projected(pos))&&pos.distanceTo(camera.position)<65&&flame.scale.y>2.5&&flame.material.map&&flame.material.toneMapped===false;}),'Large bright flames face the driving camera');
 if(i===2){const snow=lastScene.getObjectByName('airborne-particles'),a=snow.geometry.attributes.position;let visible=0;for(let j=0;j<a.count;j++){const p=new three.Vector3(a.getX(j),a.getY(j),a.getZ(j));if(inFrame(projected(p))&&p.y>t.nearest(p.x,p.z).y+.2&&p.distanceTo(camera.position)<35)visible++;}assert(snow.material.map&&snow.material.size>=.3);assert(visible>20,'Snow occupies the foreground, not a sparse distant volume');console.log('Foreground snowflakes at race start:',visible);}
}
const geometryGroup=new three.Group(),tiny=context.probe.softBox(.044,.06,.14,0x333333,0,0,0,geometryGroup),bounds=new three.Box3().setFromObject(tiny),dimensions=bounds.getSize(new three.Vector3());assert(Math.abs(dimensions.x-.044)<.002&&Math.abs(dimensions.z-.14)<.002,'Bevels stay inside small parts');const smooth=context.probe.sculptedShell([[.1,.5,0],[.7,.8,1],[.03,.5,2]],new three.MeshStandardMaterial(),geometryGroup);assert(smooth.geometry.index,'Smooth shell shares vertices between faces');const normal=smooth.geometry.attributes.normal;for(let i=0;i<normal.count;i++)assert(Math.abs(Math.hypot(normal.getX(i),normal.getY(i),normal.getZ(i))-1)<.001,'Smooth normals are normalized');
for(const match of html.matchAll(/(?:src|href)="([^"?]+)\?v=([^" ]+)"/g)){const hash=require('node:crypto').createHash('sha256').update(read(match[1])).digest('hex').slice(0,10);assert.equal(match[2],hash,'Asset URL matches current content');}
console.log('OK: physical partial fences, road-level fog and bright flames in the chase view, visible foreground snow, bounded bevels, smooth indexed bodywork and fresh asset URLs.');

// Existing five-hero saves migrate without losing XP, upgrades or old course records.
const legacy={version:1,heroes:C.newProfile().heroes.slice(0,5).map(h=>({xp:h.xp,upgrades:h.upgrades})),records:{ash:154.2,frost:160}};legacy.heroes[2].xp=450;legacy.heroes[2].upgrades.handling=4;
const migrated=C.parseProfile(JSON.stringify(legacy));assert.equal(migrated.heroes.length,8);assert.equal(migrated.heroes[2].xp,450);assert.equal(migrated.heroes[2].upgrades.handling,4);assert.equal(migrated.legacyRecords.ash,154.2);assert.equal(migrated.records['ash-v2'],undefined,'Old times do not compete on regenerated routes');assert.deepEqual(C.parseProfile(JSON.stringify(migrated)),migrated);
const wallet=C.newProfile();assert(C.chooseSkin(wallet,0,1));assert.equal(wallet.points,40);assert.equal(wallet.heroes[0].skin,1);assert.equal(wallet.heroes[1].skin,0);assert(C.chooseSkin(wallet,0,1));assert.equal(wallet.points,40,'Owned skin cannot charge twice');assert(!C.chooseSkin(wallet,1,1));assert(!C.chooseSkin(wallet,0,99));assert(!C.chooseSkin(wallet,'__proto__',1));assert(C.chooseSkin(wallet,0,0));assert.equal(wallet.points,40);assert.deepEqual(C.parseProfile(JSON.stringify(wallet)),wallet);
for(const mutate of [p=>p.points=-1,p=>p.points=.5,p=>p.heroes[0].skins=[0,9],p=>p.heroes[0].skin=2,p=>p.heroes[0].skins=[0,0]]){const bad=C.newProfile();mutate(bad);assert.throws(()=>C.parseProfile(JSON.stringify(bad)));}
assert(reward.points>0&&rewardProfile.points===220+reward.points,'Finish earns spendable race points exactly once');
// New traits affect the actual drive/item/collision paths.
const shieldRace=C.createRace(track,7);shieldRace.racers[0].item='shield';C.useItem(shieldRace);assert.equal(shieldRace.racers[0].shield,9.8);
function shoulderSpeed(hero){const s=C.createRace(C.makeTrack([{x:0,y:0,z:0},{x:300,y:0,z:0},{x:300,y:0,z:300},{x:0,y:0,z:300}]),hero);for(const e of s.racers.slice(1))e.finishTime=0;place(s,s.racers[0],5,40,9.3);run(s,gas,.9);return s.racers[0].speed;}assert(shoulderSpeed(5)>shoulderSpeed(0)+4,'Deer keeps more speed on the shoulder');
function bumpSpeed(hero){const s=C.createRace(track,hero);for(const e of s.racers.slice(1))e.finishTime=0;place(s,s.racers[0],10,30);place(s,s.racers[1],10,30,1.5);C.step(s,gas,dt);return Math.hypot(s.racers[0].vx,s.racers[0].vz);}assert(bumpSpeed(6)>bumpSpeed(0)+2,'Bear collision passive preserves momentum');

// A hold/release changes only the viewing direction and clears on blur.
click('pauseButton');click('back');drivers[7].listeners.click();click('openForge');assert(context.probe.garageModel,'Workshop builds a live 3D preview');assert.equal(context.probe.garageScene.children.filter(o=>o.name.startsWith('hero-')).length,1);
skinButtons[1].listeners.click();assert.equal(context.probe.garageModel.g.userData.skin,1);assert.equal(context.probe.garageScene.children.filter(o=>o.name.startsWith('hero-')).length,1,'Preview replacement disposes the old car');click('buySkin');assert.equal(context.probe.profile.heroes[7].skin,1);assert(C.parseProfile(saved.get('wild-drift-ashen-profile-v1')).heroes[7].skins.includes(1));assert.equal(context.probe.models[0].g.userData.skin,1);click('forgeDone');courseButtons[0].listeners.click();click('start');frame(220);
const rearPlayer=context.probe.state.racers[0];place(context.probe.state,rearPlayer,20,0);context.probe.updateCamera(1,true);const rearYaw=rearPlayer.yaw,forwardDot=()=>((context.probe.camera.position.x-rearPlayer.x)*Math.sin(rearYaw)+(context.probe.camera.position.z-rearPlayer.z)*Math.cos(rearYaw));assert(forwardDot()<0);key('KeyC');context.probe.updateCamera(dt);context.probe.updateHUD();assert(forwardDot()>0);assert.equal(rearPlayer.yaw,rearYaw);assert(!nodes.get('rearView').classList.contains('hidden'));key('KeyC',false);context.probe.updateCamera(dt);assert(forwardDot()<0);key('KeyC');events.blur();click('resume');context.probe.updateCamera(dt);assert(forwardDot()<0,'Blur releases rear view');

// Distinct coachwork geometry for all eight heroes and all three purchased variants.
const bodyHashes=new Set();for(let hero=0;hero<8;hero++){const shapes=[];for(let skin=0;skin<3;skin++){
 const k=context.probe.kart(hero,skin),hash=require('node:crypto').createHash('sha256');let count=0;k.frame.traverse(o=>{if(o.geometry){hash.update(Buffer.from(o.geometry.attributes.position.array.buffer));count+=o.geometry.attributes.position.count;}});shapes.push(hash.digest('hex'));assert(count>15000,'Detailed chassis contains sculpted surfaces and ornaments');assert.equal(k.ws.length,skin===2||hero===6?6:4);if(skin===0)bodyHashes.add(shapes[0]);
 for(const time of [0,1.7,3.1,4.7]){context.probe.waveCloth(k.cape,time,3);k.tail.rotation.y=Math.sin(time)*.09;k.g.updateMatrixWorld(true);const tailBox=new three.Box3().setFromObject(k.tail),geo=k.cape.geometry,p=geo.attributes.position,indices=geo.index;if(tailBox.isEmpty())continue;for(let i=0;i<indices.count;i+=3){const vertices=[0,1,2].map(j=>new three.Vector3().fromBufferAttribute(p,indices.getX(i+j)).applyMatrix4(k.cape.matrixWorld));assert(!tailBox.intersectsTriangle(new three.Triangle(...vertices)),'Tail clears the split cape in wind: hero '+hero+' at '+time+' bounds '+JSON.stringify(tailBox)+' triangle '+JSON.stringify(vertices));}}
 let draws=0;k.g.traverse(o=>{if(o.isMesh)draws++;});assert(draws<110,'Shared details stay batched');context.probe.disposeGroup(k.g);
 }assert.equal(new Set(shapes).size,3,'Every skin changes geometry for hero '+hero);
}assert.equal(bodyHashes.size,8,'Every hero has its own actual coachwork');

// Elevation-aware nearest queries keep both decks separate; bank geometry and physics agree.
for(const course of trackContext.RaceTracks){assert(course.banks.length>2);for(const crossing of course.overpasses){const low=course.sample(crossing.lower),high=course.sample(crossing.upper);assert(Math.hypot(low.x-high.x,low.z-high.z)<1&&high.y-low.y>12,'Bridge passes directly above another road');assert(Math.abs(course.nearest(low.x,low.z,undefined,low.y).y-low.y)<.01);assert(Math.abs(course.nearest(high.x,high.z,crossing.upper).y-high.y)<.01);for(const d of [crossing.lower,crossing.upper]){const s=C.createRace(course),r=s.racers[0];place(s,r,d-25,30);for(const e of s.racers.slice(1))e.finishTime=0;run(s,st=>C.botInput(st,r),1.8);assert.equal(r.falls,0);assert(Math.abs(r.d-(d-25))<85,'Crossing does not teleport progress to the other deck');}}
 const bank=course.banks[0],d=(bank.start+bank.end)/2,center=course.sample(d),edge=course.sample(d,bank.side*9);assert(edge.y>center.y+1.5);assert(edge.crossSlope*bank.side>.3);const s=C.createRace(course),r=s.racers[0];for(const e of s.racers.slice(1))e.finishTime=0;place(s,r,d,0,bank.side*8);C.step(s,{throttle:false,steer:0},dt);assert((r.vx*-edge.tz+r.vz*edge.tx)*bank.side<0,'Raised edge applies inward gravity without turning the wheel');
}
console.log('OK: v1 save migration, wallet validation, atomic skin purchase/equip, all new passives, hold-to-look-back, 24 geometric car variants, animated tail/cape clearance and two separate bridge decks.');

// No decorative solid intersects the racing lanes, and both overpass surfaces are rendered.
for(let index=0;index<5;index++){
 click('pauseButton');click('back');courseButtons[index].listeners.click();click('start');frame(1);const t=context.probe.track,course=lastScene.getObjectByName('course'),obstacles=[],road=[];course.updateMatrixWorld(true);course.traverse(o=>{if(o.isMesh){if(o.name==='track-strip')road.push(o);else if(!o.material.transparent&&o.name!=='pickup')obstacles.push(o);}});
 assert(course.getObjectByName('statue-'+t.id),'Each world has themed statues');
 for(let d=3;d<t.length;d+=9)for(const lane of [-7,0,7]){const p=t.sample(d,lane);if(!p.ground)continue;const ray=new three.Raycaster(new three.Vector3(p.x,p.y+3.6,p.z),new three.Vector3(0,-1,0),0,3.4),hits=ray.intersectObjects(obstacles,false);assert(!hits.length,'No solid decor in lane '+lane+' at '+t.id+':'+Math.round(d)+' '+hits.map(h=>h.object.name||h.object.geometry.type).join(','));}
 for(const pass of t.overpasses)for(const d of [pass.lower,pass.upper]){const p=t.sample(d),hits=new three.Raycaster(new three.Vector3(p.x,p.y+2,p.z),new three.Vector3(0,-1,0),0,3).intersectObjects(road,false);assert(hits.length&&Math.abs(hits[0].point.y-p.y)<.1,'Bridge deck render matches physics');}
 const bank=t.banks[0],d=(bank.start+bank.end)/2,p=t.sample(d,bank.side*8),hits=new three.Raycaster(new three.Vector3(p.x,p.y+2,p.z),new three.Vector3(0,-1,0),0,3).intersectObjects(road,false);assert(hits.length&&Math.abs(hits[0].point.y-p.y)<.06,'Visible bank matches the physical surface');
}
// Quantized physics steps on a climb must not shake the projected car or the camera pitch.
click('pauseButton');click('back');courseButtons[2].listeners.click();click('start');frame(220);
const mountain=context.probe.track,climb=mountain.segments.find(seg=>seg.d>330&&seg.d<500&&(seg.b.y-seg.a.y)/seg.len>.15).d;
for(const fps of [30,60,144]){const r=context.probe.state.racers[0],ys=[],pitches=[];place(context.probe.state,r,climb,30);context.probe.updateCamera(1,true);for(let i=0;i<fps*2;i++){const physicalTime=Math.floor(i/fps*120)/120;place(context.probe.state,r,climb+physicalTime*30,30);const prior=mountain.sample(climb+Math.max(0,physicalTime-dt)*30);r.previousPose={x:prior.x,y:prior.y,z:prior.z,yaw:Math.atan2(prior.tx,prior.tz),phase:r.phase};context.probe.renderAlpha=(i/fps*120)%1;context.probe.updateCamera(1/fps);context.probe.camera.updateMatrixWorld();const pose=context.probe.renderPose(r),screen=new three.Vector3(pose.x,pose.y+1.4,pose.z).project(context.probe.camera),direction=new three.Vector3();context.probe.camera.getWorldDirection(direction);ys.push(screen.y);pitches.push(Math.asin(direction.y));}const jerk=values=>Math.max(...values.slice(2).map((v,i)=>Math.abs(v-2*values[i+1]+values[i])));assert(jerk(ys.slice(fps/2))<.003,'Stable climb projection at '+fps+' Hz');assert(jerk(pitches)<.003,'Stable camera pitch at '+fps+' Hz');}
click('pauseButton');click('back');courseButtons[0].listeners.click();click('start');const pass=context.probe.track.overpasses[0],bottom=context.probe.track.sample(pass.lower),cp=context.probe.state.racers[0];place(context.probe.state,cp,pass.lower,0);context.probe.updateCamera(1,true);assert(context.probe.camera.position.y<bottom.y+12,'Camera under bridge stays with the lower road');
console.log('OK: five themed statue sets, clear driving lanes, rendered raised edges and upper/lower bridge decks, smooth climbing camera at 30/60/144 Hz, camera clearance under bridges. GPU output/FPS remain untested.');
