/* Дикий дрифт — all assets and code run directly from disk. */
(function(){
'use strict';
const $=id=>document.getElementById(id),C=window.RaceCore;
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas:$('game'),antialias:true,powerPreference:'high-performance'});}catch(error){$('error').classList.remove('hidden');$('menu').classList.add('hidden');return;}
renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.75));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;
const scene=new THREE.Scene();scene.background=new THREE.Color(0xb6dee1);scene.fog=new THREE.Fog(0xc4e1df,220,950);
const camera=new THREE.PerspectiveCamera(57,innerWidth/innerHeight,.15,1200);
const hemi=new THREE.HemisphereLight(0xb6b1c9,0x333b42,1.65);scene.add(hemi);
const sun=new THREE.DirectionalLight(0xffe5c9,2.8);sun.position.set(-70,140,45);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-75,right:75,top:75,bottom:-75,near:1,far:320});sun.shadow.bias=-.0008;sun.shadow.normalBias=.08;scene.add(sun);scene.add(sun.target);
const mats={};function mat(color,extra={}){const key=String(color)+JSON.stringify(extra);return mats[key]||(mats[key]=new THREE.MeshStandardMaterial({color,roughness:.78,...extra}));}
function mesh(geo,color,x=0,y=0,z=0,parent=scene,shadow=false){const m=new THREE.Mesh(geo,typeof color==='number'?mat(color):color);m.position.set(x,y,z);m.castShadow=shadow;m.receiveShadow=true;parent.add(m);return m;}
const unitBox=new THREE.BoxGeometry(1,1,1),unitSphere=new THREE.SphereGeometry(1,12,9);
function box(w,h,d,color,x,y,z,parent=scene,shadow=false){const m=mesh(unitBox,color,x,y,z,parent,shadow);m.scale.set(w,h,d);return m;}
function ellipsoid(x,y,z,sx,sy,sz,color,parent=scene,shadow=false){const m=mesh(unitSphere,color,x,y,z,parent,shadow);m.scale.set(sx,sy,sz);return m;}
const roundedGeometries={};
function softBox(w,h,d,color,x,y,z,parent,shadow){const key=[w,h,d].join(',');if(!roundedGeometries[key]){const r=Math.min(.14,h/3),shape=new THREE.Shape();shape.moveTo(-w/2+r,-h/2);shape.lineTo(w/2-r,-h/2);shape.quadraticCurveTo(w/2,-h/2,w/2,-h/2+r);shape.lineTo(w/2,h/2-r);shape.quadraticCurveTo(w/2,h/2,w/2-r,h/2);shape.lineTo(-w/2+r,h/2);shape.quadraticCurveTo(-w/2,h/2,-w/2,h/2-r);shape.lineTo(-w/2,-h/2+r);shape.quadraticCurveTo(-w/2,-h/2,-w/2+r,-h/2);const geo=new THREE.ExtrudeGeometry(shape,{depth:d-.16,bevelEnabled:true,bevelThickness:.08,bevelSize:.06,bevelSegments:2,steps:1,curveSegments:4});geo.translate(0,0,-d/2+.08);roundedGeometries[key]=geo;}return mesh(roundedGeometries[key],color,x,y,z,parent,shadow);}
// A tiled height/roughness map gives the road stone joints and small surface pits.
const stoneCanvas=document.createElement('canvas');stoneCanvas.width=stoneCanvas.height=256;const stoneCtx=stoneCanvas.getContext('2d');stoneCtx.fillStyle='#555';stoneCtx.fillRect(0,0,256,256);for(let row=0;row<8;row++)for(let col=-1;col<5;col++){const shade=155+((row*37+col*71+256)%54);stoneCtx.fillStyle='rgb('+shade+','+shade+','+shade+')';stoneCtx.fillRect(col*64+(row%2)*32+2,row*32+2,60,28);}const stoneTexture=new THREE.CanvasTexture(stoneCanvas);stoneTexture.wrapS=stoneTexture.wrapT=THREE.RepeatWrapping;
let track=window.RaceTracks[0],length=track.length,distances=[],samples=[],N=0,world=null,reflection=null,pickupMeshes=[],torchAnchors=[];
const up=new THREE.Vector3(0,1,0);
function sample(d,lane=0){const s=track.sample(d,lane);return {p:new THREE.Vector3(s.x,s.y,s.z),t:new THREE.Vector3(s.tx,s.slope,s.tz).normalize(),right:new THREE.Vector3(-s.tz,0,s.tx),...s};}
function label(text,bg,fg,w=512,h=128){const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.fillStyle=fg;ctx.font=`600 ${h*.48}px Georgia`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,w/2,h*.53);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide});}
function disposeGroup(group){if(!group)return;const shared=new Set([unitBox,unitSphere,...Object.values(roundedGeometries)]),cached=new Set(Object.values(mats));group.traverse(o=>{if(o.geometry&&!shared.has(o.geometry))o.geometry.dispose();for(const m of o.material?(Array.isArray(o.material)?o.material:[o.material]):[]){if(!cached.has(m)){m.map?.dispose();m.dispose();}}});scene.remove(group);}
function buildWorld(index){
 disposeGroup(world);const existing=new Set(scene.children);track=window.RaceTracks[index];length=track.length;const theme=track.meta;
 scene.background=new THREE.Color(theme.sky);scene.fog=new THREE.Fog(theme.fog,85,660);sun.color.setHex(theme.light);sun.intensity=index===1?2.4:2.9;hemi.color.setHex(index===0?0xc4b6cb:index===1?0x91b7aa:0xb1c6f0);hemi.groundColor.setHex(theme.stone);
 distances=[...Array.from({length:1501},(_,i)=>i/1500*length),...track.gaps.flatMap(g=>[g.start-22,g.start,g.end,g.end+24])].sort((a,b)=>a-b);samples=distances.map(d=>sample(d));N=samples.length-1;torchAnchors=[];
 function strip(lo,hi,lift,colors,land=false){const verts=[],cols=[],uvs=[];for(let i=0;i<N;i++){const a=samples[i],b=samples[i+1],mid=(distances[i]+distances[i+1])/2;if(track.gapAt(mid)||(land&&track.bridgeAt(mid)))continue;const color=new THREE.Color(colors[Math.floor(distances[i]/5)%colors.length]);for(const [s,w] of [[a,lo],[b,lo],[a,hi],[a,hi],[b,lo],[b,hi]]){verts.push(s.p.x+s.right.x*w,s.p.y+lift,s.p.z+s.right.z*w);cols.push(color.r,color.g,color.b);uvs.push(w/4,(s===a?distances[i]:distances[i+1])/5);}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setAttribute('color',new THREE.Float32BufferAttribute(cols,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));g.computeVertexNormals();const m=mesh(g,new THREE.MeshStandardMaterial({vertexColors:true,bumpMap:stoneTexture,bumpScale:.09,roughnessMap:stoneTexture,roughness:land?.85:.56,metalness:land?0:.32,side:THREE.DoubleSide}));m.name='track-strip';return m;}
 const liquid=mesh(new THREE.PlaneGeometry(2800,2800),mat(theme.liquid,{roughness:.12,metalness:.65}),0,-3,0);liquid.rotation.x=-Math.PI/2;
 strip(-11.25,11.25,-.14,[theme.stone],true);strip(-9.45,9.45,0,[theme.road,theme.road,new THREE.Color(theme.road).multiplyScalar(1.035).getHex()]);strip(-9.95,-9.4,.025,[theme.stone,theme.accent]);strip(9.4,9.95,.025,[theme.stone,theme.accent]);
 for(const side of [-1,1]){const verts=[];for(let i=0;i<N;i++){if(track.bridgeAt((distances[i]+distances[i+1])/2))continue;const a=samples[i],b=samples[i+1],top=s=>[s.p.x+s.right.x*side*11.25,s.p.y-.12,s.p.z+s.right.z*side*11.25],bottom=s=>[s.p.x+s.right.x*side*13,-3,s.p.z+s.right.z*side*13];for(const p of [top(a),bottom(a),top(b),top(b),bottom(a),bottom(b)])verts.push(...p);}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));geo.computeVertexNormals();mesh(geo,mat(theme.stone,{side:THREE.DoubleSide,roughness:.87}));}
 let seed=824+index*977;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
 function spire(x,y,z,size=1){const g=new THREE.Group();g.position.set(x,y,z);g.scale.setScalar(size);scene.add(g);mesh(new THREE.CylinderGeometry(1.3,2,13,8),mat(theme.stone,{roughness:.7}),0,6,0,g,true);mesh(new THREE.ConeGeometry(2,7,8),mat(0x272d37,{metalness:.45,roughness:.38}),0,15.8,0,g,true);for(const h of [2,7,12]){mesh(new THREE.TorusGeometry(1.45,.12,5,8),0x817868,0,h,0,g).rotation.x=Math.PI/2;}box(.28,3,.12,mat(theme.accent,{emissive:theme.accent,emissiveIntensity:1.6}),0,9,1.42,g);}
 function tree(x,y,z,size){const g=new THREE.Group();g.position.set(x,y,z);g.scale.setScalar(size);scene.add(g);mesh(new THREE.CylinderGeometry(.18,.7,10,7),0x303d3a,0,5,0,g);for(let j=0;j<5;j++){const limb=mesh(new THREE.CylinderGeometry(.04,.19,5,5),0x3a4840,0,6+j*.8,0,g);limb.rotation.z=(j%2?1:-1)*.75;limb.rotation.y=j*1.7;}if(index===1)for(let j=0;j<3;j++)ellipsoid((rand()-.5)*3,9+j*1.4,0,2.8,1.9,2.3,0x3a5950,g);}
 function crystal(x,y,z,size){const c=mesh(new THREE.ConeGeometry(size*.4,size*2.7,5),mat(0x9fbacc,{metalness:.3,roughness:.17,emissive:0x344a6c,emissiveIntensity:.8}),x,y+size,z);c.rotation.z=.16;}
 for(let i=0;i<50;i++){const d=i/50*length;if(track.bridgeAt(d))continue;const s=sample(d,(i%2?1:-1)*(13+rand()*3));ellipsoid(s.p.x,s.p.y-2,s.p.z,4,2.6,4,theme.stone);if(index===0)spire(s.p.x,s.p.y,s.p.z,.5+rand()*.5);else if(index===1)tree(s.p.x,s.p.y,s.p.z,.9+rand()*.6);else crystal(s.p.x,s.p.y,s.p.z,2+rand()*3);}
 for(let i=0;i<60;i++){const d=i/60*length;if(track.bridgeAt(d))continue;const s=sample(d,i%2?10.5:-10.5);box(.28,2.1,.28,mat(0x595552,{metalness:.75}),s.p.x,s.p.y+1,s.p.z);const flame=ellipsoid(s.p.x,s.p.y+2.3,s.p.z,.24,.55,.24,mat(theme.accent,{emissive:theme.accent,emissiveIntensity:4}));torchAnchors.push(flame.position.clone());}
 // Cathedral silhouettes and broken arches sit beyond the driving surface.
 for(let i=0;i<8;i++){const a=i/8*Math.PI*2,x=Math.cos(a)*90,z=Math.sin(a)*105;spire(x,1,z,1.7+rand()*2);}
 for(let i=0;i<12;i++){const a=i*2.4;ellipsoid(Math.cos(a)*490,-20,Math.sin(a)*490,70,80+rand()*65,70,theme.stone);}
 const moon=ellipsoid(-280,260,-500,24,24,24,new THREE.MeshBasicMaterial({color:index===0?0xeac991:0xc0d5ee}));
 for(const gap of track.gaps)for(const d of [gap.start-25,gap.end+25]){const s=sample(d),g=new THREE.Group();g.position.copy(s.p);g.rotation.y=Math.atan2(s.tx,s.tz);scene.add(g);for(const x of [-10.8,10.8]){box(1,12,1,theme.stone,x,5,0,g,true);mesh(new THREE.ConeGeometry(1.1,3,5),theme.stone,x,12,0,g);}box(23,.5,1,theme.stone,0,11,0,g);if(d<gap.start)box(7,1.5,.15,label('↗ '+Math.round(gap.end-gap.start)+' м','#25292e','#d7bf91'),0,9.8,0,g);}
 for(let d=190;d<length;d+=95){if(track.bridgeAt(d))continue;const a=sample(d),b=sample(d+32),turn=C.angle(Math.atan2(b.tx,b.tz)-Math.atan2(a.tx,a.tz));if(Math.abs(turn)<.24)continue;const s=sample(d,Math.sign(turn)*11),g=new THREE.Group();g.position.copy(s.p);g.rotation.y=Math.atan2(a.tx,a.tz);scene.add(g);box(.2,2.5,.2,theme.stone,0,1,0,g);box(3.2,1,.1,label(turn>0?'‹ ‹ ‹':'› › ›','#262e32','#d3c09a'),0,2.3,0,g);}
 const start=sample(0),arch=new THREE.Group();arch.position.copy(start.p);arch.rotation.y=Math.atan2(start.tx,start.tz);scene.add(arch);for(const x of [-10.8,10.8]){box(1.4,13,1.4,theme.stone,x,6,0,arch,true);mesh(new THREE.ConeGeometry(1.5,4,6),theme.stone,x,14,0,arch);}box(24,2.3,1.4,mat(0x4a4644,{metalness:.35}),0,11.5,0,arch);box(19,1.55,1.42,label('ASHEN COVENANT','#343337','#d7ba86'),0,11.5,0,arch);
 for(let j=0;j<20;j++)for(let k=0;k<3;k++)box(.9,.03,.8,(j+k)%2?0xb6aaa0:0x34393f,(j-9.5)*.9,.08,k*.8-1,arch);
 for(const d of track.pads){const s=sample(d),g=new THREE.Group();g.position.copy(s.p);g.rotation.set(-Math.atan(s.slope),Math.atan2(s.tx,s.tz),0,'YXZ');scene.add(g);box(9,.03,5,mat(0x34333c,{metalness:.5,roughness:.25}),0,.06,0,g);for(let k=0;k<3;k++){const rune=mesh(new THREE.TorusGeometry(.75,.035,4,4),mat(theme.accent,{emissive:theme.accent,emissiveIntensity:2}),0,.1,(k-1)*1.5,g);rune.rotation.x=Math.PI/2;}}
 // Small wet patches use the scene reflection map, not a painted highlight.
 for(let i=0;i<40;i++){const d=(i+.3)/40*length;if(track.bridgeAt(d))continue;const s=sample(d,Math.sin(i*2)*5),patch=mesh(new THREE.CircleGeometry(1.2+i%3*.5,18),mat(theme.road,{metalness:.78,roughness:.08,transparent:true,opacity:.38,depthWrite:false}),s.p.x,s.p.y+.027,s.p.z);patch.rotation.set(-Math.PI/2-Math.atan(s.slope),Math.atan2(s.tx,s.tz),0,'YXZ');patch.scale.y=.55;}
 pickupMeshes=[];const runeMat=mat(theme.accent,{emissive:theme.accent,emissiveIntensity:1.4,metalness:.45,roughness:.2});for(const d of track.pickups){const row=[];for(const lane of [-5,0,5]){const s=sample(d,lane),m=mesh(new THREE.OctahedronGeometry(.92),runeMat,s.p.x,s.p.y+1.7,s.p.z);m.name='pickup';row.push(m);}pickupMeshes.push(row);}
 world=new THREE.Group();world.name='course';for(const child of [...scene.children])if(!existing.has(child))world.add(child);scene.add(world);
 // ponytail: one local environment capture per course; continuous reflections would need a lower-cost reflection pass.
 if(renderer.getContext){scene.environment=null;reflection?.dispose();const cube=new THREE.WebGLCubeRenderTarget(128,{type:THREE.HalfFloatType}),capture=new THREE.CubeCamera(.1,900,cube),s=sample(0);capture.position.set(s.p.x,s.p.y+5,s.p.z);capture.update(renderer,scene);const pmrem=new THREE.PMREMGenerator(renderer);reflection=pmrem.fromCubemap(cube.texture);scene.environment=reflection.texture;cube.dispose();pmrem.dispose();}
}
buildWorld(0);
function kart(type){
 const hero=C.DRIVERS[type],g=new THREE.Group(),body=new THREE.Group();g.add(body);g.name='hero-'+type;
 const paint=mat(hero.color,{metalness:.78,roughness:.3}),steel=mat(0x3d424a,{metalness:.87,roughness:.26}),gold=mat(0xb09b70,{metalness:.82,roughness:.3}),leather=mat(0x292b32,{roughness:.85}),glow=mat(hero.glow,{emissive:hero.glow,emissiveIntensity:2.6,metalness:.3,roughness:.24});
 softBox(1.85,.44,2.8,steel,0,.63,0,body,true);softBox(1.52,.43,2.1,paint,0,.89,.26,body,true);ellipsoid(0,1.05,.86,.65,.21,.64,paint,body,true);softBox(1.8,.14,.38,gold,0,.59,1.5,body,true);
 for(const x of [-.78,.78]){softBox(.35,.28,1.75,paint,x,.98,-.15,body,true);box(.045,.035,1.4,gold,x,1.135,-.1,body);for(let j=0;j<4;j++)box(.24,.035,.08,gold,x,1.13,-.55+j*.22,body);const exhaust=mesh(new THREE.CylinderGeometry(.13,.15,.65,12),steel,x,.65,-1.4,body);exhaust.rotation.x=Math.PI/2;mesh(new THREE.TorusGeometry(.15,.035,6,12),gold,x,.65,-1.74,body);ellipsoid(x,.9,1.08,.12,.085,.08,glow,body);}
 for(const z of [-.93,.85]){const axle=mesh(new THREE.CylinderGeometry(.07,.07,2.2,8),steel,0,.49,z,body);axle.rotation.z=Math.PI/2;}
 const ws=[];for(const x of [-1.08,1.08])for(const z of [-.94,.89]){const pivot=new THREE.Group();pivot.position.set(x,.48,z);body.add(pivot);const wheel=mesh(new THREE.CylinderGeometry(.46,.46,.43,24),mat(0x1e2229,{roughness:.94}),0,0,0,pivot,true);wheel.rotation.z=Math.PI/2;const face=x<0?-.235:.235;const rim=mesh(new THREE.TorusGeometry(.3,.055,8,20),gold,face,0,0,pivot);rim.rotation.y=Math.PI/2;for(let j=0;j<6;j++){const spoke=box(.045,.55,.045,steel,face,0,0,pivot);spoke.rotation.x=j/6*Math.PI;}ellipsoid(face,0,0,.07,.1,.1,glow,pivot);ws.push(wheel);}
 box(.85,.55,.72,leather,0,1.04,-.35,body);const cloak=mesh(new THREE.ConeGeometry(.58,1.25,10,1,true),mat(type===3?0x332c49:0x342c32,{side:THREE.DoubleSide,roughness:1}),0,1.32,-.41,body);cloak.scale.z=.52;
 ellipsoid(0,1.53,-.16,.4,.53,.32,paint,body,true);for(const x of [-.43,.43]){ellipsoid(x,1.76,-.13,.28,.2,.3,steel,body,true);const spike=mesh(new THREE.ConeGeometry(.075,.28,5),gold,x,1.98,-.17,body);spike.rotation.z=-x*.35;}
 const fur=[0xb1815c,0x7f8988,0xc5c2ca,0x3a425b,0x9eaba9][type];ellipsoid(0,2.12,-.09,.49,.47,.41,fur,body,true);
 if(type===0||type===4){for(const x of [-.34,.34]){const ear=mesh(new THREE.ConeGeometry(.18,.58,4),fur,x,2.59,-.14,body);ear.rotation.z=-x*.25;mesh(new THREE.ConeGeometry(.09,.32,4),0x393239,x,2.6,-.04,body);}ellipsoid(0,1.99,.29,type===4?.29:.25,.2,.29,type===4?0xd0d3c8:0xd5bc9c,body);ellipsoid(0,2.035,.55,.085,.06,.055,0x252932,body);const tail=ellipsoid(.16,1.05,-1.05,.22,.24,.65,fur,body);tail.rotation.x=-.45;
 }else if(type===1){for(const x of [-.35,.35])ellipsoid(x,2.54,-.13,.18,.2,.12,fur,body);ellipsoid(0,2.11,.265,.45,.13,.11,0x303a42,body);ellipsoid(0,1.96,.34,.24,.15,.16,0xb5b7a9,body);
 }else if(type===2){for(const x of [-.23,.23]){const ear=ellipsoid(x,2.77,-.12,.13,.58,.12,fur,body);ear.rotation.z=-x*.4;ellipsoid(x,2.77,-.005,.055,.39,.025,0x858198,body);}ellipsoid(0,1.99,.31,.23,.17,.13,0xe1dcd8,body);
 }else{const beak=mesh(new THREE.ConeGeometry(.19,.5,4),gold,0,2.0,.43,body);beak.rotation.x=Math.PI/2;for(const x of [-.34,.34])ellipsoid(x,2.31,-.17,.19,.28,.16,0x2a3046,body);}
 for(const x of [-.2,.2]){ellipsoid(x,2.17,.285,.1,.065,.055,0x242935,body);ellipsoid(x,2.17,.335,.045,.035,.02,glow,body);}
 // Brow crown, engraved collar and back-mounted rune distinguish the silhouettes.
 const crown=mesh(new THREE.TorusGeometry(.45,.045,6,20,Math.PI*1.4),gold,0,2.35,-.06,body);crown.rotation.x=Math.PI/2;for(const x of [-.26,0,.26])mesh(new THREE.ConeGeometry(.065,.2+(x===0?.12:0),5),gold,x,2.52,-.2,body);
 const collar=mesh(new THREE.TorusGeometry(.36,.05,6,16),gold,0,1.84,-.13,body);collar.rotation.x=Math.PI/2;
 const backRune=mesh(new THREE.TorusGeometry(.24,.035,6,type===1?4:6),glow,0,1.56,-.53,body);backRune.rotation.z=Math.PI/4;
 ellipsoid(.43,1.35,.37,.15,.17,.22,steel,body);const hand=ellipsoid(-.6,1.35,.4,.15,.17,.22,steel,body);
 const steering=mesh(new THREE.TorusGeometry(.28,.045,6,18),gold,0,1.25,.61,body);steering.rotation.x=-.5;
 const shield=mesh(new THREE.SphereGeometry(1.7,20,14),mat(hero.glow,{transparent:true,opacity:.14,metalness:.5,roughness:.12,depthWrite:false}),0,1.3,0,g);shield.visible=false;
 const flame=ellipsoid(0,.68,-1.75,.3,.24,.85,glow,g);flame.visible=false;
 const held=new THREE.Group();body.add(held);const items={};for(const type of Object.keys(C.ITEMS)){const item=new THREE.Group();held.add(item);items[type]=item;item.visible=false;if(type==='coconut'){ellipsoid(0,0,0,.29,.29,.29,mat(0xbfcac2,{metalness:.65,roughness:.2,emissive:0x6495a0,emissiveIntensity:.7}),item);mesh(new THREE.TorusGeometry(.34,.025,6,16),glow,0,0,0,item);}else if(type==='bomb'){mesh(new THREE.IcosahedronGeometry(.36,1),mat(0x443146,{metalness:.45,roughness:.3}),0,0,0,item);for(const x of [-.15,.15])mesh(new THREE.ConeGeometry(.07,.25,5),glow,x,.34,0,item);}else if(type==='boost'){mesh(new THREE.CylinderGeometry(.13,.2,.5,10),glow,0,0,0,item);mesh(new THREE.CylinderGeometry(.13,.13,.12,8),gold,0,.29,0,item);}else mesh(new THREE.TorusGeometry(.3,.065,6,6),glow,0,0,0,item);}
 const respawnRing=mesh(new THREE.TorusGeometry(1.65,.035,6,36),glow,0,.1,0,g);respawnRing.rotation.x=Math.PI/2;respawnRing.visible=false;scene.add(g);return {g,body,ws,shield,flame,hand,held,items,respawnRing};
}
let selected=0,selectedTrack=0,models=[],modelSelected=-1;
function buildKarts(){if(modelSelected===selected)return;modelSelected=selected;for(const k of models)disposeGroup(k.g);models=Array.from({length:6},(_,i)=>kart(i===0?selected:(selected+i)%C.DRIVERS.length));}buildKarts();
const particles=[];for(let i=0;i<60;i++){const m=mesh(new THREE.SphereGeometry(.12,4,3),mat(0xffd46a,{emissive:0xff9d39,emissiveIntensity:1.4}));m.visible=false;particles.push({m,life:0,v:new THREE.Vector3()});}let particleIndex=0;
function spark(pos,right){const p=particles[particleIndex++%particles.length];p.m.position.copy(pos).addScaledVector(right,(Math.random()>.5?1:-1)*1.1);p.m.position.y+=.3;p.v.set((Math.random()-.5)*4,1+Math.random()*2,(Math.random()-.5)*4);p.life=.3+Math.random()*.25;p.m.visible=true;}
const projectileViews=Array.from({length:18},()=>{const g=new THREE.Group();scene.add(g);const coconut=ellipsoid(0,0,0,.5,.5,.5,mat(0xa7c2be,{emissive:0x6095a0,emissiveIntensity:.7,metalness:.65,roughness:.2}),g,true),bomb=ellipsoid(0,0,0,.6,.6,.6,mat(0x4a3c51,{emissive:0x8f5374,emissiveIntensity:.7,metalness:.6,roughness:.3}),g,true);const band=mesh(new THREE.TorusGeometry(.45,.055,5,12),0xf4d095,0,0,0,g);g.visible=false;return {g,coconut,bomb,band};});
const blastViews=Array.from({length:10},()=>{const m=mesh(new THREE.SphereGeometry(1,14,10),new THREE.MeshBasicMaterial({color:0xffc7aa,transparent:true,opacity:.3,depthWrite:false}));m.visible=false;return m;});
const smokeCanvas=document.createElement('canvas');smokeCanvas.width=smokeCanvas.height=64;const smokeCtx=smokeCanvas.getContext('2d'),gradient=smokeCtx.createRadialGradient(32,32,2,32,32,32);gradient.addColorStop(0,'rgba(190,195,200,.6)');gradient.addColorStop(.45,'rgba(155,160,170,.24)');gradient.addColorStop(1,'rgba(120,130,145,0)');smokeCtx.fillStyle=gradient;smokeCtx.fillRect(0,0,64,64);const smokeTexture=new THREE.CanvasTexture(smokeCanvas);
const smoke=Array.from({length:72},()=>{const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:smokeTexture,transparent:true,opacity:0,depthWrite:false,color:0xbfc5ce}));scene.add(sprite);return {sprite,life:0,maxLife:1,v:new THREE.Vector3()};});let smokeIndex=0;
function tireSmoke(r){for(const side of [-1,1]){const p=smoke[smokeIndex++%smoke.length];p.life=p.maxLife=.9+Math.random()*.5;p.sprite.position.set(r.x-Math.cos(r.yaw)*side-Math.sin(r.yaw),r.y+.28,r.z+Math.sin(r.yaw)*side-Math.cos(r.yaw));p.sprite.material.rotation=Math.random()*Math.PI;p.v.set(-r.vx*.05+(Math.random()-.5)*.8,1.1+Math.random(),-r.vz*.05+(Math.random()-.5)*.8);}}
const skidPositions=new Float32Array(1200*18),skidGeometry=new THREE.BufferGeometry();skidGeometry.setAttribute('position',new THREE.BufferAttribute(skidPositions,3));skidGeometry.setDrawRange(0,0);const skidMesh=new THREE.Mesh(skidGeometry,new THREE.MeshBasicMaterial({color:0x13181d,transparent:true,opacity:.5,side:THREE.DoubleSide,depthWrite:false}));skidMesh.frustumCulled=false;scene.add(skidMesh);let skidIndex=0,skidCount=0,lastTire=null;
function leaveSkid(r){const rx=-Math.cos(r.yaw),rz=Math.sin(r.yaw),tires=[-1,1].map(side=>({x:r.x+rx*side-Math.sin(r.yaw)*.94,z:r.z+rz*side-Math.cos(r.yaw)*.94}));if(lastTire)for(let i=0;i<2;i++){const a=lastTire[i],b=tires[i],dist=Math.hypot(b.x-a.x,b.z-a.z);if(dist<.04||dist>3)continue;const nx=-(b.z-a.z)/dist*.11,nz=(b.x-a.x)/dist*.11,ay=track.nearest(a.x,a.z,r.nearD).y+.045,by=track.nearest(b.x,b.z,r.nearD).y+.045;const points=[[a.x+nx,ay,a.z+nz],[a.x-nx,ay,a.z-nz],[b.x+nx,by,b.z+nz],[b.x+nx,by,b.z+nz],[a.x-nx,ay,a.z-nz],[b.x-nx,by,b.z-nz]];skidPositions.set(points.flat(),skidIndex*18);skidIndex=(skidIndex+1)%1200;skidCount=Math.min(1200,skidCount+1);}lastTire=tires;skidGeometry.attributes.position.needsUpdate=true;skidGeometry.setDrawRange(0,skidCount*6);}
const torchLights=Array.from({length:4},()=>{const light=new THREE.PointLight(0xffc185,45,35,2);scene.add(light);return light;});
const headLights=[-1,1].map(side=>{const light=new THREE.SpotLight(0xffe2ac,100,52,.46,.65,2);scene.add(light,light.target);return {light,side};});
function updateAtmosphere(dt){for(const p of smoke){if(p.life<=0){p.sprite.visible=false;continue;}p.life-=dt;p.sprite.visible=true;p.sprite.position.addScaledVector(p.v,dt);const t=1-p.life/p.maxLife;p.sprite.scale.setScalar(.65+t*2.5);p.sprite.material.opacity=(1-t)*.5;}
 const p=state.racers[0],nearest= [...torchAnchors].sort((a,b)=>(a.x-p.x)**2+(a.z-p.z)**2-((b.x-p.x)**2+(b.z-p.z)**2));torchLights.forEach((light,i)=>{if(nearest[i])light.position.copy(nearest[i]);light.color.setHex(track.meta.accent);light.intensity=42+Math.sin(elapsed*7+i)*5;});for(const {light,side} of headLights){const rx=-Math.cos(p.yaw),rz=Math.sin(p.yaw);light.position.set(p.x+rx*side*.65,p.y+1.15,p.z+rz*side*.65);light.target.position.set(p.x+Math.sin(p.yaw)*20,p.y-1,p.z+Math.cos(p.yaw)*20);light.visible=p.phase==='driving';}}
function updateEffects(){
 projectileViews.forEach((view,i)=>{const b=state.projectiles[i];view.g.visible=!!b;if(!b)return;view.g.position.set(b.x,b.y,b.z);view.g.rotation.set(elapsed*8,elapsed*3,0);view.coconut.visible=b.type==='coconut';view.band.visible=b.type==='coconut';view.bomb.visible=b.type==='bomb';});
 blastViews.forEach((view,i)=>{const e=state.effects[i];view.visible=!!e;if(!e)return;view.position.set(e.x,e.y,e.z);const t=1-e.life/e.maxLife;view.scale.setScalar((e.type==='blast'?7:2)*t+.3);view.material.opacity=(1-t)*.4;});
}
let simulationDebt=0;let mode='menu',state=C.createRace(track),keys={},countdown=3.5,last=performance.now(),elapsed=0,noticeUntil=0,uiClock=0,previousCount=4;
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const profileKey='wild-drift-ashen-profile-v1';let profile=C.newProfile(),storageWritable=true;
function storageWarning(message){$('storageNotice').textContent=message;$('storageNotice').classList.remove('hidden');}
try{profile=C.parseProfile(localStorage.getItem(profileKey));}catch{storageWritable=false;storageWarning('Сохранение недоступно. Прогресс этой сессии останется в памяти до закрытия вкладки; старое сохранение не изменено.');}
function mutateProfile(action){if(storageWritable){try{profile=C.parseProfile(localStorage.getItem(profileKey));}catch{storageWritable=false;storageWarning('Не удалось прочитать сохранение. Старые данные не перезаписываются.');}}
 const result=action(profile);if(storageWritable){try{localStorage.setItem(profileKey,JSON.stringify(profile));}catch{storageWritable=false;storageWarning('Браузер не разрешил сохранить прогресс. Не закрывай вкладку, чтобы не потерять улучшения этой сессии.');}}return result;}
function showBest(){const best=profile.records[window.RaceTracks[selectedTrack].id];$('menuBest').textContent=best?'ЛЕТОПИСЬ  '+C.formatTime(best):'ВПИШИ СВОЁ ИМЯ В ЛЕТОПИСЬ';}
function mapPoint(t,x,z,w,h){const b=t.bounds,scale=Math.min((w-20)/(b.maxX-b.minX),(h-15)/(b.maxZ-b.minZ));return [w/2+(x-(b.minX+b.maxX)/2)*scale,h/2+(z-(b.minZ+b.maxZ)/2)*scale];}
function drawCourseCards(){window.RaceTracks.forEach((t,i)=>{const canvas=$('courseMap'+i),ctx=canvas.getContext('2d');ctx.clearRect(0,0,150,85);ctx.strokeStyle='#'+t.meta.accent.toString(16).padStart(6,'0');ctx.lineWidth=2;ctx.beginPath();t.segments.forEach((seg,j)=>{if(j%5)return;const [x,y]=mapPoint(t,seg.a.x,seg.a.z,150,85);if(j===0||t.gapAt(seg.d))ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();$('courseMeta'+i).textContent=(t.length/1000).toFixed(2).replace('.',',')+' км · '+t.gaps.length+' разрыва';});}
function renderForge(){const hero=C.DRIVERS[selected],h=profile.heroes[selected],v=C.stats(selected,h.upgrades),points=C.skillPoints(h);$('forgeTitle').textContent=hero.name+' · '+hero.kind;$('forgeTrait').textContent=hero.trait+'. '+hero.description;$('forgeLevel').textContent='Уровень '+(1+Math.floor(h.xp/150));$('forgeXP').textContent=(h.xp%150)+' / 150 опыта';$('xpBar').style.width=(h.xp%150)/150*100+'%';$('forgePoints').textContent=points;
 const values={Speed:Math.round(v.speed*3.1)+' км/ч',Handling:Math.round(v.handling*100)+'%',Acceleration:v.acceleration.toFixed(1),Braking:v.braking.toFixed(1),Aero:Math.round(v.aero*100)+'%'};for(const [key,value] of Object.entries(values)){$('stat'+key).textContent=value;$('level'+key).textContent=h.upgrades[key.toLowerCase()]+'/5';}document.querySelectorAll('[data-upgrade]').forEach(b=>{b.disabled=points<1||h.upgrades[b.dataset.upgrade]>=5;});}
function renderMenu(){const hero=C.DRIVERS[selected],h=profile.heroes[selected],t=window.RaceTracks[selectedTrack];$('heroTrait').textContent=hero.trait;$('traitDescription').textContent=hero.description;$('pointsBadge').textContent=C.skillPoints(h);$('selectedCourseName').textContent=t.name;$('selectedCourseDescription').textContent=t.meta.subtitle;document.querySelector('.selection-number').textContent='0'+(selected+1)+' / 05';C.DRIVERS.forEach((d,i)=>{$('heroLevel'+i).textContent=d.kind+' · ур. '+(1+Math.floor(profile.heroes[i].xp/150));});showBest();renderForge();}
$('openForge').addEventListener('click',()=>{renderForge();$('forge').classList.remove('hidden');$('closeForge').focus();});$('forge').addEventListener('keydown',e=>{if(e.code!=='Tab')return;const buttons=[$('closeForge'),...document.querySelectorAll('[data-upgrade]'),$('forgeDone')].filter(b=>!b.disabled),first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});for(const id of ['closeForge','forgeDone'])$(id).addEventListener('click',()=>{$('forge').classList.add('hidden');$('openForge').focus();});
document.querySelectorAll('[data-upgrade]').forEach(button=>button.addEventListener('click',()=>{mutateProfile(p=>C.upgrade(p,selected,button.dataset.upgrade));renderMenu();}));
document.querySelectorAll('[data-track]').forEach(button=>button.addEventListener('click',()=>{selectedTrack=Number(button.dataset.track);document.querySelectorAll('[data-track]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));});renderMenu();}));
drawCourseCards();renderMenu();
$('keyArt').style.backgroundImage='url("assets/fantasy-art.png")';
let soundOn=false,audio=null,engine=null,engineGain=null;
function initAudio(){if(!audio){const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;audio=new AudioContext();engine=audio.createOscillator();engine.type='sawtooth';const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=330;engineGain=audio.createGain();engineGain.gain.value=0;engine.connect(filter);filter.connect(engineGain);engineGain.connect(audio.destination);engine.start();}if(audio.state==='suspended')audio.resume().catch(()=>{});}
function beep(freq=600,duration=.15){if(!soundOn||!audio)return;const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(.12,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration);}
function showNotice(text){$('notice').textContent=text;noticeUntil=elapsed+2.3;beep(text.includes('КРУГ')?880:580,.13);}
function hideOverlays(){for(const id of ['menu','pause','finish','forge'])$(id).classList.add('hidden');}
function startRace(){initAudio();keys={};if(track.courseIndex!==selectedTrack)buildWorld(selectedTrack);state=C.createRace(track,selected,profile.heroes[selected].upgrades);state.rng=Math.floor(Math.random()*4294967296);$('hudCourseName').textContent=track.name.toUpperCase();simulationDebt=0;skidIndex=skidCount=0;lastTire=null;for(const p of smoke)p.life=0;skidGeometry.setDrawRange(0,0);countdown=3.5;previousCount=4;mode='countdown';noticeUntil=0;$('notice').textContent='';$('countdown').textContent='3';hideOverlays();$('hud').classList.remove('hidden');$('pauseButton').classList.remove('hidden');document.body.classList.add('racing');buildKarts();placeKarts(0);updateCamera(1,true);updateHUD();$('start').blur();}
function pauseRace(){if(mode!=='race'&&mode!=='countdown')return;mode=mode==='race'?'paused':'paused-countdown';keys={};$('pause').classList.remove('hidden');$('resume').focus();}
function resumeRace(){if(mode!=='paused'&&mode!=='paused-countdown')return;mode=mode==='paused'?'race':'countdown';$('pause').classList.add('hidden');keys={};}
function menu(){mode='menu';keys={};hideOverlays();$('menu').classList.remove('hidden');$('hud').classList.add('hidden');$('pauseButton').classList.add('hidden');document.body.classList.remove('racing');renderMenu();$('start').focus();}
function finishRace(){mode='finish';$('hud').classList.add('hidden');$('pauseButton').classList.add('hidden');$('finish').classList.remove('hidden');$('finishRank').innerHTML=state.rank+'<span>МЕСТО</span>';$('finishTitle').textContent=state.rank===1?'Пепел помнит победителя.':state.rank<=3?'Завет исполнен.':'Бездна ждёт реванша.';$('finishTime').textContent=C.formatTime(state.finishTime);$('bestLap').textContent=C.formatTime(Math.min(...state.lapTimes));const best=profile.records[track.id];$('record').textContent=!best||state.finishTime<best?'Новая запись в летописи ✦':'Рекорд мира: '+C.formatTime(best);const reward=mutateProfile(p=>C.awardRace(p,state));$('reward').textContent=reward?'+'+reward.xp+' опыта'+(reward.levelUps?' · +'+reward.levelUps+' очк. улучшений':''):'';renderMenu();beep(880,.5);$('again').focus();}
for(const id of ['start','restart','again'])$(id).addEventListener('click',startRace);$('resume').addEventListener('click',resumeRace);for(const id of ['back','garage'])$(id).addEventListener('click',menu);$('pauseButton').addEventListener('click',pauseRace);document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();if(mode==='menu')return;pauseRace();});
document.querySelectorAll('[data-driver]').forEach(button=>button.addEventListener('click',()=>{selected=Number(button.dataset.driver);document.querySelectorAll('[data-driver]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));});buildKarts();renderMenu();}));
$('sound').addEventListener('click',()=>{soundOn=!soundOn;initAudio();$('sound').querySelector('.slash').classList.toggle('hidden',soundOn);$('sound').setAttribute('aria-label',soundOn?'Выключить звук':'Включить звук');beep();});
$('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else showNotice('Используй полноэкранный режим браузера');}catch{showNotice('Используй полноэкранный режим браузера');}});
function activateItem(){if(mode==='race'&&C.useItem(state))beep(700,.2);}$('item').addEventListener('click',activateItem);
const controlCodes=['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD','Space','ShiftLeft','ShiftRight'];
window.addEventListener('keydown',e=>{if(controlCodes.includes(e.code)&&(mode==='race'||mode==='countdown'))e.preventDefault();keys[e.code]=true;if(e.repeat)return;if(e.code==='Escape'){if(!$('forge').classList.contains('hidden')){$('forge').classList.add('hidden');$('openForge').focus();return;}if(mode.startsWith('paused'))resumeRace();else pauseRace();}if(e.code.startsWith('Shift'))activateItem();if(e.code==='KeyR'&&mode==='race')C.recover(state);});window.addEventListener('keyup',e=>{keys[e.code]=false;});
window.addEventListener('blur',()=>{keys={};pauseRace();});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys={};pauseRace();}});
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>{keys[b.dataset.key]=false;});});
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.75));});
function getInput(){return {throttle:!!(keys.KeyW||keys.ArrowUp),brake:!!(keys.KeyS||keys.ArrowDown),steer:Number(!!(keys.KeyD||keys.ArrowRight))-Number(!!(keys.KeyA||keys.ArrowLeft)),drift:!!keys.Space};}
function placeKarts(dt){
 for(let i=0;i<models.length;i++){
  const r=state.racers[i],k=models[i];k.g.position.set(r.x,r.y,r.z);
  const pitch=r.grounded?Math.atan(r.surface.slope)*(Math.cos(r.yaw)*r.surface.tz+Math.sin(r.yaw)*r.surface.tx):Math.atan2(r.vy,Math.max(r.speed,1));
  k.g.rotation.set(-pitch,r.yaw,0,'YXZ');
  k.body.rotation.z=THREE.MathUtils.damp(k.body.rotation.z,r.steering*(r.drifting?.1:.055),10,dt);
  k.body.rotation.y=r.hitAnim>0?Math.sin(r.hitAnim*19)*.45:0;
  k.body.position.y=(r.speed>1&&r.grounded?Math.sin(elapsed*20+i)*.018:0)-(r.landing>0?Math.sin(r.landing/.4*Math.PI)*.16:0);
  k.g.visible=true;k.g.scale.setScalar(1);k.respawnRing.visible=false;
  if(r.phase==='falling'){k.body.rotation.z+=Math.sin(elapsed*4)*.2;k.g.scale.setScalar(Math.max(.3,r.phaseTime/.8));}
  if(r.phase==='respawning'){const t=1-r.phaseTime/1.05;k.g.position.y+=7*(1-t)**3;k.g.scale.setScalar(.7+.3*t);k.g.visible=Math.floor(r.phaseTime*18)%3!==0;k.respawnRing.visible=true;k.respawnRing.scale.setScalar(1.8-.8*t);}
  for(let j=0;j<k.ws.length;j++){const wheel=k.ws[j];wheel.rotation.x+=r.speed*dt*2;if(wheel.parent!==k.body)wheel.parent.rotation.y=j%2===1?-r.steering*.38:0;}
  k.shield.visible=r.shield>0&&r.phase!=='falling';k.flame.visible=r.boost>0&&r.phase==='driving';k.flame.scale.z=.65+Math.sin(elapsed*50)*.15;
  k.hand.position.set(r.item?-.85:-.6,r.item?1.92:1.27,r.item?-.12:.45);k.hand.rotation.z=r.item?-.4:0;
  if(r.throwAnim>0){k.hand.position.y=1.6+Math.sin(r.throwAnim/.4*Math.PI)*.65;k.hand.position.z=.3+Math.sin(r.throwAnim/.4*Math.PI)*.8;}
  k.held.position.copy(k.hand.position);k.held.position.y+=.3;k.held.rotation.y=elapsed*.7;
  for(const [type,object] of Object.entries(k.items))object.visible=r.item===type;
  if(i===0){if(r.grounded&&r.phase==='driving'&&r.drifting&&Math.abs(r.slip)>.13){spark(new THREE.Vector3(r.x,r.y,r.z),new THREE.Vector3(-Math.cos(r.yaw),0,Math.sin(r.yaw)));leaveSkid(r);if(Math.random()<dt*32)tireSmoke(r);}else lastTire=null;}
 }
}
const cameraTarget=new THREE.Vector3();let cameraYaw=0;
function updateCamera(dt,snap=false){
 if(mode==='menu'){const a=reducedMotion?.7:elapsed*.017+.7;camera.position.set(Math.sin(a)*370,185,Math.cos(a)*370);camera.lookAt(0,15,0);return;}
 const p=state.racers[0],travel=p.speed>5?Math.atan2(p.vx,p.vz):p.yaw,targetYaw=p.yaw+C.angle(travel-p.yaw)*.65;
 cameraYaw+=C.angle(targetYaw-cameraYaw)*(snap?1:1-Math.exp(-4.5*dt));const heading=new THREE.Vector3(Math.sin(cameraYaw),0,Math.cos(cameraYaw)),position=new THREE.Vector3(p.x,p.y,p.z);
 if(p.phase==='respawning')position.y+=7*(p.phaseTime/1.05)**3;
 const desired=position.clone().addScaledVector(heading,-12.5-(p.boost>0?1.4:0));desired.y+=6;
 const under=track.nearest(desired.x,desired.z,p.nearD);if(under.ground&&Math.abs(under.lane)<14)desired.y=Math.max(desired.y,under.y+3);
 const factor=snap?1:1-Math.exp(-9*dt);camera.position.lerp(desired,factor);cameraTarget.copy(position).addScaledVector(heading,7);cameraTarget.y+=1.4;camera.lookAt(cameraTarget);
 const fov=58+(p.boost>0&&!reducedMotion?8:0);camera.fov+=(fov-camera.fov)*factor;camera.updateProjectionMatrix();
 sun.position.set(p.x-60,p.y+100,p.z+45);sun.target.position.set(p.x,p.y,p.z);
}
const map=$('minimap').getContext('2d');
function drawMap(){
 map.clearRect(0,0,220,180);const point=s=>mapPoint(track,s.p.x,s.p.z,220,180);map.lineCap='round';
 for(const [width,color] of [[9,'#183f4866'],[3,'#fff6df']]){map.strokeStyle=color;map.lineWidth=width;map.beginPath();for(let i=0;i<=N;i+=3){const [x,y]=point(samples[i]);if(i===0||track.gapAt(distances[i]))map.moveTo(x,y);else map.lineTo(x,y);}map.stroke();}
 for(const gap of track.gaps){const [x,y]=point(sample((gap.start+gap.end)/2));map.fillStyle='#ffbb71';map.fillRect(x-3,y-3,6,6);}
 for(let i=5;i>=0;i--){const r=state.racers[i],[x,y]=point({p:r});map.beginPath();map.arc(x,y,i===0?5:2.8,0,Math.PI*2);map.fillStyle=i===0?'#ff865e':'#fffae4';map.fill();if(i===0){map.strokeStyle='#fffbe7';map.lineWidth=2;map.stroke();}}
}
function updateHUD(){
 const p=state.racers[0];$('speed').textContent=Math.round(p.speed*3.1);$('position').textContent=state.rank;$('lap').textContent=Math.min(3,Math.floor(Math.max(0,p.d)/length)+1);$('timer').textContent=C.formatTime(state.time);$('speedBar').style.width=Math.min(100,p.speed/65*100)+'%';$('driftBar').style.width=p.drift/2.5*100+'%';$('driftLabel').textContent=p.drift>.55?'ОТПУСТИ ПРОБЕЛ → ТУРБО':p.drifting?'ДЕРЖИ ЗАНОС':'ПРОБЕЛ + ПОВОРОТ';
 const info=C.ITEMS[p.item];$('item').classList.toggle('ready',!!info);$('itemIcon').textContent=info?info.icon:'?';$('itemName').textContent=info?info.name:'ПОЙМАЙ БОНУС';$('item').setAttribute('aria-label',info?'Использовать: '+info.name:'Бонус пока не получен');
 const nextGap=track.gaps.map(g=>({g,delta:C.wrap(g.start-p.nearD,length)})).sort((a,b)=>a.delta-b.delta)[0];
 $('jumpCue').classList.toggle('hidden',!(nextGap.delta<100||!p.grounded)&&p.phase==='driving');
 if(p.phase!=='driving'){$('jumpCue').textContent='↟ ВОЗВРАЩЕНИЕ НА ТРАССУ';}
 else if(!p.grounded){$('jumpCue').textContent='↗ В ПОЛЁТЕ';}
 else{$('jumpCue').textContent='↗ РАЗРЫВ '+Math.round(nextGap.g.end-nextGap.g.start)+' М · ЧЕРЕЗ '+Math.round(nextGap.delta)+' М';}
 $('elevation').textContent=Math.round(p.y)+' м';drawMap();const target=C.aimTarget(state),reticle=$('reticle');if(target){camera.updateMatrixWorld();const pos=new THREE.Vector3(target.x,target.y+2,target.z).project(camera);const visible=pos.z>0&&pos.z<1&&Math.abs(pos.x)<.95&&Math.abs(pos.y)<.9;reticle.classList.toggle('hidden',!visible);if(visible){reticle.style.left=(pos.x*.5+.5)*innerWidth+'px';reticle.style.top=(-pos.y*.5+.5)*innerHeight+'px';$('targetName').textContent=C.DRIVERS[target.hero].name+(target.shield>0?' · ЩИТ':'');}}else reticle.classList.add('hidden');
}
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;elapsed+=dt;if(mode==='menu'||mode.startsWith('paused'))return;const running=mode==='race'||mode==='countdown';if(mode==='countdown'){countdown-=dt;const n=Math.ceil(countdown);if(n!==previousCount&&n>0){previousCount=n;beep(n===1?900:500,.15);}$('countdown').textContent=countdown>0?Math.min(3,Math.ceil(countdown)):'СТАРТ!';if(countdown<=0){mode='race';noticeUntil=elapsed+1.1;$('notice').textContent='W / ↑ — ГАЗ · ПРОБЕЛ — ДРИФТ';}}
if(mode==='race'){simulationDebt+=dt;while(simulationDebt>=1/120&&!state.finished){C.step(state,getInput(),1/120);simulationDebt-=1/120;}if(state.events.length){showNotice(state.events[state.events.length-1]);state.events.length=0;}if(state.time>1)$('countdown').textContent='';if(state.finished)finishRace();}
if(running||mode==='menu'){placeKarts(dt);for(let i=0;i<pickupMeshes.length;i++)for(let j=0;j<3;j++){const m=pickupMeshes[i][j];m.visible=state.pickups[i].cooldown===0;m.rotation.set(.15,elapsed*1.3+j,.12);m.position.y=sample(state.pickups[i].d).p.y+1.6+Math.sin(elapsed*2+j)*.2;}for(const p of particles){if(p.life>0){p.life-=dt;p.m.position.addScaledVector(p.v,dt);p.v.y-=7*dt;p.m.visible=p.life>0;}}}
updateEffects();updateAtmosphere(dt);if(mode==='menu'||running||mode==='finish')updateCamera(dt);if(elapsed>noticeUntil)$('notice').textContent='';if(engineGain){engineGain.gain.setTargetAtTime(soundOn&&mode==='race'?.026:0,audio.currentTime,.08);engine.frequency.setTargetAtTime(45+state.racers[0].speed*2.2,audio.currentTime,.06);}uiClock+=dt;if(uiClock>.05&&running){updateHUD();uiClock=0;}renderer.render(scene,camera);}
placeKarts(0);updateCamera(1);renderer.render(scene,camera);requestAnimationFrame(animate);
})();
