/* Дикий дрифт — all assets and code run directly from disk. */
(function(){
'use strict';
const $=id=>document.getElementById(id),C=window.RaceCore;
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas:$('game'),antialias:true,powerPreference:'high-performance'});}catch(error){$('error').classList.remove('hidden');$('menu').classList.add('hidden');return;}
renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.75));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;
const scene=new THREE.Scene();scene.background=new THREE.Color(0xb6dee1);scene.fog=new THREE.Fog(0xc4e1df,220,950);
const camera=new THREE.PerspectiveCamera(57,innerWidth/innerHeight,.15,1200);
const hemi=new THREE.HemisphereLight(0xb6b1c9,0x333b42,1.65);scene.add(hemi);
const sun=new THREE.DirectionalLight(0xffe5c9,2.8);sun.position.set(-70,140,45);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-75,right:75,top:75,bottom:-75,near:1,far:320});sun.shadow.bias=-.0008;sun.shadow.normalBias=.08;scene.add(sun);scene.add(sun.target);
const mats={};function mat(color,extra={}){const key=String(color)+JSON.stringify(extra);return mats[key]||(mats[key]=new THREE.MeshStandardMaterial({color,roughness:.78,...extra}));}
function mesh(geo,color,x=0,y=0,z=0,parent=scene,shadow=false){const m=new THREE.Mesh(geo,typeof color==='number'?mat(color):color);m.position.set(x,y,z);m.castShadow=shadow;m.receiveShadow=true;parent.add(m);return m;}
const unitBox=new THREE.BoxGeometry(1,1,1),unitSphere=new THREE.SphereGeometry(1,32,24);
function box(w,h,d,color,x,y,z,parent=scene,shadow=false){const m=mesh(unitBox,color,x,y,z,parent,shadow);m.scale.set(w,h,d);return m;}
function ellipsoid(x,y,z,sx,sy,sz,color,parent=scene,shadow=false){const m=mesh(unitSphere,color,x,y,z,parent,shadow);m.scale.set(sx,sy,sz);return m;}
const roundedGeometries={};
function smoothNormals(geo){const p=geo.attributes.position,n=geo.attributes.normal,groups=new Map();for(let i=0;i<p.count;i++){const key=[p.getX(i),p.getY(i),p.getZ(i)].map(x=>Math.round(x*1e5)).join(',');if(!groups.has(key))groups.set(key,{v:new THREE.Vector3(),indices:[]});const g=groups.get(key);g.v.add(new THREE.Vector3(n.getX(i),n.getY(i),n.getZ(i)));g.indices.push(i);}for(const g of groups.values()){g.v.normalize();for(const i of g.indices)n.setXYZ(i,g.v.x,g.v.y,g.v.z);}return geo;}
function softBox(w,h,d,color,x,y,z,parent,shadow){
 const key=[w,h,d].join(',');if(!roundedGeometries[key]){const bevel=Math.min(w,h,d)*.16,a=w/2-bevel,b=h/2-bevel,r=Math.min(a,b)*.7,shape=new THREE.Shape();shape.moveTo(-a+r,-b);shape.lineTo(a-r,-b);shape.quadraticCurveTo(a,-b,a,-b+r);shape.lineTo(a,b-r);shape.quadraticCurveTo(a,b,a-r,b);shape.lineTo(-a+r,b);shape.quadraticCurveTo(-a,b,-a,b-r);shape.lineTo(-a,-b+r);shape.quadraticCurveTo(-a,-b,-a+r,-b);const geo=new THREE.ExtrudeGeometry(shape,{depth:d-2*bevel,bevelEnabled:true,bevelThickness:bevel,bevelSize:bevel,bevelSegments:5,steps:1,curveSegments:10});geo.translate(0,0,-d/2+bevel);roundedGeometries[key]=smoothNormals(geo);}return mesh(roundedGeometries[key],color,x,y,z,parent,shadow);
}
function sculptedShell(profile,material,parent){
 const curve=new THREE.CatmullRomCurve3(profile.map(p=>new THREE.Vector3(...p))),vertices=[],uv=[],indices=[],rows=48,sides=40;
 for(let i=0;i<=rows;i++){const p=curve.getPoint(i/rows),w=Math.max(.008,p.x);for(let j=0;j<=sides;j++){const a=j/sides*Math.PI*2;vertices.push(Math.sin(a)*w,p.y+Math.cos(a)*w*.32,p.z);uv.push(j/sides,i/rows);}}
 for(let i=0;i<rows;i++)for(let j=0;j<sides;j++){const a=i*(sides+1)+j,b=a+sides+1;indices.push(a,b,a+1,b,b+1,a+1);}
 const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));geo.setIndex(indices);geo.computeVertexNormals();smoothNormals(geo);const result=mesh(geo,material,0,0,0,parent,true);result.name='sculpted-coachwork';return result;
}
// A tiled height/roughness map gives the road stone joints and small surface pits.
const stoneCanvas=document.createElement('canvas');stoneCanvas.width=stoneCanvas.height=256;const stoneCtx=stoneCanvas.getContext('2d');stoneCtx.fillStyle='#555';stoneCtx.fillRect(0,0,256,256);for(let row=0;row<8;row++)for(let col=-1;col<5;col++){const shade=155+((row*37+col*71+256)%54);stoneCtx.fillStyle='rgb('+shade+','+shade+','+shade+')';stoneCtx.fillRect(col*64+(row%2)*32+2,row*32+2,60,28);}const stoneTexture=new THREE.CanvasTexture(stoneCanvas);stoneTexture.wrapS=stoneTexture.wrapT=THREE.RepeatWrapping;
let track=window.RaceTracks[0],length=track.length,distances=[],samples=[],N=0,world=null,reflection=null,pickupMeshes=[],torchAnchors=[];
const up=new THREE.Vector3(0,1,0);
function sample(d,lane=0){const s=track.sample(d,lane);return {p:new THREE.Vector3(s.x,s.y,s.z),t:new THREE.Vector3(s.tx,s.slope,s.tz).normalize(),right:new THREE.Vector3(-s.tz,0,s.tx),...s};}
function label(text,bg,fg,w=512,h=128){const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.fillStyle=fg;ctx.font=`600 ${h*.48}px Georgia`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,w/2,h*.53);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide});}
function disposeGroup(group){if(!group)return;const shared=new Set([unitBox,unitSphere,...Object.values(roundedGeometries)]),cached=new Set(Object.values(mats));group.traverse(o=>{if(o.geometry&&!shared.has(o.geometry))o.geometry.dispose();for(const m of o.material?(Array.isArray(o.material)?o.material:[o.material]):[]){if(!cached.has(m)){if(m.map&&!permanentTextures.has(m.map))m.map.dispose();m.dispose();}}});group.removeFromParent();}
function clearOfRoad(x,z,radius,minY,maxY){
 for(const seg of track.segments){const along=C.clamp((x-seg.a.x)*seg.tx+(z-seg.a.z)*seg.tz,0,seg.len),dx=x-seg.a.x-seg.tx*along,dz=z-seg.a.z-seg.tz*along;if(dx*dx+dz*dz>(track.width+radius+1)**2)continue;const p=track.sample(seg.d+along,(dx*-seg.tz+dz*seg.tx));if(p.ground&&p.y<=maxY+.15&&p.y+4>=minY)return false;}return true;
}
function buildWorld(index){
 disposeGroup(world);ambience={flags:[],flames:[],trees:[],mist:[],birds:[],weather:null,embers:null,liquid:null};const existing=new Set(scene.children);track=window.RaceTracks[index];length=track.length;const theme=track.meta;
 scene.background=new THREE.Color(theme.sky);scene.fog=new THREE.Fog(theme.fog,32,index===2?260:340);sun.color.setHex(theme.light);sun.intensity=index===1?2.4:2.9;hemi.color.setHex(index===0?0xc4b6cb:index===1?0x91b7aa:0xb1c6f0);hemi.groundColor.setHex(theme.stone);
 distances=[...Array.from({length:1501},(_,i)=>i/1500*length),...track.gaps.flatMap(g=>[g.start-22,g.start,g.end,g.end+24])].sort((a,b)=>a-b);samples=distances.map(d=>sample(d));N=samples.length-1;torchAnchors=[];
 function strip(lo,hi,lift,colors,land=false){const verts=[],cols=[],uvs=[],lanes=Math.ceil((hi-lo)/1.5);for(let i=0;i<N;i++){const mid=(distances[i]+distances[i+1])/2;if(track.gapAt(mid)||(land&&track.bridgeAt(mid)))continue;const color=new THREE.Color(colors[Math.floor(distances[i]/5)%colors.length]);for(let j=0;j<lanes;j++){const left=lo+(hi-lo)*j/lanes,right=lo+(hi-lo)*(j+1)/lanes;for(const [d,w] of [[distances[i],left],[distances[i+1],left],[distances[i],right],[distances[i],right],[distances[i+1],left],[distances[i+1],right]]){const p=track.sample(d,w);verts.push(p.x,p.y+lift,p.z);cols.push(color.r,color.g,color.b);uvs.push(w/4,d/5);}}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setAttribute('color',new THREE.Float32BufferAttribute(cols,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));g.computeVertexNormals();const m=mesh(g,new THREE.MeshStandardMaterial({vertexColors:true,map:stoneTexture,bumpMap:stoneTexture,bumpScale:.09,roughnessMap:stoneTexture,roughness:land?.85:.56,metalness:land?0:.32,side:THREE.DoubleSide}));m.name='track-strip';return m;}

 const waterMaterial=new THREE.MeshStandardMaterial({color:theme.liquid,roughness:.19,metalness:.55,bumpMap:waterTexture,bumpScale:.3});waterTexture.repeat.set(70,70);const liquid=mesh(new THREE.PlaneGeometry(2800,2800),waterMaterial,0,-64,0);liquid.rotation.x=-Math.PI/2;ambience.liquid=liquid;
 strip(-11.25,11.25,-.14,[theme.stone],true);strip(-9.45,9.45,0,[theme.road,theme.road,new THREE.Color(theme.road).multiplyScalar(1.035).getHex()]);strip(-9.95,-9.4,.025,[theme.stone,theme.accent]);strip(9.4,9.95,.025,[theme.stone,theme.accent]);
 for(const side of [-1,1]){const verts=[];for(let i=0;i<N;i++){if(track.bridgeAt((distances[i]+distances[i+1])/2))continue;const a=samples[i],b=samples[i+1],top=s=>[s.p.x+s.right.x*side*11.25,track.sample(s.d,side*11.25).y-.12,s.p.z+s.right.z*side*11.25],bottom=s=>[s.p.x+s.right.x*side*11.25,track.sample(s.d,side*11.25).y-2.8,s.p.z+s.right.z*side*11.25];for(const p of [top(a),bottom(a),top(b),top(b),bottom(a),bottom(b)])verts.push(...p);}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));geo.computeVertexNormals();mesh(geo,mat(theme.stone,{side:THREE.DoubleSide,roughness:.87}));}
 let seed=824+index*977;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
 function spire(x,y,z,size=1){const g=new THREE.Group();g.position.set(x,y,z);g.scale.setScalar(size);scene.add(g);mesh(new THREE.CylinderGeometry(1.3,2,13,8),mat(theme.stone,{roughness:.7}),0,6,0,g,true);mesh(new THREE.ConeGeometry(2,7,8),mat(0x272d37,{metalness:.45,roughness:.38}),0,15.8,0,g,true);for(const h of [2,7,12]){mesh(new THREE.TorusGeometry(1.45,.12,5,8),0x817868,0,h,0,g).rotation.x=Math.PI/2;}box(.28,3,.12,mat(theme.accent,{emissive:theme.accent,emissiveIntensity:1.6}),0,9,1.42,g);bakeStatic(g);}
 function tree(x,y,z,size){const g=new THREE.Group();g.position.set(x,y,z);g.scale.setScalar(size);scene.add(g);ambience.trees.push(g);mesh(new THREE.CylinderGeometry(.18,.7,10,7),0x303d3a,0,5,0,g);for(let j=0;j<5;j++){const limb=mesh(new THREE.CylinderGeometry(.04,.19,5,5),0x3a4840,0,6+j*.8,0,g);limb.rotation.z=(j%2?1:-1)*.75;limb.rotation.y=j*1.7;}if(index===1)for(let j=0;j<3;j++)ellipsoid((rand()-.5)*3,9+j*1.4,0,2.8,1.9,2.3,0x3a5950,g);bakeStatic(g);}
 function crystal(x,y,z,size){const c=mesh(new THREE.ConeGeometry(size*.4,size*2.7,5),mat(0x9fbacc,{metalness:.3,roughness:.17,emissive:0x344a6c,emissiveIntensity:.8}),x,y+size,z);c.rotation.z=.16;}
 for(let i=0;i<50;i++){const d=i/50*length;if(track.bridgeAt(d))continue;const s=sample(d,(i%2?1:-1)*(19+rand()*7));if(!clearOfRoad(s.x,s.z,4,s.y-5,s.y+30))continue;ellipsoid(s.p.x,s.p.y-2,s.p.z,4,2.6,4,theme.stone);if(index===0||index===3)spire(s.p.x,s.p.y,s.p.z,.5+rand()*.5);else if(index===1||index===4)tree(s.p.x,s.p.y,s.p.z,.9+rand()*.6);else crystal(s.p.x,s.p.y,s.p.z,2+rand()*3);}
 for(let i=0;i<64;i++){const d=i/64*length;if(track.bridgeAt(d))continue;const s=sample(d,i%2?12.4:-12.4);if(!clearOfRoad(s.x,s.z,.1,s.y+.2,s.y+4.5))continue;strut([s.p.x,s.p.y,s.p.z],[s.p.x,s.p.y+2,s.p.z],.13,armour,scene);brazier(s);mesh(new THREE.CylinderGeometry(.55,.3,.4,16),armour,s.p.x,s.p.y+1.99,s.p.z);for(const side of [-1,1])strut([s.p.x+side*.38,s.p.y+2,s.p.z],[s.p.x+side*.55,s.p.y+2.55,s.p.z],.04,brass,scene);}
 // Cathedral silhouettes and broken arches sit beyond the driving surface.
 gothicWorld(theme,index,rand);buildFences();
 for(let i=0;i<12;i++){const a=i*2.4;ellipsoid(Math.cos(a)*490,-20,Math.sin(a)*490,70,80+rand()*65,70,theme.stone);}
 const moon=ellipsoid(-280,260,-500,24,24,24,new THREE.MeshBasicMaterial({color:index===0?0xeac991:0xc0d5ee,fog:false}));
 for(const gap of track.gaps)for(const d of [gap.start-25,gap.end+25]){const s=sample(d),g=new THREE.Group();g.position.copy(s.p);g.rotation.y=Math.atan2(s.tx,s.tz);scene.add(g);for(const x of [-10.8,10.8]){box(1,12,1,theme.stone,x,5,0,g,true);mesh(new THREE.ConeGeometry(1.1,3,5),theme.stone,x,12,0,g);}box(23,.5,1,theme.stone,0,11,0,g);if(d<gap.start)box(7,1.5,.15,label('↗ '+Math.round(gap.end-gap.start)+' м','#25292e','#d7bf91'),0,9.8,0,g);}
 for(let d=190;d<length;d+=95){if(track.bridgeAt(d))continue;const a=sample(d),b=sample(d+32),turn=C.angle(Math.atan2(b.tx,b.tz)-Math.atan2(a.tx,a.tz));if(Math.abs(turn)<.24)continue;const s=sample(d,Math.sign(turn)*13);if(!clearOfRoad(s.x,s.z,1.4,s.y,s.y+3.5))continue;const g=new THREE.Group();g.position.copy(s.p);g.rotation.y=Math.atan2(a.tx,a.tz);scene.add(g);box(.2,2.5,.2,theme.stone,0,1,0,g);box(3.2,1,.1,label(turn>0?'‹ ‹ ‹':'› › ›','#262e32','#d3c09a'),0,2.3,0,g);}
 const start=sample(0),arch=new THREE.Group();arch.position.copy(start.p);arch.rotation.y=Math.atan2(start.tx,start.tz);scene.add(arch);for(const x of [-10.8,10.8]){box(1.4,13,1.4,theme.stone,x,6,0,arch,true);mesh(new THREE.ConeGeometry(1.5,4,6),theme.stone,x,14,0,arch);}box(24,2.3,1.4,mat(0x4a4644,{metalness:.35}),0,11.5,0,arch);box(19,1.55,1.42,label('ASHEN COVENANT','#343337','#d7ba86'),0,11.5,0,arch);
 for(let j=0;j<20;j++)for(let k=0;k<3;k++)box(.9,.03,.8,(j+k)%2?0xb6aaa0:0x34393f,(j-9.5)*.9,.08,k*.8-1,arch);
 for(const d of track.pads){const s=sample(d),g=new THREE.Group();g.position.copy(s.p);g.rotation.set(-Math.atan(s.slope),Math.atan2(s.tx,s.tz),0,'YXZ');scene.add(g);box(9,.03,5,mat(0x34333c,{metalness:.5,roughness:.25}),0,.06,0,g);for(let k=0;k<3;k++){const rune=mesh(new THREE.TorusGeometry(.75,.035,4,4),mat(theme.accent,{emissive:theme.accent,emissiveIntensity:2}),0,.1,(k-1)*1.5,g);rune.rotation.x=Math.PI/2;}}
 // Small wet patches use the scene reflection map, not a painted highlight.
 for(let i=0;i<40;i++){const d=(i+.3)/40*length;if(track.bridgeAt(d))continue;const s=sample(d,Math.sin(i*2)*5),patch=mesh(new THREE.CircleGeometry(1.2+i%3*.5,18),mat(theme.road,{metalness:.78,roughness:.08,transparent:true,opacity:.38,depthWrite:false}),s.p.x,s.p.y+.027,s.p.z);patch.rotation.set(-Math.PI/2-Math.atan(s.slope),Math.atan2(s.tx,s.tz),0,'YXZ');patch.scale.y=.55;}
 pickupMeshes=[];const runeMat=mat(theme.accent,{emissive:theme.accent,emissiveIntensity:1.4,metalness:.45,roughness:.2});for(const d of track.pickups){const row=[];for(const lane of [-5,0,5]){const s=sample(d,lane),m=mesh(new THREE.OctahedronGeometry(.92),runeMat,s.p.x,s.p.y+1.7,s.p.z);m.name='pickup';row.push(m);}pickupMeshes.push(row);}
 world=new THREE.Group();world.name='course';for(const child of [...scene.children])if(!existing.has(child))world.add(child);scene.add(world);
 // ponytail: one local environment capture per course; continuous reflections would need a lower-cost reflection pass.
 if(renderer.getContext){scene.environment=null;reflection?.dispose();const cube=new THREE.WebGLCubeRenderTarget(128,{type:THREE.HalfFloatType}),capture=new THREE.CubeCamera(.1,900,cube),s=sample(0);capture.position.set(s.p.x,s.p.y+5,s.p.z);capture.update(renderer,scene);const pmrem=new THREE.PMREMGenerator(renderer);reflection=pmrem.fromCubemap(cube.texture);scene.environment=reflection.texture;cube.dispose();pmrem.dispose();}
}
// Cover motifs are modelled as geometry: a pointed bonnet, exposed brass frame,
// articulated armour, animal muzzles and wind-driven fabric.
function tube(points,radius,material,parent){return mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p))),Math.min(96,Math.max(8,points.length*5)),radius,12,false),material,0,0,0,parent);}
function strut(a,b,radius,material,parent){const av=new THREE.Vector3(...a),bv=new THREE.Vector3(...b),m=mesh(new THREE.CylinderGeometry(radius,radius,av.distanceTo(bv),16),material,0,0,0,parent);m.position.copy(av).add(bv).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),bv.sub(av).normalize());return m;}
function bakeStatic(group){
 // Batch ornamental geometry by material; wheels, heads and cloth stay separate.
 group.updateMatrixWorld(true);const inverse=group.matrixWorld.clone().invert(),batches=new Map(),shared=new Set([unitBox,unitSphere,...Object.values(roundedGeometries)]);
 group.traverse(o=>{if(!o.isMesh)return;const geo=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();geo.applyMatrix4(inverse.clone().multiply(o.matrixWorld));let batch=batches.get(o.material);if(!batch){batch={position:[],normal:[],uv:[],shadow:false};batches.set(o.material,batch);}for(const name of ['position','normal','uv']){const attr=geo.getAttribute(name);if(attr)batch[name].push(...attr.array);else for(let i=0;i<geo.attributes.position.count*(name==='uv'?2:3);i++)batch[name].push(0);}batch.shadow ||= o.castShadow;geo.dispose();if(!shared.has(o.geometry))o.geometry.dispose();});
 group.clear();for(const [material,b] of batches){const geo=new THREE.BufferGeometry();for(const name of ['position','normal','uv'])geo.setAttribute(name,new THREE.Float32BufferAttribute(b[name],name==='uv'?2:3));mesh(geo,material,0,0,0,group,b.shadow);}return group;
}
function grainTexture(kind){const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const ctx=canvas.getContext('2d');ctx.fillStyle=kind==='fur'?'#a09c91':'#aaa';ctx.fillRect(0,0,256,256);let seed=619;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<3500;i++){const x=rand()*256,y=rand()*256,shade=75+Math.floor(rand()*135);ctx.strokeStyle='rgb('+shade+','+shade+','+shade+')';ctx.lineWidth=kind==='fur'?.7:.35;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+(kind==='fur'?(rand()-.5)*4:rand()*14),y+(kind==='fur'?5+rand()*15:rand()*2));ctx.stroke();}const texture=new THREE.CanvasTexture(canvas);texture.wrapS=texture.wrapT=THREE.RepeatWrapping;return texture;}
const metalGrain=grainTexture('metal'),furGrain=grainTexture('fur');
const armour=mats.armour=new THREE.MeshStandardMaterial({color:0x4b5660,metalness:.7,roughness:.28,bumpMap:metalGrain,bumpScale:.022});
const brass=mats.brass=new THREE.MeshStandardMaterial({color:0xa88b55,metalness:.84,roughness:.32,bumpMap:metalGrain,bumpScale:.013});
function cloth(width,height,color,parent,cape=false){
 const geo=new THREE.PlaneGeometry(width,height,12,16),position=geo.attributes.position;for(let i=0;i<position.count;i++){const x=position.getX(i),y=position.getY(i),v=(height/2-y)/height;position.setY(i,-v*height+(v>.87?Math.sin(x*29)*height*.045:0));if(cape)position.setZ(i,-v*height*.6);}if(cape){const indices=[];for(let i=0;i<geo.index.count;i+=3){const face=[geo.index.getX(i),geo.index.getX(i+1),geo.index.getX(i+2)];const y=face.reduce((n,j)=>n+position.getY(j),0)/3;if(y>-.56||Math.min(...face.map(j=>Math.abs(position.getX(j))))>.4)indices.push(...face);}geo.setIndex(indices);}geo.computeVertexNormals();
 const material=new THREE.MeshStandardMaterial({color,roughness:1,side:THREE.DoubleSide,bumpMap:furGrain,bumpScale:.008});const m=mesh(geo,material,0,0,0,parent,true);m.name=cape?'wind-cape':'wind-banner';m.userData.base=new Float32Array(position.array);m.userData.height=height;m.userData.cape=cape;return m;
}
// ponytail: analytic cloth waves keep this offline; cloth collisions would require a cloth solver.
function waveCloth(m,time,wind){const a=m.geometry.attributes.position,base=m.userData.base,h=m.userData.height;for(let i=0;i<a.count;i++){const x=base[i*3],y=base[i*3+1],z=base[i*3+2],v=Math.max(0,-y/h),wave=Math.sin(time*3.5+x*3-v*4)*.075+Math.sin(time*5.3-v*8)*.035;a.setXYZ(i,x+Math.sin(time*1.7+v*3)*v*.06,y+Math.sin(time*2.1+x*2)*v*.025,z+v*(wave*wind-(m.userData.cape?wind*.12:0)));}a.needsUpdate=true;m.geometry.computeVertexNormals();}
function makeMistTexture(){const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const ctx=canvas.getContext('2d'),gradient=ctx.createRadialGradient(64,64,3,64,64,64);gradient.addColorStop(0,'rgba(205,216,220,.5)');gradient.addColorStop(.4,'rgba(180,197,205,.2)');gradient.addColorStop(1,'rgba(155,175,184,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,128,128);return new THREE.CanvasTexture(canvas);}
const mistTexture=makeMistTexture(),waterTexture=grainTexture('water');
function particleTexture(kind){const canvas=document.createElement('canvas');canvas.width=128;canvas.height=kind==='fire'?256:128;const ctx=canvas.getContext('2d');if(kind==='fire'){
 for(let i=0;i<7;i++){ctx.save();ctx.translate(64+Math.sin(i*2.6)*19,191-i*19);ctx.scale(44-i*4,57-i*3);const g=ctx.createRadialGradient(0,0,0,0,0,1);g.addColorStop(0,'rgba(255,249,199,1)');g.addColorStop(.24,'rgba(255,210,91,.97)');g.addColorStop(.6,'rgba(255,100,14,.75)');g.addColorStop(1,'rgba(220,30,0,0)');ctx.fillStyle=g;ctx.fillRect(-1,-1,2,2);ctx.restore();}
 }else{const g=ctx.createRadialGradient(64,64,0,64,64,62);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.24,'rgba(255,255,255,.95)');g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.fillRect(0,0,128,128);if(kind==='snow'){ctx.strokeStyle='rgba(255,255,255,.95)';ctx.lineWidth=5;ctx.lineCap='round';for(let i=0;i<6;i++){const a=i*Math.PI/3;ctx.beginPath();ctx.moveTo(64,64);ctx.lineTo(64+Math.cos(a)*46,64+Math.sin(a)*46);ctx.stroke();}}}
 const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return texture;
}
const fireTexture=particleTexture('fire'),snowTexture=particleTexture('snow'),emberTexture=particleTexture('ember');
const permanentTextures=new Set([stoneTexture,mistTexture,fireTexture,snowTexture,emberTexture]);
function brazier(s){const fire=new THREE.Group();fire.position.set(s.p.x,s.p.y+2.15,s.p.z);fire.name='torch-flame';scene.add(fire);const flame=new THREE.Sprite(new THREE.SpriteMaterial({map:fireTexture,transparent:true,depthWrite:false,opacity:.96,toneMapped:false,fog:false}));flame.scale.set(1.85,3.1,1);flame.position.y=1.04;fire.add(flame);const halo=new THREE.Sprite(new THREE.SpriteMaterial({map:emberTexture,color:0xff751f,transparent:true,opacity:.16,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false,fog:false}));halo.scale.set(4.4,4.4,1);halo.position.y=.8;fire.add(halo);ambience.flames.push(fire);torchAnchors.push(new THREE.Vector3(s.p.x,s.p.y+2.7,s.p.z));
}
function buildFences(){for(const fence of track.fences){const group=new THREE.Group();group.name='track-fence';group.userData.fence=fence;scene.add(group);const points=[],steps=Math.ceil((fence.end-fence.start)/3);for(let i=0;i<=steps;i++){const s=sample(fence.start+(fence.end-fence.start)*i/steps,fence.side*track.fenceLane);points.push(s);strut([s.p.x,s.p.y,s.p.z],[s.p.x,s.p.y+1.9,s.p.z],.075,armour,group);mesh(new THREE.ConeGeometry(.14,.32,8),brass,s.p.x,s.p.y+2.03,s.p.z,group);if(i%3===0){const foot=mesh(new THREE.CylinderGeometry(.22,.28,.36,12),armour,s.p.x,s.p.y+.18,s.p.z,group);}}
 for(const height of [.52,1.24,1.7])tube(points.map(s=>[s.p.x,s.p.y+height,s.p.z]),height===1.7?.07:.045,brass,group);for(let i=0;i<points.length-1;i++){const a=points[i],b=points[i+1];strut([a.p.x,a.p.y+.53,a.p.z],[b.p.x,b.p.y+1.22,b.p.z],.035,armour,group);}bakeStatic(group);}}
let ambience={flags:[],flames:[],trees:[],mist:[],birds:[],weather:null,embers:null,liquid:null};
function gothicWorld(theme,index,rand){
 const masonry=mat(theme.stone,{roughness:.83}),roof=mat(0x252c33,{roughness:.57,metalness:.32}),windowMat=mat(index===2?0x819bab:0xb08b59,{emissive:index===2?0x799dc2:0xe6a35a,emissiveIntensity:.7,roughness:.45});
 const buildings=new THREE.Group();scene.add(buildings);buildings.name='gothic-city';buildings.position.set((track.bounds.minX+track.bounds.maxX)/2,-12,track.bounds.minZ-150);
 function lancet(x,y,z,w,h,parent){const outline=[[x-w/2,y,z],[x-w/2,y+h*.63,z],[x,y+h,z],[x+w/2,y+h*.63,z],[x+w/2,y,z]];tube(outline,.16,masonry,parent);const shape=new THREE.Shape();shape.moveTo(-w*.33,0);shape.lineTo(-w*.33,h*.62);shape.lineTo(0,h*.88);shape.lineTo(w*.33,h*.62);shape.lineTo(w*.33,0);shape.closePath();mesh(new THREE.ShapeGeometry(shape),windowMat,x,y,z-.08,parent);strut([x,y,z+.04],[x,y+h*.85,z+.04],.055,roof,parent);}
 function tower(x,y,z,h,w,parent){const tower=new THREE.Group();tower.position.set(x,y,z);parent.add(tower);mesh(new THREE.CylinderGeometry(w*.42,w*.52,h,8),masonry,0,h/2,0,tower,true);mesh(new THREE.ConeGeometry(w*.69,h*.34,8),roof,0,h*1.17,0,tower,true);for(const level of [.24,.58,.87]){mesh(new THREE.CylinderGeometry(w*.55,w*.55,.8,8),masonry,0,h*level,0,tower);lancet(0,h*level+.8,w*.46,w*.3,h*.16,tower);}for(const side of [-1,1])box(w*.11,h*.88,w*.72,masonry,side*w*.45,h*.44,0,tower,true);strut([0,h*1.31,0],[0,h*1.46,0],.12,roof,tower);}
 // A cathedral above a crag, with flying buttresses, lancet windows and clustered towers.
 const cathedral=new THREE.Group();cathedral.position.set(0,6,0);buildings.add(cathedral);
 const rockGeo=new THREE.IcosahedronGeometry(1,2),positions=rockGeo.attributes.position;for(let i=0;i<positions.count;i++){const scale=.86+rand()*.22;positions.setXYZ(i,positions.getX(i)*scale,positions.getY(i)*scale,positions.getZ(i)*scale);}rockGeo.computeVertexNormals();const rock=mesh(rockGeo,masonry,0,-16,0,cathedral);rock.scale.set(72,53,65);
 box(37,55,63,masonry,0,34,0,cathedral,true);const roofShape=new THREE.Shape();roofShape.moveTo(-21,0);roofShape.lineTo(0,21);roofShape.lineTo(21,0);roofShape.closePath();mesh(new THREE.ExtrudeGeometry(roofShape,{depth:66,bevelEnabled:false}),roof,0,61,-33,cathedral,true);
 for(const side of [-1,1])for(let i=0;i<5;i++){const z=-26+i*13;box(2.2,49,2.8,masonry,side*24,24,z,cathedral,true);tube([[side*24,39,z],[side*22,47,z],[side*17,52,z]],.9,masonry,cathedral);tower(side*24,49,z,6,2.2,cathedral);}
 for(const x of [-12,0,12])lancet(x,28,31.62,7,26,cathedral);const rose=mesh(new THREE.TorusGeometry(6,.55,7,32),masonry,0,67,33,cathedral);mesh(new THREE.CircleGeometry(5.3,24),windowMat,0,67,32.9,cathedral);for(let j=0;j<10;j++){const a=j/10*Math.PI*2;strut([0,67,33.05],[Math.cos(a)*5.4,67+Math.sin(a)*5.4,33.05],.14,roof,cathedral);}
 tower(-27,0,29,88,13,cathedral);tower(27,0,29,101,14,cathedral);tower(0,57,-17,72,10,cathedral);
 for(let i=0;i<9;i++){const a=i/9*Math.PI*2;tower(Math.cos(a)*65,-10,Math.sin(a)*55,28+rand()*32,7+rand()*5,buildings);}

 if(index===0){const bark=mat(0x665a42,{roughness:.82}),aether=mat(0xb2a477,{emissive:0xe9ce87,emissiveIntensity:1.6,roughness:.7});tube([[-91,-27,-30],[-94,5,-28],[-91,27,-31],[-96,47,-32]],1.6,bark,buildings);for(let i=0;i<12;i++){const a=i/12*Math.PI*2,x=-92+Math.cos(a)*(12+i%3*4),z=-30+Math.sin(a)*(10+i%2*4),y=42+i%4*3;tube([[-93,21,-30],[-93+Math.cos(a)*7,34,-30+Math.sin(a)*5],[x,y,z],[x+Math.cos(a)*5,y+7,z+Math.sin(a)*4]],.25,aether,buildings);}}
 bakeStatic(buildings);
 // Monument plinths stay clear of every road layer, including the road under a bridge.
 const roadside=new THREE.Group();roadside.name='track-statues';scene.add(roadside);
 for(let d=35;d<length;d+=78){if(track.bridgeAt(d))continue;const p=sample(d,Math.floor(d/78)%2?15.2:-15.2);if(!clearOfRoad(p.x,p.z,2.4,-64,p.y+9))continue;const g=new THREE.Group();g.name='statue-'+theme.id;g.position.copy(p.p);g.rotation.y=Math.atan2(p.tx,p.tz)+Math.PI;roadside.add(g);
  const stone=mat(new THREE.Color(theme.stone).multiplyScalar(1.35).getHex(),{roughness:.66,metalness:.12}),rune=mat(theme.accent,{emissive:theme.accent,emissiveIntensity:.9,metalness:.5});
  mesh(new THREE.CylinderGeometry(1.25,2,p.y+64,12),masonry,0,-(p.y+64)/2-.3,0,g,true);mesh(new THREE.CylinderGeometry(1.28,1.6,.85,12),stone,0,.18,0,g,true);mesh(new THREE.CylinderGeometry(1.13,1.28,.24,16),brass,0,.72,0,g);mesh(new THREE.CylinderGeometry(.48,.96,2.4,24),stone,0,2,0,g,true);ellipsoid(0,3.37,0,.62,.79,.42,stone,g,true);ellipsoid(0,4.42,.04,.42,.52,.38,stone,g,true);
  for(const side of [-1,1]){ellipsoid(side*.63,3.58,0,.39,.29,.44,stone,g,true);strut([side*.61,3.6,0],[side*.82,2.75,.22],.2,stone,g);ellipsoid(side*.82,2.7,.2,.23,.22,.22,stone,g);mesh(new THREE.OctahedronGeometry(.105,1),rune,side*.17,4.52,.382,g);}
  if(index===0){strut([.82,.88,.32],[.82,4.68,.32],.095,brass,g);strut([.4,3.37,.32],[1.25,3.37,.32],.08,brass,g);const shield=mesh(new THREE.SphereGeometry(.73,24,20),stone,-.86,2.68,.4,g);shield.scale.set(.75,1.25,.18);mesh(new THREE.TorusGeometry(.38,.045,8,24),brass,-.86,2.7,.58,g);}
  if(index===1){for(const side of [-1,1]){tube([[side*.28,4.66,0],[side*.54,5.3,-.05],[side*.7,5.9,-.13]],.12,stone,g);for(let j=0;j<3;j++)strut([side*(.4+j*.1),5+j*.24,0],[side*(.76+j*.13),5.17+j*.28,0],.07,stone,g);}}
  if(index===2){for(const side of [-1,1])for(let j=0;j<7;j++){const feather=ellipsoid(side*(.66+j*.13),3.3+j*.17,-.3,.17,.96-j*.04,.18,stone,g);feather.rotation.z=-side*(.2+j*.07);}mesh(new THREE.TorusGeometry(.66,.06,10,48),rune,0,4.71,-.17,g);}
  if(index===3){strut([.82,1.06,.28],[.82,4.74,.28],.15,brass,g);softBox(1.55,.75,.77,stone,.82,4.72,.28,g,true);for(const side of [-1,1])ellipsoid(side*.34,4.9,0,.24,.24,.16,stone,g);}
  if(index===4){const hood=mesh(new THREE.SphereGeometry(.6,32,24),stone,0,4.47,-.14,g);hood.scale.set(1,1.35,.7);strut([.87,.93,.28],[.87,5.19,.28],.08,brass,g);for(const x of [.52,.87,1.22]){strut([.87,4.57,.28],[x,4.89,.28],.06,brass,g);mesh(new THREE.ConeGeometry(.12,.65,16),rune,x,5.14,.28,g);}}
  bakeStatic(g);
 }
 for(const crossing of track.overpasses){const bridge=new THREE.Group();bridge.name='overpass-piers';scene.add(bridge);for(const offset of [-36,36])for(const side of [-1,1]){const p=sample(crossing.upper+offset,side*13.5),top=p.y-2.9;if(!clearOfRoad(p.x,p.z,2,-64,top))continue;mesh(new THREE.CylinderGeometry(1.55,2.5,top+64,16),masonry,p.x,(top-64)/2,p.z,bridge,true);mesh(new THREE.CylinderGeometry(2.05,1.6,1.3,16),masonry,p.x,top-.65,p.z,bridge,true);}bakeStatic(bridge);}

 for(let d=38;d<length;d+=125){if(track.bridgeAt(d))continue;const s=sample(d,Math.floor(d/125)%2?15.8:-15.8);if(!clearOfRoad(s.x,s.z,2.5,s.y,s.y+10))continue;const pole=new THREE.Group();pole.position.copy(s.p);pole.rotation.y=Math.atan2(s.tx,s.tz);scene.add(pole);strut([0,0,0],[0,8.7,0],.075,roof,pole);strut([-.2,8.2,0],[2.4,8.2,0],.065,roof,pole);const banner=cloth(2.2,3.6,index===0?0x58393a:index===1?0x3b5147:0x434e64,pole);banner.position.set(1.1,8.1,0);ambience.flags.push(banner);mesh(new THREE.ConeGeometry(.18,.7,4),brass,0,9,0,pole);}
 // Low banks sit on the driving surface and are visible from the chase camera.
 for(let i=0;i<48;i++){const s=sample((i+.4)/48*length,[-5,0,5][i%3]),sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:mistTexture,color:index===0?0xc2cbd0:0xd7e4e9,transparent:true,opacity:.42,depthWrite:false,fog:false}));sprite.name='road-mist';sprite.position.set(s.p.x,s.p.y+1.2+rand()*.8,s.p.z);sprite.scale.set(25+rand()*12,4.8+rand()*2.5,1);sprite.userData.base=sprite.position.clone();sprite.userData.phase=rand()*Math.PI*2;scene.add(sprite);ambience.mist.push(sprite);}
 for(let i=0;i<8;i++){const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:mistTexture,color:0x15232d,transparent:true,opacity:.65,depthWrite:false,fog:false}));sprite.position.set(Math.cos(i)*340,155+i%3*17,Math.sin(i)*340);sprite.scale.set(350,80,1);sprite.userData.base=sprite.position.clone();sprite.userData.phase=i;scene.add(sprite);ambience.mist.push(sprite);}
 for(let i=0;i<9;i++){const bird=new THREE.Group(),wings=[];scene.add(bird);ellipsoid(0,0,0,.13,.12,.36,mat(0x1c242a),bird);for(const side of [-1,1]){const wing=new THREE.Group();bird.add(wing);const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute([0,0,0,side*1.1,0,-.25,side*.5,0,.3],3));geometry.computeVertexNormals();mesh(geometry,mat(0x1b242c,{side:THREE.DoubleSide}),0,0,0,wing);wings.push(wing);}bird.scale.setScalar(1.4);bird.name='raven';ambience.birds.push({g:bird,wings,phase:i*1.72,radius:75+i*6});}
 const count=index===2?720:320,weatherGeometry=new THREE.BufferGeometry(),base=new Float32Array(count*3);for(let i=0;i<base.length;i++)base[i]=rand();weatherGeometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(base.length),3));const weather=new THREE.Points(weatherGeometry,new THREE.PointsMaterial({map:index===2?snowTexture:emberTexture,color:index===0?0xffcb87:index===1?0xd0e4c3:0xe5f3ff,size:index===2?.36:.2,transparent:true,opacity:index===2?.96:.8,alphaTest:.015,depthWrite:false,fog:false}));weather.frustumCulled=false;weather.name='airborne-particles';scene.add(weather);ambience.weather={mesh:weather,base};
 const emberGeo=new THREE.BufferGeometry();emberGeo.setAttribute('position',new THREE.BufferAttribute(new Float32Array(120*3),3));const embers=new THREE.Points(emberGeo,new THREE.PointsMaterial({map:emberTexture,color:0xffa843,size:.16,transparent:true,opacity:.95,depthWrite:false,blending:THREE.AdditiveBlending,toneMapped:false,fog:false}));embers.frustumCulled=false;embers.name='brazier-embers';scene.add(embers);ambience.embers=embers;

}
function updateLivingWorld(dt){
 const time=elapsed,calm=reducedMotion?.22:1,gust=(.8+Math.sin(time*.23)*.23+Math.sin(time*.071)*.2)*calm;
 for(const [i,flag] of ambience.flags.entries())waveCloth(flag,time+i*.83,gust*2);
 for(const [i,fire] of ambience.flames.entries()){fire.scale.set(1+Math.sin(time*11+i)*.09,1+Math.sin(time*8+i*2)*.14,1);fire.children[0].material.rotation=Math.sin(time*5+i)*.07;fire.children[1].material.opacity=.17+Math.sin(time*9+i)*.035;}
 for(const [i,tree] of ambience.trees.entries())tree.rotation.z=Math.sin(time*.7+i)*.015*gust;
 for(const cloud of ambience.mist){const b=cloud.userData.base,phase=cloud.userData.phase;cloud.position.x=b.x+Math.sin(time*.035+phase)*5*calm;cloud.position.z=b.z+Math.cos(time*.029+phase)*4*calm;cloud.material.opacity=(cloud.name==='road-mist'?.42:.57)+Math.sin(time*.045+phase)*.04;}
 for(const bird of ambience.birds){const a=time*.085+bird.phase;bird.g.position.set(Math.cos(a)*bird.radius,69+Math.sin(a*2)*7,Math.sin(a)*bird.radius);bird.g.rotation.y=-a;bird.g.rotation.z=Math.sin(a)*.12;bird.wings.forEach((wing,i)=>{wing.rotation.z=Math.sin(time*5+bird.phase)*(i===0?1:-1)*.65;});}
 const p=state.racers[0],weather=ambience.weather;if(weather){const a=weather.mesh.geometry.attributes.position,b=weather.base,fall=track.courseIndex===2?-3.2:track.courseIndex===1?-.5:.8;for(let i=0;i<a.count;i++){a.setXYZ(i,p.x+C.wrap(b[i*3]*64-p.x+time*1.2,64)-32,p.y+C.wrap(b[i*3+1]*22-p.y+time*fall,22)-3,p.z+C.wrap(b[i*3+2]*64-p.z+time*.6,64)-32);}a.needsUpdate=true;}
 if(ambience.embers){const a=ambience.embers.geometry.attributes.position,nearest=[...torchAnchors].sort((a,b)=>(a.x-p.x)**2+(a.y-p.y)**2+(a.z-p.z)**2-((b.x-p.x)**2+(b.y-p.y)**2+(b.z-p.z)**2)).slice(0,6);for(let i=0;i<a.count;i++){const source=nearest[i%nearest.length],t=C.wrap(time*.7+i*.173,1);a.setXYZ(i,source.x+Math.sin(i*2.4+t*3)*(.25+t*.6),source.y+t*3.7,source.z+Math.cos(i*1.7+t*2)*(.25+t*.6));}a.needsUpdate=true;}
 if(ambience.liquid){waterTexture.offset.set(time*.008,time*.013);ambience.liquid.material.roughness=.19+Math.sin(time*.08)*.025;}
 sun.intensity=(track.courseIndex===1?2.4:2.9)*(1+Math.sin(time*.039)*.055);scene.fog.near=32+Math.sin(time*.027)*4;scene.fog.far=(track.courseIndex===2?260:340)+Math.sin(time*.021)*16;
}
const carNames=['Пепельная стрела','Терновый бастион','Лунный серп','Крыло ворона','Рунный следопыт','Королевский рог','Молот титана','Эфирная игла'];
function kart(type,skin=0){
 const hero=C.DRIVERS[type],g=new THREE.Group(),body=new THREE.Group(),frame=new THREE.Group(),rider=new THREE.Group();g.add(body);body.add(frame,rider);g.name='hero-'+type;g.userData.skin=skin;g.userData.car=carNames[type];frame.name='car-body';
 const steel=armour,gold=brass,leather=mat(0x202126,{roughness:.95}),glow=mat(hero.glow,{emissive:hero.glow,emissiveIntensity:1.8,roughness:.28,metalness:.45});
 const lacquer=mats['lacquer-'+type]||(mats['lacquer-'+type]=new THREE.MeshPhysicalMaterial({color:new THREE.Color(hero.color).lerp(new THREE.Color(0x35434d),.48),metalness:.68,roughness:.27,clearcoat:.8,clearcoatRoughness:.2,bumpMap:metalGrain,bumpScale:.007}));
 const coat=[0x623634,0x36423b,0x565971,0x322d47,0x464e57,0x48533a,0x594435,0x594663][type];
 // Indexed, smoothly shaded closed sections replace the flat triangular bonnet.
 sculptedShell([[.04,.55,-1.42],[.62,.57,-1.22],[.81,.56,-.6],[.79,.55,.1],[.4,.5,1.2],[.03,.48,1.94]],steel,frame);
 const noses=[
 [[.08,.91,.12],[.67,.86,.3],[.64,.79,.67],[.48,.7,1.1],[.25,.6,1.69],[.025,.54,2.13]],
 [[.1,.82,.08],[.81,.85,.35],[.85,.81,1.05],[.73,.68,1.58],[.54,.56,1.73],[.03,.52,1.78]],
 [[.03,.72,.1],[.39,.73,.45],[.34,.66,.9],[.29,.6,1.55],[.12,.53,2.38],[.01,.51,2.6]],
 [[.05,.79,.08],[.56,.8,.36],[.4,.7,1.1],[.31,.65,1.9],[.1,.55,2.4],[.01,.5,2.7]],
 [[.03,.78,.08],[.6,.77,.27],[.66,.71,.7],[.59,.67,1.12],[.38,.56,1.72],[.03,.52,1.88]],
 [[.08,.85,.1],[.52,.89,.4],[.6,.79,.83],[.44,.73,1.18],[.23,.64,1.86],[.03,.52,2.17]],
 [[.1,.91,.1],[.9,.91,.34],[.92,.86,.96],[.86,.76,1.55],[.69,.59,1.8],[.04,.54,1.86]],
 [[.03,.8,.1],[.46,.91,.4],[.36,.81,.94],[.2,.65,1.9],[.06,.55,2.58],[.008,.51,2.8]]
 ];
 sculptedShell(noses[type],lacquer,frame);
 sculptedShell([[.03,.7,-1.61],[.49,.86,-1.44],[.65,.89,-1.16],[.46,.8,-.99],[.02,.68,-.94]],lacquer,frame);
 for(const side of [-1,1]){const pod=sculptedShell([[.02,.62,-1.29],[.22,.68,-.99],[.24,.69,-.5],[.16,.64,.04],[.02,.57,.35]],lacquer,frame);pod.position.x=side*.73;for(let j=0;j<4;j++){const vent=mesh(new THREE.CapsuleGeometry(.022,.2,4,8),gold,side*.76,.79,-.84+j*.14,frame);vent.rotation.z=Math.PI/2;}for(const z of [-1.13,.68]){const bolt=mesh(new THREE.SphereGeometry(.028,10,8),gold,side*.67,.82,z,frame);}}
 for(const side of [-1,1]){tube([[side*.75,.91,.2],[side*.59,.82,.68],[side*.3,.68,1.5],[side*.035,.57,2.13]],.025,gold,frame);tube([[side*.72,.51,-1.3],[side*.89,.46,-.4],[side*.94,.48,.65],[side*.42,.45,1.74],[0,.51,2.16]],.045,gold,frame);tube([[side*.77,.48,-1.2],[side*.81,1,-.65],[side*.7,1.12,.15],[side*.44,.67,1.45]],.038,gold,frame);
  for(const z of [-.95,.88]){strut([side*.35,.53,z-.3],[side*1.02,.54,z],.045,gold,frame);strut([side*.35,.52,z+.3],[side*1.02,.54,z],.04,gold,frame);const spring=[];for(let i=0;i<=70;i++){const t=i/70,a=t*Math.PI*12;spring.push([side*(.68+t*.28)+Math.cos(a)*.075,.95-t*.34,z+Math.sin(a)*.075]);}tube(spring,.022,steel,frame);}
  for(let j=0;j<3;j++){const z=.42+j*.38,scale=1-j*.19;tube([[side*.1,1.065-j*.105,z-.12],[side*.4*scale,1.02-j*.1,z],[side*.45*scale,.93-j*.1,z+.14],[side*.23*scale,1-j*.105,z+.2]],.012,gold,frame);}
  const engine=mesh(new THREE.CylinderGeometry(.21,.21,.65,16),steel,side*.69,.78,-.43,frame);engine.rotation.z=Math.PI/2;for(let i=0;i<3;i++){const ring=mesh(new THREE.TorusGeometry(.22,.035,6,16),gold,side*(.45+i*.2),.78,-.43,frame);ring.rotation.y=Math.PI/2;}ellipsoid(side*.78,.78,-.43,.1,.17,.17,glow,frame);
  tube([[side*.6,.75,-.65],[side*.78,.68,-1.05],[side*.78,.92,-1.54]],.085,steel,frame);mesh(new THREE.TorusGeometry(.09,.02,5,12),gold,side*.78,.94,-1.54,frame).rotation.x=Math.PI/2;
 }
 tube([[0,.941,.13],[0,1.081,.3],[0,.998,.67],[0,.858,1.1],[0,.685,1.69],[0,.551,2.13]],.018,gold,frame);
 const crest=mesh(new THREE.TorusGeometry(.17,.014,5,24),gold,0,.87,1.09,frame);crest.rotation.x=-Math.PI/2-.22;tube([[-.14,.96,1.1],[0,1,1.29],[.14,.96,1.1],[0,1,1.01],[-.14,.96,1.1]],.011,gold,frame);
 softBox(.96,.18,1.12,leather,0,.96,-.45,frame,true);softBox(.83,.65,.17,leather,0,1.3,-.98,frame,true);
 const width=[1.07,1.22,.94,1.13,1.19,1.08,1.27,1.01][type]*(skin===2?1.07:1),wheelbase=[1,1.07,1.19,1.2,1.13,1.04,1.1,1.25][type];
 const ws=[];for(const x of [-width,width])for(const z of (skin===2||type===6?[-1.27,-.35,1.04]:[-1,1.04]).map(z=>z*wheelbase)){
  const pivot=new THREE.Group(),rolling=new THREE.Group(),arch=new THREE.Group();pivot.position.set(x,.54,z);pivot.userData.front=z>0;body.add(pivot);pivot.add(rolling,arch);
  const outline=new THREE.CatmullRomCurve3([[.29,-.245,0],[.45,-.245,0],[.53,-.17,0],[.554,-.08,0],[.554,.08,0],[.53,.17,0],[.45,.245,0],[.29,.245,0]].map(p=>new THREE.Vector3(...p)));
  const tireGeo=new THREE.LatheGeometry(outline.getPoints(40).map(p=>new THREE.Vector2(p.x,p.y)),64);const tire=mesh(tireGeo,mat(0x20272b,{roughness:.86}),0,0,0,rolling,true);tire.rotation.z=Math.PI/2;
  for(const face of [-.249,.249]){const rim=mesh(new THREE.TorusGeometry(.38,.037,12,48),gold,face,0,0,rolling);rim.rotation.y=Math.PI/2;const brake=mesh(new THREE.CylinderGeometry(.27,.27,.025,40),steel,face*.76,0,0,rolling);brake.rotation.z=Math.PI/2;for(let j=0;j<8;j++){const a=j*Math.PI/4;tube([[face,Math.cos(a)*.09,Math.sin(a)*.09],[face+.02,Math.cos(a+.13)*.25,Math.sin(a+.13)*.25],[face,Math.cos(a+.24)*.35,Math.sin(a+.24)*.35]],.018,gold,rolling);}ellipsoid(face,0,0,.07,.105,.105,steel,rolling);}
  for(let j=0;j<32;j++){const a=j/32*Math.PI*2;for(const side of [-1,1]){const tread=mesh(new THREE.CapsuleGeometry(.01,.14,3,6),mat(0x384147,{roughness:.96}),side*.085,Math.cos(a)*.553,Math.sin(a)*.553,rolling);tread.rotation.set(Math.PI/2-a,0,side*.45);}}
  const archGeo=new THREE.TorusGeometry(.665,.085,16,56,Math.PI+.4);archGeo.rotateZ(-.2);archGeo.rotateY(Math.PI/2);const fender=mesh(archGeo,lacquer,0,0,0,arch,true);fender.scale.x=3.15;
  for(const side of [-1,1]){const pts=[];for(let j=0;j<=32;j++){const a=-.2+j/32*(Math.PI+.4);pts.push([side*.235,Math.sin(a)*.665,-Math.cos(a)*.665]);}tube(pts,.014,gold,arch);}
  if(skin===1){const cover=mesh(new THREE.SphereGeometry(.72,32,20,0,Math.PI*2,0,Math.PI/2),lacquer,0,0,0,arch,true);cover.scale.set(.44,1,1.13);for(const side of [-1,1])mesh(new THREE.TorusGeometry(.49,.022,8,32),gold,side*.29,0,0,arch).rotation.y=Math.PI/2;}
  bakeStatic(rolling);bakeStatic(arch);ws.push(rolling);
 }
 // Individual silhouettes: these are coachworks and equipment, not palette swaps.
 for(const side of [-1,1]){
  const lamp=new THREE.Group();lamp.position.set(side*.67,.93,1.06);frame.add(lamp);mesh(new THREE.CylinderGeometry(.15,.21,.24,24),steel,0,0,0,lamp).rotation.x=Math.PI/2;mesh(new THREE.CircleGeometry(.125,24),glow,0,0,.13,lamp);mesh(new THREE.TorusGeometry(.14,.025,10,28),gold,0,0,.14,lamp);
  for(let j=0;j<9;j++)strut([side*.09,.83-j*.025,1.45+j*.012],[side*.34,.81-j*.025,1.43+j*.012],.009,steel,frame);
  if(type===0){tube([[side*.45,.94,-1.15],[side*.69,1.3,-1.46],[side*.32,1.53,-1.71]],.08,gold,frame);}
  if(type===1){softBox(.25,.56,1.4,lacquer,side*.93,.87,.22,frame,true);for(let j=0;j<4;j++)mesh(new THREE.ConeGeometry(.1,.34,12),gold,side*.94,1.2,-.32+j*.3,frame);}
  if(type===2){const moon=mesh(new THREE.TorusGeometry(.88,.095,16,64,Math.PI*1.25),gold,side*.86,1.03,-.57,frame);moon.rotation.set(.4,side*.4,side*.3);}
  if(type===3)for(let j=0;j<6;j++){const wing=sculptedShell([[.02,.8,0],[.17,.97,.22],[.13,1.12,.62],[.008,1.28,1.26]],j%2?steel:lacquer,frame);wing.position.set(side*(.65+j*.13),.04,-.9-j*.09);wing.rotation.y=side*(-.75-j*.11);}
  if(type===4){tube([[side*.95,.71,1.46],[side*.95,1.29,1.54],[side*.55,1.3,1.7]],.067,steel,frame);softBox(.38,.24,.66,leather,side*.73,1.08,-1.21,frame,true);}
  if(type===5){tube([[side*.55,.82,1.03],[side*.75,1.33,1.45],[side*.57,1.9,1.61]],.064,gold,frame);for(let j=0;j<3;j++)tube([[side*.73,1.22+j*.18,1.43],[side*(.92+j*.03),1.47+j*.18,1.48]],.035,gold,frame);}
  if(type===6){softBox(.28,.55,2.45,steel,side*1.01,.87,0,frame,true);const stack=mesh(new THREE.CylinderGeometry(.14,.14,1.02,20),steel,side*.72,1.39,-1.1,frame);mesh(new THREE.TorusGeometry(.15,.035,8,24),gold,side*.72,1.93,-1.1,frame).rotation.x=Math.PI/2;}
  if(type===7){const turbine=mesh(new THREE.CylinderGeometry(.31,.24,1.62,32),lacquer,side*.79,.96,-.44,frame);turbine.rotation.x=Math.PI/2;mesh(new THREE.TorusGeometry(.255,.04,12,32),gold,side*.79,.96,.38,frame);ellipsoid(side*.79,.96,.39,.2,.2,.06,glow,frame);}
  if(skin===1){const tailFin=sculptedShell([[.008,.72,-2.13],[.29,.79,-1.71],[.34,.77,-1.17],[.05,.71,-.83]],lacquer,frame);tailFin.position.x=side*.59;tube([[side*.61,.85,-1.0],[side*.77,1.24,-1.76],[side*.49,1.65,-2.03]],.06,gold,frame);}
  if(skin===2){softBox(.3,.56,2.6,steel,side*.98,.76,-.07,frame,true);mesh(new THREE.TorusGeometry(.32,.095,16,32),gold,side*.71,1.14,-1.45,frame);ellipsoid(side*.71,1.14,-1.4,.23,.23,.38,glow,frame);}
 }
 if(type===4){const spare=mesh(new THREE.TorusGeometry(.37,.16,16,40),leather,0,1.12,-1.45,frame);spare.rotation.x=.5;mesh(new THREE.TorusGeometry(.25,.035,12,32),gold,0,1.18,-1.56,frame).rotation.x=.5;}
 if(type===1||type===6||skin===2){softBox(1.85,.32,.34,steel,0,.56,1.92,frame,true);tube([[-.84,.63,1.99],[0,.95,2.08],[.84,.63,1.99]],.055,gold,frame);}
 if(skin===2)tube([[-.82,.67,-.86],[-.88,1.92,-1.07],[0,2.1,-1.13],[.88,1.92,-1.07],[.82,.67,-.86]],.075,steel,frame);
 if(skin===1){const fin=mesh(new THREE.ConeGeometry(.3,1.1,32),lacquer,0,1.22,1.12,frame,true);fin.scale.z=2.2;fin.scale.x=.16;frame.scale.z=1.1;}
 frame.scale.x=[1,1.08,.88,1,.99,1,1.1,.92][type]*(skin===2?1.08:1);
 bakeStatic(frame);
 // Seated torso with layered pauldrons and segmented gauntlets.
 ellipsoid(0,1.57,-.4,.39,.59,.29,leather,rider,true);ellipsoid(0,1.72,-.28,.42,.47,.29,steel,rider,true);
 for(const side of [-1,1]){for(let layer=0;layer<3;layer++){const pad=ellipsoid(side*(.39+layer*.035),1.99-layer*.075,-.35,.28,.13,.32,layer===1?gold:steel,rider,true);pad.rotation.z=side*.19;}for(let j=0;j<3;j++)tube([[side*.07,1.85-j*.16,-.002],[side*.22,1.76-j*.15,.025],[side*.37,1.78-j*.15,-.1]],.012,gold,rider);ellipsoid(side*.24,1.14,.05,.21,.22,.53,steel,rider,true);}
 const clasp=mesh(new THREE.TorusGeometry(.09,.022,5,16),gold,0,1.94,.026,rider);tube([[-.31,2.06,-.1],[-.12,1.97,.035],[0,1.96,.05],[.14,1.98,.04],[.31,2.06,-.1]],.017,gold,rider);
 bakeStatic(rider);
 const cape=cloth(1.35,1.53,coat,body,true);cape.position.set(0,2.06,-.67);
 const head=new THREE.Group();head.position.set(0,2.32,-.31);body.add(head);head.name='animal-head';
 const furColor=[0x995226,0x77766e,0xbbb9b5,0x20272d,0x858f91,0x977753,0x6c5142,0x8b839e][type],pale=type===0?0xd0bda2:type===4?0xbdc4c0:0xc1beb2;
 const fur=mats['fur-'+type]||(mats['fur-'+type]=new THREE.MeshStandardMaterial({color:furColor,roughness:.94,bumpMap:furGrain,bumpScale:.032}));const muzzle=mat(pale,{roughness:.96});
 ellipsoid(0,.08,0,type===3?.28:.38,.37,.32,fur,head,true);ellipsoid(0,-.14,.17,.32,.19,.26,type===3?fur:muzzle,head,true);
 const eyes=[];
 if(type===3){const beak=mesh(new THREE.ConeGeometry(.16,.59,8),mat(0x857044,{roughness:.54}),0,-.045,.49,head,true);beak.rotation.x=Math.PI/2;beak.scale.x=.66;for(let side of [-1,1])for(let i=0;i<6;i++){const feather=ellipsoid(side*(.2+i*.017),-.03-i*.035,-.13-i*.035,.075,.075,.26,fur,head);feather.rotation.y=side*.4;}}
 else{ellipsoid(0,-.07,.32,type===2?.16:.22,.13,type===0||type===4?.3:.21,muzzle,head,true);ellipsoid(0,-.04,type===0||type===4?.6:.5,.087,.065,.062,mat(0x171c1e,{roughness:.36}),head);tube([[-.16,-.15,.39],[0,-.18,.54],[.16,-.15,.39]],.009,mat(0x36302d),head);
  for(const side of [-1,1]){if(type===2){const ear=ellipsoid(side*.22,.57,-.06,.12,.52,.09,fur,head,true);ear.rotation.z=-side*.14;ellipsoid(side*.23,.59,.016,.047,.35,.017,mat(0x8b7a7d),head);}else if(type===1||type===6){ellipsoid(side*.28,.4,-.07,.15,.18,.085,fur,head,true);ellipsoid(side*.29,.43,.01,.087,.1,.025,mat(0x333639),head);ellipsoid(side*.19,.05,.268,.18,.085,.065,mat(0x2f3335),head);}else{const ear=mesh(new THREE.ConeGeometry(.21,.61,12),fur,side*.3,.48,-.06,head,true);ear.rotation.z=-side*.19;ear.scale.z=.64;const inner=mesh(new THREE.ConeGeometry(.125,.4,12),mat(0x352d29,{roughness:1}),side*.31,.48,.041,head);inner.scale.z=.3;}}
 }
 for(const side of [-1,1]){const eye=new THREE.Group();eye.position.set(side*.185,.1,.284);eye.rotation.z=side*.16;head.add(eye);ellipsoid(0,0,0,.107,.044,.03,mat(0x151b1e,{roughness:.25}),eye);ellipsoid(-side*.01,0,.028,.034,.032,.015,mat(type===3?0xa1a88f:0xcaa765,{roughness:.25}),eye);ellipsoid(-side*.01,0,.043,.012,.028,.009,0x111516,eye);eyes.push(eye);
  const brow=ellipsoid(side*.2,.17,.276,.17,.059,.065,fur,head,true);brow.rotation.z=side*.25;
  // Swept fur tufts break the cheek and neck silhouette.
  for(let i=0;i<20;i++){const t=i/20,a=t*Math.PI*1.5,tuft=mesh(new THREE.ConeGeometry(.045,.15+(i%3)*.025,8),type===3?fur:i%3?fur:muzzle,side*(.26+Math.sin(a)*.08),.22-t*.52,-.08+Math.cos(a)*.12,head);tuft.rotation.z=side*(1.1+t*.5);tuft.rotation.x=-.25;}
 }
 if(type===5)for(const side of [-1,1]){tube([[side*.23,.31,-.05],[side*.4,.72,-.11],[side*.57,1.01,-.18],[side*.51,1.3,-.11]],.049,gold,head);for(let j=0;j<3;j++)tube([[side*(.34+j*.09),.59+j*.2,-.09],[side*(.57+j*.1),.72+j*.23,.01]],.032,gold,head);}
 if(type===7){for(const side of [-1,1])tube([[side*.27,.31,-.08],[side*.38,.52,-.2],[side*.24,.76,-.33]],.07,gold,head);for(let j=0;j<5;j++){const spike=mesh(new THREE.ConeGeometry(.075,.22,16),gold,0,.33-j*.057,-.1-j*.06,head);spike.rotation.x=-.7;}ellipsoid(0,-.02,.34,.21,.16,.27,fur,head);}
 // Eyes blink independently of the static head surface.
 for(const eye of eyes)head.remove(eye);bakeStatic(head);for(const eye of eyes){head.add(eye);bakeStatic(eye);}
 const steeringPivot=new THREE.Group();steeringPivot.position.set(0,1.39,.38);steeringPivot.rotation.x=-.44;body.add(steeringPivot);const steering=mesh(new THREE.TorusGeometry(.43,.055,16,48),leather,0,0,0,steeringPivot);for(const a of [0,2.1,4.2])strut([0,0,0],[Math.sin(a)*.39,Math.cos(a)*.39,0],.025,gold,steeringPivot);bakeStatic(steeringPivot);
 const hands=[-1,1].map(side=>{const hand=new THREE.Group();body.add(hand);ellipsoid(0,0,0,.145,.125,.15,leather,hand,true);for(let i=0;i<4;i++){const finger=mesh(new THREE.CapsuleGeometry(.024,.095,6,12),steel,(i-1.5)*.049,.064,.01,hand);finger.rotation.x=Math.PI/2;}bakeStatic(hand);return hand;});
 const arms=hands.map((hand,i)=>{const side=i===0?-1:1,upper=mesh(new THREE.CylinderGeometry(.15,.17,1,10),steel,0,0,0,body,true),lower=mesh(new THREE.CylinderGeometry(.12,.15,1,10),steel,0,0,0,body,true);return {side,upper,lower,hand};});
 const tail=new THREE.Group();tail.position.set(0,1.08,-1.03);tail.name='tail-below-split-cape';body.add(tail);if(type!==3){const fluffy=ellipsoid(0,-.15,-.28,type===2?.2:.19,.2,type===2?.2:.6,fur,tail);fluffy.rotation.y=-.23;if(type===0||type===4)ellipsoid(.08,-.15,-.7,.14,.15,.23,muzzle,tail);if(type===1)for(let i=0;i<3;i++)ellipsoid(0,-.15,-.08-i*.2,.197,.207,.07,mat(0x363a3a),tail);}bakeStatic(tail);
 if(type===5||type===6)tail.scale.setScalar(.65);
 const shield=mesh(new THREE.SphereGeometry(1.9,20,14),mat(hero.glow,{transparent:true,opacity:.12,metalness:.5,roughness:.12,depthWrite:false}),0,1.35,0,g);shield.visible=false;
 const flame=ellipsoid(0,.68,-1.75,.3,.24,.85,glow,g);flame.visible=false;
 const hand=hands[0],held=new THREE.Group();body.add(held);const items={};for(const type of Object.keys(C.ITEMS)){const item=new THREE.Group();held.add(item);items[type]=item;item.visible=false;if(type==='coconut'){ellipsoid(0,0,0,.29,.29,.29,mat(0xbfcac2,{metalness:.65,roughness:.2,emissive:0x6495a0,emissiveIntensity:.7}),item);mesh(new THREE.TorusGeometry(.34,.025,6,16),glow,0,0,0,item);}else if(type==='bomb'){mesh(new THREE.IcosahedronGeometry(.36,1),mat(0x443146,{metalness:.45,roughness:.3}),0,0,0,item);for(const x of [-.15,.15])mesh(new THREE.ConeGeometry(.07,.25,5),glow,x,.34,0,item);}else if(type==='boost'){mesh(new THREE.CylinderGeometry(.13,.2,.5,10),glow,0,0,0,item);mesh(new THREE.CylinderGeometry(.13,.13,.12,8),gold,0,.29,0,item);}else mesh(new THREE.TorusGeometry(.3,.065,6,6),glow,0,0,0,item);}
 const respawnRing=mesh(new THREE.TorusGeometry(1.65,.035,6,36),glow,0,.1,0,g);respawnRing.rotation.x=Math.PI/2;respawnRing.visible=false;scene.add(g);return {g,body,frame,ws,shield,flame,hand,held,items,respawnRing,head,eyes,cape,arms,tail,steeringPivot};
}
buildWorld(0);
let selected=0,selectedTrack=0,models=[],modelSelected=-1;
function buildKarts(){const signature=selected+':'+profile.heroes.map(h=>h.skin).join(',');if(modelSelected===signature)return;modelSelected=signature;for(const k of models)disposeGroup(k.g);models=Array.from({length:6},(_,i)=>{const hero=i===0?selected:(selected+i)%C.DRIVERS.length;return kart(hero,profile.heroes[hero].skin);});}
const particles=[];for(let i=0;i<60;i++){const m=mesh(new THREE.SphereGeometry(.12,4,3),mat(0xffd46a,{emissive:0xff9d39,emissiveIntensity:1.4}));m.visible=false;particles.push({m,life:0,v:new THREE.Vector3()});}let particleIndex=0;
function spark(pos,right){const p=particles[particleIndex++%particles.length];p.m.position.copy(pos).addScaledVector(right,(Math.random()>.5?1:-1)*1.1);p.m.position.y+=.3;p.v.set((Math.random()-.5)*4,1+Math.random()*2,(Math.random()-.5)*4);p.life=.3+Math.random()*.25;p.m.visible=true;}
const projectileViews=Array.from({length:18},()=>{const g=new THREE.Group();scene.add(g);const coconut=ellipsoid(0,0,0,.5,.5,.5,mat(0xa7c2be,{emissive:0x6095a0,emissiveIntensity:.7,metalness:.65,roughness:.2}),g,true),bomb=ellipsoid(0,0,0,.6,.6,.6,mat(0x4a3c51,{emissive:0x8f5374,emissiveIntensity:.7,metalness:.6,roughness:.3}),g,true);const band=mesh(new THREE.TorusGeometry(.45,.055,5,12),0xf4d095,0,0,0,g);g.visible=false;return {g,coconut,bomb,band};});
const blastViews=Array.from({length:10},()=>{const m=mesh(new THREE.SphereGeometry(1,14,10),new THREE.MeshBasicMaterial({color:0xffc7aa,transparent:true,opacity:.3,depthWrite:false}));m.visible=false;return m;});
const smokeCanvas=document.createElement('canvas');smokeCanvas.width=smokeCanvas.height=64;const smokeCtx=smokeCanvas.getContext('2d'),gradient=smokeCtx.createRadialGradient(32,32,2,32,32,32);gradient.addColorStop(0,'rgba(190,195,200,.6)');gradient.addColorStop(.45,'rgba(155,160,170,.24)');gradient.addColorStop(1,'rgba(120,130,145,0)');smokeCtx.fillStyle=gradient;smokeCtx.fillRect(0,0,64,64);const smokeTexture=new THREE.CanvasTexture(smokeCanvas);
const smoke=Array.from({length:72},()=>{const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:smokeTexture,transparent:true,opacity:0,depthWrite:false,color:0xbfc5ce}));scene.add(sprite);return {sprite,life:0,maxLife:1,v:new THREE.Vector3()};});let smokeIndex=0;
function tireSmoke(r){for(const side of [-1,1]){const p=smoke[smokeIndex++%smoke.length];p.life=p.maxLife=.9+Math.random()*.5;p.sprite.position.set(r.x-Math.cos(r.yaw)*side-Math.sin(r.yaw),r.y+.28,r.z+Math.sin(r.yaw)*side-Math.cos(r.yaw));p.sprite.material.rotation=Math.random()*Math.PI;p.v.set(-r.vx*.05+(Math.random()-.5)*.8,1.1+Math.random(),-r.vz*.05+(Math.random()-.5)*.8);}}
const skidPositions=new Float32Array(1200*18),skidGeometry=new THREE.BufferGeometry();skidGeometry.setAttribute('position',new THREE.BufferAttribute(skidPositions,3));skidGeometry.setDrawRange(0,0);const skidMesh=new THREE.Mesh(skidGeometry,new THREE.MeshBasicMaterial({color:0x13181d,transparent:true,opacity:.5,side:THREE.DoubleSide,depthWrite:false}));skidMesh.frustumCulled=false;scene.add(skidMesh);let skidIndex=0,skidCount=0,lastTire=null;
function leaveSkid(r){const rx=-Math.cos(r.yaw),rz=Math.sin(r.yaw),tires=[-1,1].map(side=>({x:r.x+rx*side-Math.sin(r.yaw)*.94,z:r.z+rz*side-Math.cos(r.yaw)*.94}));if(lastTire)for(let i=0;i<2;i++){const a=lastTire[i],b=tires[i],dist=Math.hypot(b.x-a.x,b.z-a.z);if(dist<.04||dist>3)continue;const nx=-(b.z-a.z)/dist*.11,nz=(b.x-a.x)/dist*.11,ay=track.nearest(a.x,a.z,r.nearD).y+.045,by=track.nearest(b.x,b.z,r.nearD).y+.045;const points=[[a.x+nx,ay,a.z+nz],[a.x-nx,ay,a.z-nz],[b.x+nx,by,b.z+nz],[b.x+nx,by,b.z+nz],[a.x-nx,ay,a.z-nz],[b.x-nx,by,b.z-nz]];skidPositions.set(points.flat(),skidIndex*18);skidIndex=(skidIndex+1)%1200;skidCount=Math.min(1200,skidCount+1);}lastTire=tires;skidGeometry.attributes.position.needsUpdate=true;skidGeometry.setDrawRange(0,skidCount*6);}
const torchLights=Array.from({length:4},()=>{const light=new THREE.PointLight(0xffac58,150,42,2);scene.add(light);return light;});
const headLights=[-1,1].map(side=>{const light=new THREE.SpotLight(0xffe2ac,100,52,.46,.65,2);scene.add(light,light.target);return {light,side};});
function updateAtmosphere(dt){for(const p of smoke){if(p.life<=0){p.sprite.visible=false;continue;}p.life-=dt;p.sprite.visible=true;p.sprite.position.addScaledVector(p.v,dt);const t=1-p.life/p.maxLife;p.sprite.scale.setScalar(.65+t*2.5);p.sprite.material.opacity=(1-t)*.5;}
 updateLivingWorld(dt);const p=state.racers[0],nearest= [...torchAnchors].sort((a,b)=>(a.x-p.x)**2+(a.z-p.z)**2-((b.x-p.x)**2+(b.z-p.z)**2));torchLights.forEach((light,i)=>{if(nearest[i])light.position.copy(nearest[i]);light.color.setHex(0xffac58);light.intensity=150+Math.sin(elapsed*7+i)*24;});for(const {light,side} of headLights){const rx=-Math.cos(p.yaw),rz=Math.sin(p.yaw);light.position.set(p.x+rx*side*.65,p.y+1.15,p.z+rz*side*.65);light.target.position.set(p.x+Math.sin(p.yaw)*20,p.y-1,p.z+Math.cos(p.yaw)*20);light.visible=p.phase==='driving';}}
function updateEffects(){
 projectileViews.forEach((view,i)=>{const b=state.projectiles[i];view.g.visible=!!b;if(!b)return;view.g.position.set(b.x,b.y,b.z);view.g.rotation.set(elapsed*8,elapsed*3,0);view.coconut.visible=b.type==='coconut';view.band.visible=b.type==='coconut';view.bomb.visible=b.type==='bomb';});
 blastViews.forEach((view,i)=>{const e=state.effects[i];view.visible=!!e;if(!e)return;view.position.set(e.x,e.y,e.z);const t=1-e.life/e.maxLife;view.scale.setScalar((e.type==='blast'?7:2)*t+.3);view.material.opacity=(1-t)*.4;});
}
let simulationDebt=0;let mode='menu',state=C.createRace(track),keys={},countdown=3.5,last=performance.now(),elapsed=0,noticeUntil=0,uiClock=0,previousCount=4;
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const profileKey='wild-drift-ashen-profile-v1';let profile=C.newProfile(),storageWritable=true;
function storageWarning(message){$('storageNotice').textContent=message;$('storageNotice').classList.remove('hidden');}
try{profile=C.parseProfile(localStorage.getItem(profileKey));}catch{storageWritable=false;storageWarning('Сохранение недоступно. Прогресс этой сессии останется в памяти до закрытия вкладки; старое сохранение не изменено.');}
function mutateProfile(action){if(storageWritable){try{profile=C.parseProfile(localStorage.getItem(profileKey));}catch{storageWritable=false;storageWarning('Не удалось прочитать сохранение. Старые данные не перезаписываются.');}}
 const result=action(profile);if(storageWritable){try{localStorage.setItem(profileKey,JSON.stringify(profile));}catch{storageWritable=false;storageWarning('Браузер не разрешил сохранить прогресс. Не закрывай вкладку, чтобы не потерять улучшения этой сессии.');}}return result;}
function showBest(){const best=profile.records[window.RaceTracks[selectedTrack].recordKey];$('menuBest').textContent=best?'ЛЕТОПИСЬ  '+C.formatTime(best):'ВПИШИ СВОЁ ИМЯ В ЛЕТОПИСЬ';}
function mapPoint(t,x,z,w,h){const b=t.bounds,scale=Math.min((w-20)/(b.maxX-b.minX),(h-15)/(b.maxZ-b.minZ));return [w/2+(x-(b.minX+b.maxX)/2)*scale,h/2+(z-(b.minZ+b.maxZ)/2)*scale];}
function drawCourseCards(){window.RaceTracks.forEach((t,i)=>{const canvas=$('courseMap'+i),ctx=canvas.getContext('2d');ctx.clearRect(0,0,150,85);ctx.strokeStyle='#'+t.meta.accent.toString(16).padStart(6,'0');ctx.lineWidth=2;ctx.beginPath();t.segments.forEach((seg,j)=>{if(j%5)return;const [x,y]=mapPoint(t,seg.a.x,seg.a.z,150,85);if(j===0||t.gapAt(seg.d))ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();$('courseMeta'+i).textContent=(t.length/1000).toFixed(2).replace('.',',')+' км · '+t.gaps.length+' разрыва'+(t.overpasses.length?' · мост над дорогой':'');});}
let previewSkin=0,garageRenderer=null,garageScene=null,garageCamera=null,garageModel=null,garageSignature='';
function updateGarage(){
 if($('forge').classList.contains('hidden'))return;
 try{if(!garageRenderer){garageRenderer=new THREE.WebGLRenderer({canvas:$('garagePreview'),antialias:true,alpha:true});garageRenderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));garageRenderer.setSize(600,260,false);garageRenderer.outputColorSpace=THREE.SRGBColorSpace;garageRenderer.toneMapping=THREE.ACESFilmicToneMapping;garageRenderer.toneMappingExposure=1.35;garageRenderer.shadowMap.enabled=true;garageRenderer.shadowMap.type=THREE.PCFSoftShadowMap;garageScene=new THREE.Scene();garageScene.name='garage';garageScene.add(new THREE.HemisphereLight(0xdfefff,0x3b3545,2.6));const light=new THREE.DirectionalLight(0xffdeaf,4);light.position.set(3,7,5);light.castShadow=true;light.shadow.mapSize.set(1024,1024);garageScene.add(light);const rim=new THREE.DirectionalLight(0xadcfff,3);rim.position.set(-4,3,-4);garageScene.add(rim);const floor=mesh(new THREE.CylinderGeometry(3,3.2,.15,64),mat(0x313b44,{metalness:.25,roughness:.47}),0,-.16,0,garageScene);floor.receiveShadow=true;garageCamera=new THREE.PerspectiveCamera(36,600/260,.1,40);garageCamera.position.set(5.8,4.25,7);garageCamera.lookAt(0,1.35,.2);}
  const signature=selected+':'+previewSkin;if(garageSignature===signature)return;garageSignature=signature;disposeGroup(garageModel?.g);garageModel=kart(selected,previewSkin);garageScene.add(garageModel.g);
  for(const arm of garageModel.arms){arm.hand.position.set(arm.side*.39,1.43,.4);const shoulder=new THREE.Vector3(arm.side*.46,1.98,-.32),elbow=new THREE.Vector3(arm.side*.62,1.62,-.07);for(const [part,a,b] of [[arm.upper,shoulder,elbow],[arm.lower,elbow,arm.hand.position]]){part.position.copy(a).add(b).multiplyScalar(.5);part.scale.y=a.distanceTo(b);part.quaternion.setFromUnitVectors(up,b.clone().sub(a).normalize());}}
  renderGarage(performance.now());
 }catch{ $('skinNotice').textContent='Предпросмотр недоступен. Выбранный кузов появится в заезде.';}
}
function renderGarage(now){if(!garageModel||$('forge').classList.contains('hidden'))return;const canvas=$('garagePreview'),width=canvas.clientWidth||600,height=canvas.clientHeight||260;if(canvas.width!==Math.round(width*(Math.min(devicePixelRatio||1,1.5)))){garageRenderer.setSize(width,height,false);garageCamera.aspect=width/height;garageCamera.updateProjectionMatrix();}garageModel.g.rotation.y=reducedMotion?.6:now*.0003+.6;waveCloth(garageModel.cape,now/1000,.3);garageRenderer.render(garageScene,garageCamera);}
function renderShop(){const hero=profile.heroes[selected];$('carName').textContent=carNames[selected];$('wallet').textContent=profile.points;$('skinDescription').textContent=C.SKINS[previewSkin].description;document.querySelectorAll('[data-skin]').forEach(b=>{const id=Number(b.dataset.skin),chosen=id===previewSkin;b.classList.toggle('selected',chosen);b.setAttribute('aria-pressed',String(chosen));$('skinStatus'+id).textContent=hero.skin===id?'УСТАНОВЛЕН':hero.skins.includes(id)?'КУПЛЕН':C.SKINS[id].price+' ОЧКОВ';});const owned=hero.skins.includes(previewSkin),equipped=hero.skin===previewSkin;$('buySkin').textContent=equipped?'КУЗОВ УСТАНОВЛЕН':owned?'УСТАНОВИТЬ КУЗОВ':'КУПИТЬ ЗА '+C.SKINS[previewSkin].price+' ОЧКОВ';$('buySkin').disabled=equipped||!owned&&profile.points<C.SKINS[previewSkin].price;updateGarage();}
function renderForge(){const hero=C.DRIVERS[selected],h=profile.heroes[selected],v=C.stats(selected,h.upgrades),points=C.skillPoints(h);$('forgeTitle').textContent=hero.name+' · '+hero.kind;$('forgeTrait').textContent=hero.trait+'. '+hero.description;$('forgeLevel').textContent='Уровень '+(1+Math.floor(h.xp/150));$('forgeXP').textContent=(h.xp%150)+' / 150 опыта';$('xpBar').style.width=(h.xp%150)/150*100+'%';$('forgePoints').textContent=points;
 const values={Speed:Math.round(v.speed*3.1)+' км/ч',Handling:Math.round(v.handling*100)+'%',Acceleration:v.acceleration.toFixed(1),Braking:v.braking.toFixed(1),Aero:Math.round(v.aero*100)+'%'};for(const [key,value] of Object.entries(values)){$('stat'+key).textContent=value;$('level'+key).textContent=h.upgrades[key.toLowerCase()]+'/5';}document.querySelectorAll('[data-upgrade]').forEach(b=>{b.disabled=points<1||h.upgrades[b.dataset.upgrade]>=5;});renderShop();}
function renderMenu(){const hero=C.DRIVERS[selected],h=profile.heroes[selected],t=window.RaceTracks[selectedTrack];$('heroTrait').textContent=hero.trait;$('traitDescription').textContent=hero.description;$('pointsBadge').textContent=C.skillPoints(h);$('selectedCourseName').textContent=t.name;$('selectedCourseDescription').textContent=t.meta.subtitle;document.querySelector('.selection-number').textContent=String(selected+1).padStart(2,'0')+' / 08';C.DRIVERS.forEach((d,i)=>{$('heroLevel'+i).textContent=d.kind+' · ур. '+(1+Math.floor(profile.heroes[i].xp/150));});showBest();renderForge();}
$('openForge').addEventListener('click',()=>{previewSkin=profile.heroes[selected].skin;$('skinNotice').textContent='';$('forge').classList.remove('hidden');renderForge();$('closeForge').focus();});$('forge').addEventListener('keydown',e=>{if(e.code!=='Tab')return;const buttons=[$('closeForge'),...document.querySelectorAll('[data-upgrade]'),...document.querySelectorAll('[data-skin]'),$('buySkin'),$('forgeDone')].filter(b=>!b.disabled),first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});for(const id of ['closeForge','forgeDone'])$(id).addEventListener('click',()=>{$('forge').classList.add('hidden');$('openForge').focus();});
document.querySelectorAll('[data-skin]').forEach(button=>button.addEventListener('click',()=>{previewSkin=Number(button.dataset.skin);$('skinNotice').textContent='';renderShop();}));
$('buySkin').addEventListener('click',()=>{const ok=mutateProfile(p=>C.chooseSkin(p,selected,previewSkin));$('skinNotice').textContent=ok?'Кузов установлен. Готов к заезду.':'Недостаточно очков заездов.';if(ok)buildKarts();renderMenu();});
document.querySelectorAll('[data-upgrade]').forEach(button=>button.addEventListener('click',()=>{mutateProfile(p=>C.upgrade(p,selected,button.dataset.upgrade));renderMenu();}));
document.querySelectorAll('[data-track]').forEach(button=>button.addEventListener('click',()=>{selectedTrack=Number(button.dataset.track);document.querySelectorAll('[data-track]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));});renderMenu();}));
drawCourseCards();renderMenu();buildKarts();
$('keyArt').style.backgroundImage='url("assets/fantasy-art.png")';
let soundOn=false,audio=null,engine=null,engineGain=null;
function initAudio(){if(!audio){const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;audio=new AudioContext();engine=audio.createOscillator();engine.type='sawtooth';const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=330;engineGain=audio.createGain();engineGain.gain.value=0;engine.connect(filter);filter.connect(engineGain);engineGain.connect(audio.destination);engine.start();}if(audio.state==='suspended')audio.resume().catch(()=>{});}
function beep(freq=600,duration=.15){if(!soundOn||!audio)return;const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(.12,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration);}
function showNotice(text){$('notice').textContent=text;noticeUntil=elapsed+2.3;beep(text.includes('КРУГ')?880:580,.13);}
function hideOverlays(){for(const id of ['menu','pause','finish','forge'])$(id).classList.add('hidden');}
function startRace(){initAudio();keys={};if(track.courseIndex!==selectedTrack)buildWorld(selectedTrack);state=C.createRace(track,selected,profile.heroes[selected].upgrades);state.rng=Math.floor(Math.random()*4294967296);$('hudCourseName').textContent=track.name.toUpperCase();simulationDebt=0;skidIndex=skidCount=0;lastTire=null;for(const p of smoke)p.life=0;skidGeometry.setDrawRange(0,0);countdown=3.5;previousCount=4;mode='countdown';noticeUntil=0;$('notice').textContent='';$('countdown').textContent='3';hideOverlays();$('hud').classList.remove('hidden');$('pauseButton').classList.remove('hidden');document.body.classList.add('racing');buildKarts();placeKarts(0);updateCamera(1,true);updateHUD();$('start').blur();}
function pauseRace(){if(mode!=='race'&&mode!=='countdown')return;mode=mode==='race'?'paused':'paused-countdown';keys={};$('pause').classList.remove('hidden');$('resume').focus();}
function resumeRace(){if(mode!=='paused'&&mode!=='paused-countdown')return;mode=mode==='paused'?'race':'countdown';$('pause').classList.add('hidden');keys={};}
function menu(){mode='menu';keys={};hideOverlays();$('menu').classList.remove('hidden');$('hud').classList.add('hidden');$('pauseButton').classList.add('hidden');document.body.classList.remove('racing');renderMenu();$('start').focus();}
function finishRace(){mode='finish';$('hud').classList.add('hidden');$('pauseButton').classList.add('hidden');$('finish').classList.remove('hidden');$('finishRank').innerHTML=state.rank+'<span>МЕСТО</span>';$('finishTitle').textContent=state.rank===1?'Пепел помнит победителя.':state.rank<=3?'Завет исполнен.':'Бездна ждёт реванша.';$('finishTime').textContent=C.formatTime(state.finishTime);$('bestLap').textContent=C.formatTime(Math.min(...state.lapTimes));const best=profile.records[track.recordKey];$('record').textContent=!best||state.finishTime<best?'Новая запись в летописи ✦':'Рекорд мира: '+C.formatTime(best);const reward=mutateProfile(p=>C.awardRace(p,state));$('reward').textContent=reward?'+'+reward.xp+' опыта'+(reward.levelUps?' · +'+reward.levelUps+' очк. улучшений':'')+' · +'+reward.points+' очков заездов':'';renderMenu();beep(880,.5);$('again').focus();}
for(const id of ['start','restart','again'])$(id).addEventListener('click',startRace);$('resume').addEventListener('click',resumeRace);for(const id of ['back','garage'])$(id).addEventListener('click',menu);$('pauseButton').addEventListener('click',pauseRace);document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();if(mode==='menu')return;pauseRace();});
document.querySelectorAll('[data-driver]').forEach(button=>button.addEventListener('click',()=>{selected=Number(button.dataset.driver);document.querySelectorAll('[data-driver]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));});buildKarts();renderMenu();}));
$('sound').addEventListener('click',()=>{soundOn=!soundOn;initAudio();$('sound').querySelector('.slash').classList.toggle('hidden',soundOn);$('sound').setAttribute('aria-label',soundOn?'Выключить звук':'Включить звук');beep();});
$('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else showNotice('Используй полноэкранный режим браузера');}catch{showNotice('Используй полноэкранный режим браузера');}});
function activateItem(){if(mode==='race'&&C.useItem(state))beep(700,.2);}$('item').addEventListener('click',activateItem);
const controlCodes=['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD','Space','KeyC','ShiftLeft','ShiftRight'];
window.addEventListener('keydown',e=>{if(controlCodes.includes(e.code)&&(mode==='race'||mode==='countdown'))e.preventDefault();keys[e.code]=true;if(e.repeat)return;if(e.code==='Escape'){if(!$('forge').classList.contains('hidden')){$('forge').classList.add('hidden');$('openForge').focus();return;}if(mode.startsWith('paused'))resumeRace();else pauseRace();}if(e.code.startsWith('Shift'))activateItem();if(e.code==='KeyR'&&mode==='race')C.recover(state);});window.addEventListener('keyup',e=>{keys[e.code]=false;});
window.addEventListener('blur',()=>{keys={};pauseRace();});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys={};pauseRace();}});
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>{keys[b.dataset.key]=false;});});
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.75));});
function getInput(){return {throttle:!!(keys.KeyW||keys.ArrowUp),brake:!!(keys.KeyS||keys.ArrowDown),steer:Number(!!(keys.KeyD||keys.ArrowRight))-Number(!!(keys.KeyA||keys.ArrowLeft)),drift:!!keys.Space};}
function renderPose(r){const prev=r.previousPose;if(!prev||prev.phase!==r.phase||mode!=='race')return r;const t=Math.min(1,simulationDebt*120);return {x:THREE.MathUtils.lerp(prev.x,r.x,t),y:THREE.MathUtils.lerp(prev.y,r.y,t),z:THREE.MathUtils.lerp(prev.z,r.z,t),yaw:prev.yaw+C.angle(r.yaw-prev.yaw)*t};}
function placeKarts(dt){
 for(let i=0;i<models.length;i++){
  const r=state.racers[i],k=models[i],pose=renderPose(r);k.g.position.set(pose.x,pose.y,pose.z);
  const pitch=r.grounded?Math.atan(r.surface.slope)*(Math.cos(r.yaw)*r.surface.tz+Math.sin(r.yaw)*r.surface.tx):Math.atan2(r.vy,Math.max(r.speed,1));
  const roll=-Math.atan(r.surface.crossSlope||0)*(Math.cos(r.yaw)*r.surface.tz+Math.sin(r.yaw)*r.surface.tx);k.g.rotation.set(THREE.MathUtils.damp(k.g.rotation.x,-pitch,14,dt||1),pose.yaw,THREE.MathUtils.damp(k.g.rotation.z,roll,14,dt||1),'YXZ');
  k.body.rotation.z=THREE.MathUtils.damp(k.body.rotation.z,r.steering*(r.drifting?.1:.055),10,dt);
  k.body.rotation.y=r.hitAnim>0?Math.sin(r.hitAnim*19)*.45:0;
  k.body.position.y=(r.speed>1&&r.grounded?Math.sin(elapsed*20+i)*.018:0)-(r.landing>0?Math.sin(r.landing/.4*Math.PI)*.16:0);
  k.g.visible=true;k.g.scale.setScalar(1);k.respawnRing.visible=false;
  if(r.phase==='falling'){k.body.rotation.z+=Math.sin(elapsed*4)*.2;k.g.scale.setScalar(Math.max(.3,r.phaseTime/.8));}
  if(r.phase==='respawning'){const t=1-r.phaseTime/1.05;k.g.position.y+=7*(1-t)**3;k.g.scale.setScalar(.7+.3*t);k.g.visible=Math.floor(r.phaseTime*18)%3!==0;k.respawnRing.visible=true;k.respawnRing.scale.setScalar(1.8-.8*t);}
  for(let j=0;j<k.ws.length;j++){const wheel=k.ws[j];wheel.rotation.x+=r.speed*dt/.54;if(wheel.parent!==k.body)wheel.parent.rotation.y=wheel.parent.userData.front?-r.steering*.38:0;}
  k.shield.visible=r.shield>0&&r.phase!=='falling';k.flame.visible=r.boost>0&&r.phase==='driving';k.flame.scale.z=.65+Math.sin(elapsed*50)*.15;
  k.steeringPivot.rotation.z=-r.steering*.42;const steer=-r.steering*.42;for(const arm of k.arms){const side=arm.side;arm.hand.position.set(side*.39*Math.cos(steer),1.43+side*.39*Math.sin(steer),.4);arm.hand.rotation.z=steer;}if(r.item)k.hand.position.set(-.83,2.05,-.02);k.hand.rotation.z=r.item?-.4:steer;
  if(r.throwAnim>0){k.hand.position.y=1.6+Math.sin(r.throwAnim/.4*Math.PI)*.65;k.hand.position.z=.3+Math.sin(r.throwAnim/.4*Math.PI)*.8;}
  for(const arm of k.arms){const shoulder=new THREE.Vector3(arm.side*.46,1.98,-.32),elbow=new THREE.Vector3(arm.side*.62,1.62,-.07);for(const [part,a,b] of [[arm.upper,shoulder,elbow],[arm.lower,elbow,arm.hand.position]]){part.position.copy(a).add(b).multiplyScalar(.5);part.scale.y=a.distanceTo(b);part.quaternion.setFromUnitVectors(up,b.clone().sub(a).normalize());}}
  const motion=reducedMotion?.2:1;k.head.rotation.y=-r.steering*.16;k.head.rotation.z=-r.steering*.08;k.head.position.y=2.32+Math.sin(elapsed*2.2+i)*.012*motion;const blink=C.wrap(elapsed+i*1.13,4.3)<.13;for(const eye of k.eyes)eye.scale.y=blink?.13:1;waveCloth(k.cape,elapsed+i*.7,(.45+r.speed/32)*motion);k.tail.rotation.y=Math.sin(elapsed*2.3+i)*.09*motion;
  k.held.position.copy(k.hand.position);k.held.position.y+=.3;k.held.rotation.y=elapsed*.7;
  for(const [type,object] of Object.entries(k.items))object.visible=r.item===type;
  if(i===0){if(r.grounded&&r.phase==='driving'&&r.drifting&&Math.abs(r.slip)>.13){spark(new THREE.Vector3(r.x,r.y,r.z),new THREE.Vector3(-Math.cos(r.yaw),0,Math.sin(r.yaw)));leaveSkid(r);if(Math.random()<dt*32)tireSmoke(r);}else lastTire=null;}
 }
}
const cameraTarget=new THREE.Vector3(),cameraAnchor=new THREE.Vector3();let cameraYaw=0,cameraGrade=0;
function updateCamera(dt,snap=false){
 if(mode==='menu'){camera.position.set(340,185,300);camera.lookAt(0,15,0);return;}
 const p=state.racers[0],pose=renderPose(p),travel=p.speed>5?Math.atan2(p.vx,p.vz):p.yaw,targetYaw=pose.yaw+C.angle(travel-pose.yaw)*.65,factor=snap?1:1-Math.exp(-10*dt);
 cameraYaw+=C.angle(targetYaw-cameraYaw)*(snap?1:1-Math.exp(-4.5*dt));
 const position=new THREE.Vector3(pose.x,pose.y+(p.phase==='respawning'?7*(p.phaseTime/1.05)**3:0),pose.z);
 cameraAnchor.lerp(position,factor);
 const a=track.sample(p.nearD-6,p.lane),b=track.sample(p.nearD+6,p.lane),grade=p.grounded?C.clamp((b.y-a.y)/12,-.65,.65)*(Math.sin(cameraYaw)*p.surface.tx+Math.cos(cameraYaw)*p.surface.tz):0;
 cameraGrade+=(grade-cameraGrade)*(snap?1:1-Math.exp(-5*dt));
 const direction=keys.KeyC?-1:1,heading=new THREE.Vector3(Math.sin(cameraYaw)*direction,0,Math.cos(cameraYaw)*direction),distance=10.8+(p.boost>0?1.2:0);
 // Position and look target share the same filtered anchor; no mismatched vertical lag.
 camera.position.copy(cameraAnchor).addScaledVector(heading,-distance);camera.position.y+=5.4-cameraGrade*direction*distance;
 const under=track.nearest(camera.position.x,camera.position.z,p.nearD);if(under.ground&&Math.abs(under.lane)<12.2)camera.position.y=Math.max(camera.position.y,under.y+2);
 cameraTarget.copy(cameraAnchor).addScaledVector(heading,6);cameraTarget.y+=1.5+cameraGrade*direction*6;camera.lookAt(cameraTarget);
 const fov=58+(p.boost>0&&!reducedMotion?8:0);camera.fov+=(fov-camera.fov)*factor;camera.updateProjectionMatrix();
 sun.position.set(p.x-60,p.y+100,p.z+45);sun.target.position.set(p.x,p.y,p.z);
}

const map=$('minimap').getContext('2d');
function drawMap(){
 map.clearRect(0,0,220,180);const point=s=>mapPoint(track,s.p.x,s.p.z,220,180);map.lineCap='round';
 for(const [width,color] of [[9,'#183f4866'],[3,'#fff6df']]){map.strokeStyle=color;map.lineWidth=width;map.beginPath();for(let i=0;i<=N;i+=3){const [x,y]=point(samples[i]);if(i===0||track.gapAt(distances[i]))map.moveTo(x,y);else map.lineTo(x,y);}map.stroke();}
 for(const gap of track.gaps){const [x,y]=point(sample((gap.start+gap.end)/2));map.fillStyle='#ffbb71';map.fillRect(x-3,y-3,6,6);}
 for(let i=5;i>=0;i--){const r=state.racers[i],[x,y]=point({p:r});map.beginPath();map.arc(x,y,i===0?5:2.8,0,Math.PI*2);map.fillStyle=i===0?'#ff865e':'#fffae4';map.fill();if(i===0){map.strokeStyle='#fffbe7';map.lineWidth=2;map.stroke();}}
}
function updateHUD(){
 const p=state.racers[0];$('rearView').classList.toggle('hidden',!keys.KeyC);$('speed').textContent=Math.round(p.speed*3.1);$('position').textContent=state.rank;$('lap').textContent=Math.min(3,Math.floor(Math.max(0,p.d)/length)+1);$('timer').textContent=C.formatTime(state.time);$('speedBar').style.width=Math.min(100,p.speed/65*100)+'%';$('driftBar').style.width=p.drift/2.5*100+'%';$('driftLabel').textContent=p.drift>.55?'ОТПУСТИ ПРОБЕЛ → ТУРБО':p.drifting?'ДЕРЖИ ЗАНОС':'ПРОБЕЛ + ПОВОРОТ';
 const info=C.ITEMS[p.item];$('item').classList.toggle('ready',!!info);$('itemIcon').textContent=info?info.icon:'?';$('itemName').textContent=info?info.name:'ПОЙМАЙ БОНУС';$('item').setAttribute('aria-label',info?'Использовать: '+info.name:'Бонус пока не получен');
 const nextGap=track.gaps.map(g=>({g,delta:C.wrap(g.start-p.nearD,length)})).sort((a,b)=>a.delta-b.delta)[0];
 $('jumpCue').classList.toggle('hidden',!(nextGap.delta<100||!p.grounded)&&p.phase==='driving');
 if(p.phase!=='driving'){$('jumpCue').textContent='↟ ВОЗВРАЩЕНИЕ НА ТРАССУ';}
 else if(!p.grounded){$('jumpCue').textContent='↗ В ПОЛЁТЕ';}
 else{$('jumpCue').textContent='↗ РАЗРЫВ '+Math.round(nextGap.g.end-nextGap.g.start)+' М · ЧЕРЕЗ '+Math.round(nextGap.delta)+' М';}
 $('elevation').textContent=Math.round(p.y)+' м';drawMap();const target=C.aimTarget(state),reticle=$('reticle');if(target){camera.updateMatrixWorld();const pos=new THREE.Vector3(target.x,target.y+2,target.z).project(camera);const visible=pos.z>0&&pos.z<1&&Math.abs(pos.x)<.95&&Math.abs(pos.y)<.9;reticle.classList.toggle('hidden',!visible);if(visible){reticle.style.left=(pos.x*.5+.5)*innerWidth+'px';reticle.style.top=(-pos.y*.5+.5)*innerHeight+'px';$('targetName').textContent=C.DRIVERS[target.hero].name+(target.shield>0?' · ЩИТ':'');}}else reticle.classList.add('hidden');
}
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;renderGarage(now);if(mode==='menu'||mode.startsWith('paused'))return;elapsed+=dt;const running=mode==='race'||mode==='countdown';if(mode==='countdown'){countdown-=dt;const n=Math.ceil(countdown);if(n!==previousCount&&n>0){previousCount=n;beep(n===1?900:500,.15);}$('countdown').textContent=countdown>0?Math.min(3,Math.ceil(countdown)):'СТАРТ!';if(countdown<=0){mode='race';noticeUntil=elapsed+1.1;$('notice').textContent='W / ↑ — ГАЗ · ПРОБЕЛ — ДРИФТ';}}
if(mode==='race'){simulationDebt+=dt;while(simulationDebt>=1/120&&!state.finished){for(const r of state.racers)r.previousPose={x:r.x,y:r.y,z:r.z,yaw:r.yaw,phase:r.phase};C.step(state,getInput(),1/120);simulationDebt-=1/120;}if(state.events.length){showNotice(state.events[state.events.length-1]);state.events.length=0;}if(state.time>1)$('countdown').textContent='';if(state.finished)finishRace();}
if(running||mode==='menu'){placeKarts(dt);for(let i=0;i<pickupMeshes.length;i++)for(let j=0;j<3;j++){const m=pickupMeshes[i][j];m.visible=state.pickups[i].cooldown===0;m.rotation.set(.15,elapsed*1.3+j,.12);m.position.y=sample(state.pickups[i].d).p.y+1.6+Math.sin(elapsed*2+j)*.2;}for(const p of particles){if(p.life>0){p.life-=dt;p.m.position.addScaledVector(p.v,dt);p.v.y-=7*dt;p.m.visible=p.life>0;}}}
updateEffects();updateAtmosphere(dt);if(mode==='menu'||running||mode==='finish')updateCamera(dt);if(elapsed>noticeUntil)$('notice').textContent='';if(engineGain){engineGain.gain.setTargetAtTime(soundOn&&mode==='race'?.026:0,audio.currentTime,.08);engine.frequency.setTargetAtTime(45+state.racers[0].speed*2.2,audio.currentTime,.06);}uiClock+=dt;if(uiClock>.05&&running){updateHUD();uiClock=0;}renderer.render(scene,camera);}
placeKarts(0);updateCamera(1);renderer.render(scene,camera);requestAnimationFrame(animate);
})();
